<?php

/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
    $languageStrings = array(
        'Map' => 'Map',
        'EXTENTIONNAME' => 'Google',
        'LBL_UPDATES_CRM' => 'Pembaruan di CRM',
        'LBL_UPDATES_GOOGLE' => 'Pembaruan di Google',
        'LBL_UPDATED' => 'Diperbarui',
        'LBL_ADDED' => 'Ditambahkan',
        'LBL_DELETED' => 'Dihapus',
        'LBL_SYNCRONIZED' => 'Disinkronkan',
        'LBL_NOT_SYNCRONIZED' => 'Anda belum melakukan sinkronisasi',
        'LBL_SYNC_BUTTON' => 'Sinkronkan Sekarang',
        'LBL_REMOVE_SYNC' => 'Hapus Sinkronisasi',
        'LBL_MORE_VTIGER' => 'Ada lebih banyak data yang akan disinkronkan di vtiger',
        'LBL_MORE_GOOGLE' => 'Ada lebih banyak data yang akan disinkronkan di Google',
        'Contact Name'=>'Nama Kontak',
        'Email'=>'Email',
        'Mobile Phone'=>'Ponsel',
        'Address' => 'Alamat',
        'Event Title'=>'Judul Acara',
        'Start Date'=>'Tanggal Mulai',
        'Until Date'=>'Tanggal Hingga',
        'Description'=>'Deskripsi',
        'Office Phone' => 'Telepon Kantor',
        'Work Phone' => 'Telepon Kerja',
        'Home Phone' => 'Telepon Rumah',
        'SYNC_SETTINGS' => 'Pengaturan Sinkronisasi Kontak',
        'LBL_SELECT_GOOGLE_GROUP_TO_SYNC' => 'Pilih Grup Google',
        'LBL_ADD_CUSTOM_FIELD_MAPPING' => 'Tambahkan Pemetaan Kustom',
        'LBL_EMAIL' => 'Email',
        'LBL_PHONE' => 'Telepon',
        'LBL_URL' => 'Url',
        'LBL_CUSTOM' => 'Kustom',
        'LBL_SELECT_SYNC_DIRECTION' => 'Pilih Arah Sinkronisasi',
        'LBL_BI_DIRECTIONAL_SYNC' => 'Sinkronkan dua arah',
        'LBL_ONLY_SYNC_FROM_GOOGLE_TO_VTIGER' => 'Hanya dari Google ke Vtiger',
        'LBL_ONLY_SYNC_FROM_VTIGER_TO_GOOGLE' => 'Hanya dari Vtiger ke Google',
        'Job Title' => 'Jabatan',
        'Company' => 'Perusahaan',
        'Birthday' => 'Ulang Tahun',
        'Phone' => 'Telepon',
        'URL' => 'Url',
        'phone' => 'Telepon',
        'email' => 'Email',
        'url' => 'Url',
        'home' => 'Rumah',
        'work' => 'Kantor',
        'custom' => 'Khusus',
        'mobile' => 'Ponsel',
        'main' => 'Utama',
        'work_fax' => 'Faks',
        'home_fax' => 'Faks Rumah',
        'pager' => 'Pager',
        'profile' => 'Profil',
        'blog' => 'Blog',
        'home-page' => 'Beranda',
        'CALENDAR_SYNC_SETTINGS' => 'Pengaturan Sinkronisasi Kalender',
        'LBL_SELECT_GOOGLE_CALENDAR_TO_SYNC' => 'Pilih Google Kalender',
        'LBL_SAVE_AND_START_SYNC' => 'Simpan dan Mulai Sinkronisasi',
        'LBL_PRIMARY' => 'Utama',
        'LBL_SYNC_FROM_GOOGLE_TO_VTIGER' => 'Sinkronkan dari Google ke Vtiger',
        'LBL_SYNC_FROM_VTIGER_TO_GOOGLE' => 'Sinkronkan dari Vtiger ke Google',
        'LBL_GOOGLE_CONNECT_MSG' => 'Hubungkan ke akun Google untuk mengambil',
        'LBL_SIGN_IN_WITH_GOOGLE' => 'Masuk dengan Google',
        'LBL_GOOGLE_ACCOUNT_DETAILS' => 'Detail Akun Google',
        'LBL_GOOGLE_ACCOUNT_SYNCED_WITH' => 'Akun Google Disinkronkan dengan',
        'LBL_CHANGE_USER' => 'Ubah Pengguna',
        'LBL_SAVE_AND_IMPORT' => 'Simpan dan Impor',
        'LBL_IMPORT_RESULTS_GOOGLE' => 'Hasil Impor Google',
		'LBL_REDIRECT_URL' => 'URL pengalihan',
		'LBL_REDIRECT_URL_MESSAGE' => 'Salin URL pengalihan berikut dan tempel di proyek Google Auth Anda seperti yang ditunjukkan gambar',
    );
    $jsLanguageStrings = array(
        'LBL_SYNC_BUTTON' => 'Sinkronkan Sekarang',
        'LBL_SYNCRONIZING' => 'Sinkronisasi....',
        'LBL_NOT_SYNCRONIZE' => 'Anda belum melakukan sinkronisasi'
    );
