<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LBL_IMPORT_STEP_1' => 'Langkah 1',
	'LBL_IMPORT_STEP_1_DESCRIPTION' => 'Pilih Berkas',
	'LBL_IMPORT_SUPPORTED_FILE_TYPES' => '	Jenis Berkas yang Didukung: .CSV, .VCF',
	'LBL_IMPORT_STEP_2' => 'Langkah 2',
	'LBL_IMPORT_STEP_2_DESCRIPTION' => 'Tentukan Format',
	'LBL_FILE_TYPE' => 'Jenis Berkas',
	'LBL_CHARACTER_ENCODING' => 'Pengodean Karakter',
	'LBL_DELIMITER' => 'Pembatas',
	'LBL_HAS_HEADER' => 'Memiliki Header',
	'LBL_IMPORT_STEP_3' => 'Langkah 3',
	'LBL_IMPORT_STEP_3_DESCRIPTION' => 'Penanganan Rekaman Duplikat',
	'LBL_IMPORT_STEP_3_DESCRIPTION_DETAILED' => 'Pilih opsi ini untuk mengaktifkan dan menetapkan kriteria penggabungan duplikat',
	'LBL_SPECIFY_MERGE_TYPE' => 'Pilih bagaimana rekaman duplikat akan ditangani',
	'LBL_SELECT_MERGE_FIELDS' => 'Pilih kolom yang cocok untuk menemukan rekaman duplikat',
	'LBL_AVAILABLE_FIELDS' => 'Kolom yang Tersedia',
	'LBL_SELECTED_FIELDS' => 'Kolom yang akan dicocokkan',
	'LBL_NEXT_BUTTON_LABEL' => 'Berikutnya',
	'LBL_IMPORT_STEP_4' => 'Langkah 4',
	'LBL_IMPORT_STEP_4_DESCRIPTION' => 'Petakan Kolom ke Kolom Modul',
	'LBL_FILE_COLUMN_HEADER' => 'Header',
	'LBL_ROW_1' => 'Baris 1',
	'LBL_CRM_FIELDS' => 'Kolom CRM',
	'LBL_DEFAULT_VALUE' => 'Nilai Default',
	'LBL_SAVE_AS_CUSTOM_MAPPING' => 'Simpan sebagai Pemetaan Kustom ',
	'LBL_IMPORT_BUTTON_LABEL' => 'Impor',
	'LBL_RESULT' => 'Hasil',
	'LBL_TOTAL_RECORDS_IMPORTED' => 'Data berhasil diimpor',
	'LBL_NUMBER_OF_RECORDS_CREATED' => 'Data dibuat',
	'LBL_NUMBER_OF_RECORDS_UPDATED' => 'Rekaman ditimpa',
	'LBL_NUMBER_OF_RECORDS_SKIPPED' => 'Rekaman dilewati',
	'LBL_NUMBER_OF_RECORDS_MERGED' => 'Rekaman digabungkan', 
	'LBL_TOTAL_RECORDS_FAILED' => 'Rekaman gagal diimpor',
	'LBL_IMPORT_MORE' => 'Impor Lebih Banyak',
	'LBL_VIEW_LAST_IMPORTED_RECORDS' => 'Rekaman Terakhir yang Diimpor',
	'LBL_UNDO_LAST_IMPORT' => 'Batalkan Impor Terakhir',
	'LBL_FINISH_BUTTON_LABEL' => 'Selesai',
	'LBL_UNDO_RESULT' => 'Batalkan Hasil Impor',
	'LBL_TOTAL_RECORDS' => 'Total Jumlah Rekaman',
	'LBL_NUMBER_OF_RECORDS_DELETED' => 'Jumlah rekaman yang dihapus',
	'LBL_OK_BUTTON_LABEL' => 'Oke',
	'LBL_IMPORT_SCHEDULED' => 'Impor Terjadwal',
	'LBL_RUNNING' => 'Sedang Berjalan',
	'LBL_CANCEL_IMPORT' => 'Batalkan Impor',
	'LBL_ERROR' => 'Kesalahan',
	'LBL_CLEAR_DATA' => 'Hapus Data',
	'ERR_LOCAL_INFILE_NOT_ON' => 'Variabel local_infile dinonaktifkan di server basis data.',
	'ERR_UNIMPORTED_RECORDS_EXIST' => 'Tidak dapat mengimpor lebih banyak data dalam batch ini. Silakan mulai impor baru.',
	'ERR_IMPORT_INTERRUPTED' => 'Impor saat ini telah terputus. Silakan coba lagi nanti',
	'ERR_FAILED_TO_LOCK_MODULE' => 'Gagal mengunci modul untuk impor. Coba lagi nanti',
	'LBL_SELECT_SAVED_MAPPING' => 'Pilih Pemetaan Tersimpan',
	'LBL_IMPORT_ERROR_LARGE_FILE' => 'Kesalahan Impor Berkas Besar ',
	'LBL_FILE_UPLOAD_FAILED' => 'Unggahan Berkas Gagal',
	'LBL_IMPORT_CHANGE_UPLOAD_SIZE' => 'Unggahan Ubah Ukuran Impor',
	'LBL_IMPORT_DIRECTORY_NOT_WRITABLE' => 'Direktori Impor tidak dapat ditulis',
	'LBL_IMPORT_FILE_COPY_FAILED' => 'Penyalinan Berkas Impor gagal',
	'LBL_INVALID_FILE' => 'Berkas Tidak Valid',
	'LBL_NO_ROWS_FOUND' => 'Tidak ada baris yang ditemukan',
	'LBL_SCHEDULED_IMPORT_DETAILS' => 'Impor Anda telah dijadwalkan dan akan dimulai dalam 15 menit. Anda akan menerima email setelah impor selesai. <br> <br>
										Pastikan server Keluar dan alamat email Anda dikonfigurasi untuk menerima notifikasi email',
	'LBL_DETAILS' => 'Detail',
	'skipped' => 'Rekaman Terlewati',
	'failed' => 'Rekaman Gagal',
	
        'LBL_IMPORT_LINEITEMS_CURRENCY'=> 'Mata Uang (Untuk Kolom Item Baris)',
        'LBL_USE_SAVED_MAPS'=>'Gunakan Peta Tersimpan',
        'LBL_IMPORT_MAP_FIELDS'=>'Petakan kolom ke kolom CRM',
        'LBL_UPLOAD_CSV'=>'Unggah Berkas CSV', 
        'LBL_UPLOAD_VCF'=>'Unggah Berkas VCF',
        'LBL_DUPLICATE_HANDLING'=>'Penanganan Duplikat',
        'LBL_FIELD_MAPPING'=>'Pemetaan Bidang',
        'LBL_IMPORT_FROM_CSV_FILE'=>'Impor dari berkas CSV',
        'LBL_SELECT_IMPORT_FILE_FORMAT'=>'Dari mana Anda ingin mengimpor ?',
        'LBL_CSV_FILE'=>'Berkas CSV',
        'LBL_VCF_FILE'=>'Berkas VCF',
        'LBL_GOOGLE'=>'Google',
        'LBL_IMPORT_COMPLETED'=>'Impor Selesai',
        'LBL_IMPORT_SUMMARY'=>'Ringkasan impor',
        'LBL_DELETION_COMPLETED'=>'Penghapusan Selesai',
        'LBL_TOTAL_RECORDS_SCANNED'=>'Total data yang dipindai',
        'LBL_SKIP_BUTTON'=>'Lewati',
    'LBL_DUPLICATE_RECORD_HANDLING' => 'Penanganan data duplikat',
    'LBL_IMPORT_FROM_VCF_FILE' => 'Impor dari berkas VCF',
    'LBL_SELECT_VCF_FILE' => 'Pilih berkas VCF',
    'LBL_DONE_BUTTON' => 'Selesai',
    'LBL_DELETION_SUMMARY' => 'Hapus ringkasan',

	'LBL_SKIP_THIS_STEP' => 'Lewati langkah ini',
	'LBL_ICS_FILE'=>'Berkas ICS',
	'LBL_UPLOAD_ICS'=>'Unggah Berkas ICS',
	'LBL_IMPORT_FROM_ICS_FILE'=>'Impor dari berkas ICS',
	'LBL_SELECT_ICS_FILE' => 'Pilih berkas ICS',
    
        //Scheduled Import translations
        'LBL_ENABLE_CRON' => '<b>Harap aktifkan tugas cron Impor Terjadwal dari penjadwal pengaturan</b>',
        'LBL_SCHEDULE_IMPORT_SUBJECT' => 'vtiger CRM - Laporan Impor Terjadwal untuk',
        'LBL_IMPORT_COMPLETED' => 'vtiger CRM baru saja menyelesaikan proses impor Anda. <br/><br/>',
        'LBL_CHECK_IMPORT_STATUS' => '<br/><br/> Kami menyarankan Anda untuk masuk ke CRM dan memeriksa beberapa catatan untuk memastikan bahwa impor telah berhasil.'
);
