<?php
/* +***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * *********************************************************************************** */

$languageStrings = array(
	'ERR_DATABASE_CONNECTION_FAILED' => 'Tidak dapat terhubung ke Server basis data',
	'ERR_DB_NOT_FOUND' => 'Basis data ini tidak ditemukan. Coba ubah pengaturan basis data',
	'ERR_DB_NOT_UTF8'  => 'Charset atau kolasi basis data tidak kompatibel dengan UTF8',
	'ERR_INVALID_MYSQL_PARAMETERS' => 'Parameter Koneksi MySQL yang ditentukan tidak valid',
	'ERR_INVALID_MYSQL_VERSION' => 'Versi MySQL tidak didukung, silakan hubungkan ke MySQL 5.1.x atau yang lebih baru',
	'ERR_UNABLE_CREATE_DATABASE' => 'Tidak dapat membuat basis data',
	'ERR_DB_SQLMODE_NOTFRIENDLY' => 'MySQL Server harus dikonfigurasi dengan:<br> sql_mode = ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION',
	'LBL_ADMIN_INFORMATION'=>'Informasi Pengguna Admin',
	'LBL_ADMIN_USER_INFORMATION' => 'Informasi Pengguna Admin',
	'LBL_CHOOSE_LANGUAGE' => 'Pilih bahasa default untuk instalasi ini:',
	'LBL_CONFIRM_CONFIGURATION_SETTINGS' => 'Konfirmasi Pengaturan Konfigurasi',
	'LBL_CREATE_NEW_DB'=>'Buat basis data baru',
	'LBL_CURRENCIES'=>'Mata Uang',
	'LBL_CURRENCY' => 'Mata Uang',
	'LBL_DATABASE_INFORMATION' => 'Informasi Basis Data',
	'LBL_DATABASE_TYPE' => 'Jenis Basis Data',
	'LBL_DATE_FORMAT'=>'Format Tanggal',
	'LBL_DB_NAME' => 'Nama Basis Data',
	'LBL_DISAGREE' => 'Tidak Setuju',
	'LBL_EMAIL' => 'Surel',
	'LBL_GD_LIBRARY' => 'Dukungan Pustaka GD',
	'LBL_HOST_NAME' => 'Nama Host',
	'LBL_I_AGREE' => 'Saya Setuju',
	'LBL_IMAP_SUPPORT' => 'Dukungan IMAP',
	'LBL_INSTALLATION_IN_PROGRESS'=>'Instalasi sedang berlangsung',
	'LBL_INSTALLATION_WIZARD' => 'Wizard Instalasi',
	'LBL_INSTALL_BUTTON' => 'Instal',
	'LBL_INSTALL_PREREQUISITES' => 'Prasyarat instalasi',
	'LBL_MORE_INFORMATION' => 'Informasi Lebih Lanjut',
	'LBL_NEXT' => 'Berikutnya',
	'LBL_ONE_LAST_THING' => 'Satu hal terakhir...',
	'LBL_PASSWORD_MISMATCH' => 'Silakan masukkan kembali kata sandi. Nilai \"Password\" dan \"Re-type password\" tidak cocok.',
	'LBL_PASSWORD' => 'Kata Sandi',
	'LBL_PHP_CONFIGURATION' => 'Konfigurasi PHP',
	'LBL_PHP_RECOMMENDED_SETTINGS'=>'Pengaturan PHP yang Direkomendasikan',
	'LBL_PHP_VERSION' => 'Versi PHP',
	'LBL_PLEASE_WAIT'=>'Silakan tunggu',
	'LBL_PRESENT_VALUE' => 'Sekarang Nilai',
	'LBL_READ_WRITE_ACCESS' => 'Akses Baca/Tulis',
	'LBL_RECHECK' => 'Periksa Ulang',
	'LBL_REQUIRED_VALUE' => 'Nilai yang Diperlukan',
	'LBL_RETYPE_PASSWORD' => 'Ketik Ulang Kata Sandi',
	'LBL_ROOT_PASSWORD' => 'Kata Sandi Root',
	'LBL_ROOT_USERNAME' => 'Nama Pengguna Root',
	'LBL_SYSTEM_CONFIGURATION' => 'Konfigurasi Sistem',
	'LBL_SYSTEM_INFORMATION' => 'Informasi Sistem',
	'LBL_TIME_ZONE' => 'Zona Waktu',
	'LBL_TRUE' => 'Benar',
	'LBL_URL' => 'URL',
	'LBL_USERNAME' => 'Nama Pengguna',
	'LBL_VTIGER7_SETUP_WIZARD_DESCRIPTION' => 'Wizard ini akan memandu Anda melalui instalasi Vtiger CRM',
	'LBL_WELCOME_TO_VTIGER7_SETUP_WIZARD' => 'Selamat datang di Panduan Pengaturan Vtiger CRM',
	'LBL_WELCOME' => 'Selamat datang',
	'LBL_ZLIB_SUPPORT' => 'Dukungan Zlib',
	'LBL_SIMPLEXML' => 'Dukungan SimpleXML',
	'MSG_DB_PARAMETERS_INVALID' => 'Pengguna basis data, kata sandi, nama host, tipe basis data, atau port yang ditentukan tidak valid',
	'MSG_DB_ROOT_USER_NOT_AUTHORIZED' => 'Pesan: Pengguna Root basis data yang ditentukan tidak memiliki izin untuk Membuat basis data atau nama Basis Data memiliki karakter khusus. Coba ubah pengaturan Basis Data',
	'MSG_DB_USER_NOT_AUTHORIZED' => 'Pengguna basis data yang ditentukan tidak memiliki akses untuk terhubung ke server basis data dari host',
	'MSG_LIST_REASONS' => 'Hal ini mungkin disebabkan oleh alasan berikut',
	'LBL_MYSQLI_CONNECT_SUPPORT'=>'Dukungan MySQLi',
	'LBL_OPEN_SSL'=>'Dukungan OpenSSL',
	'LBL_CURL'=>'Dukungan Curl',
	'LBL_MB_STRING'=>'Dukungan Mbstring',
);
