<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LBL_ADD_RECORD' => 'Add User',

	//MyPreference Blocks
	'LBL_MY_PREFERENCES'  =>  'Preferensi Saya',
	'LBL_MORE_INFORMATION'  =>  'Informasi Lebih Lanjut',
	'LBL_USERLOGIN_ROLE'  =>  'Login & Peran Pengguna',
	'LBL_USER_IMAGE_INFORMATION' => 'Foto Pengguna',
	'LBL_CURRENCY_CONFIGURATION' =>  'Konfigurasi Kolom Mata Uang dan Angka',
	'LBL_ADDRESS_INFORMATION' => 'Alamat Pengguna',
	'LBL_USER_ADV_OPTIONS' => 'Opsi Lanjutan Pengguna',
	'Asterisk Configuration'  =>  'Konfigurasi Asterisk',
	'LBL_HOME_PAGE_COMPONENTS' => 'Komponen Halaman Beranda',
	'LBL_TAG_CLOUD_DISPLAY' => 'Tampilan Tag Cloud',

	//MyPreference Fields
	'Role' => 'Peran',
	'Admin' => 'Admin',
	'User Name' => 'Nama Pengguna',
	'Default Activity View' => 'Tampilan MyCalendar Default',
	'Default Calendar View' => 'Tampilan Kalender Default',
	'Default Lead View' => 'Tampilan Prospek Default',
	'Title' => 'Judul',
	'Office Phone' => 'Telepon Kantor',
	'Department' => 'Departemen',
	'Reports To' => 'Laporan Kepada',
	'Yahoo id' => 'ID Yahoo',
	'Home Phone' => 'Telepon Rumah',
	'User Image' => 'Gambar Pengguna',
	'Date Format' => 'Format Tanggal',
	'Tag Cloud' => 'Tag Cloud',
	'Signature' => 'Tanda Tangan',
	'Street Address' => 'Alamat Jalan',
	'Password' => 'Kata Sandi',
	'Confirm Password' => 'Konfirmasi Kata Sandi',
	'LBL_SHOWN' => 'Ditampilkan',
	'LBL_HIDDEN' => 'Tersembunyi',
	'LBL_SHOW' => 'Tampilkan',
	'LBL_HIDE' => 'Sembunyikan',
	'LBL_HOME_PAGE_COMPO' => 'Komponen Halaman Beranda',
	'LBL_LOGIN_HISTORY' => 'Riwayat Masuk',
	'LBL_USERDETAIL_INFO' => 'Melihat detail pengguna',
	'LBL_DELETE_GROUP' => 'Hapus Grup',
	'LBL_DELETE_GROUPNAME' => 'Grup yang Akan Dihapus',
	'LBL_TRANSFER_GROUP' => 'Transfer Kepemilikan ke: ',
	'LBL_DELETE_USER' => 'Pengguna yang Akan Dihapus',
	'LBL_REMOVE_USER' => 'Hapus',
	'LBL_MORE_OPTIONS' => 'Opsi Lainnya',
	'LBL_TRANSFER_USER' => 'Transfer Kepemilikan ke Pengguna',
	'LBL_RESTORE_USER' => 'Pulihkan Pengguna',
	'LBL_DELETE_PROFILE' => 'Hapus Profil',
	'LBL_TRANSFER_ROLES_TO_PROFILE' => 'Transfer Peran ke Profil',
	'LBL_PROFILE_TO_BE_DELETED' => 'Profil yang Akan Dihapus',
	'INTERNAL_MAIL_COMPOSER' => 'Penyusun Surat Internal',
	'Asterisk Extension'  =>  'Ekstensi Asterisk',
	' Receive Incoming Calls'  =>  'Terima Panggilan Masuk',
	'Webservice Access Key' => 'Kunci Akses',
	'Language' => 'Bahasa',
	'Theme' =>  'Tema',
	'Time Zone'  =>  'Zona Waktu',
	'Decimal Separator'  =>  'Pemisah Desimal',
	'Digit Grouping Pattern'  =>  'Pola Pengelompokan Digit',
	'Digit Grouping Separator'  =>  'Pemisah Pengelompokan Digit',
	'Symbol Placement'  =>  'Penempatan Simbol',
	'Number Of Currency Decimals'  =>  'Jumlah Desimal Mata Uang',
	'Truncate Trailing Zeros'  =>   'Pemotongan Nol di Belakang',
	'Default Call Duration' => 'Durasi Panggilan Default (Menit)',
	'Other Event Duration' => 'Durasi Acara Lainnya (Menit)',
	'Calendar Hour Format' => 'Format Jam Kalender Kalendar',
	'Tag Cloud' => 'Tag Cloud',

	//Time zones-Dont change any value
	'Kwajalein'  =>  '(UTC-12:00) International Date Line West',
	'Pacific/Midway'  =>  '(UTC-11:00) Coordinated Universal Time-11',
	'Pacific/Samoa'  =>  '(UTC-11:00) Samoa',
	'Pacific/Honolulu'  =>  '(UTC-10:00) Hawaii',
	'America/Anchorage'  =>  '(UTC-09:00) Alaska',
	'America/Los_Angeles'  =>  '(UTC-08:00) Pacific Time (US &amp; Canada)',
	'America/Tijuana'  =>  '(UTC-08:00) Tijuana, Baja California',
	'America/Denver'  =>  '(UTC-07:00) Mountain Time (US &amp; Canada)',
	'America/Chihuahua'  =>  '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
	'America/Mazatlan'  =>  '(UTC-07:00) Mazatlan',
	'America/Phoenix'  =>  '(UTC-07:00) Arizona',
	'America/Regina'  =>  '(UTC-06:00) Saskatchewan',
	'America/Tegucigalpa'  =>  '(UTC-06:00) Central America',
	'America/Chicago'  =>  '(UTC-06:00) Central Time (US &amp; Canada)',
	'America/Mexico_City'  =>  '(UTC-06:00) Mexico City',
	'America/Monterrey'  =>  '(UTC-06:00) Monterrey',
	'America/New_York'  =>  '(UTC-05:00) Eastern Time (US &amp; Canada)',
	'America/Bogota'  =>  '(UTC-05:00) Bogota, Lima, Quito',
	'America/Lima'  =>  '(UTC-05:00) Lima',
	'America/Rio_Branco'  =>  '(UTC-05:00) Rio Branco',
	'America/Indiana/Indianapolis'  =>  '(UTC-05:00) Indiana (East)',
	'America/Caracas'  =>  '(UTC-04:30) Caracas',
	'America/Halifax'  =>  '(UTC-04:00) Atlantic Time (Canada)',
	'America/Manaus'  =>  '(UTC-04:00) Manaus',
	'America/Santiago'  =>  '(UTC-04:00) Santiago',
	'America/La_Paz'  =>  '(UTC-04:00) La Paz',
	'America/Cuiaba'  =>  '(UTC-04:00) Cuiaba',
	'America/Asuncion'  =>  '(UTC-04:00) Asuncion',
	'America/St_Johns'  =>  '(UTC-03:30) Newfoundland',
	'America/Argentina/Buenos_Aires'  =>  '(UTC-03:00) Buenos Aires',
	'America/Sao_Paulo'  =>  '(UTC-03:00) Brasilia',
	'America/Godthab'  =>  '(UTC-03:00) Greenland',
	'America/Montevideo'  =>  '(UTC-03:00) Montevideo',
	'Atlantic/South_Georgia'  =>  '(UTC-02:00) Mid-Atlantic',
	'Atlantic/Azores'  =>  '(UTC-01:00) Azores',
	'Atlantic/Cape_Verde'  =>  '(UTC-01:00) Cape Verde Is.',
	'Europe/London'  =>  '(UTC) London, Edinburgh, Dublin, Lisbon',
	'UTC'  =>  '(UTC) Coordinated Universal Time, Greenwich Mean Time',
	'Africa/Monrovia'  =>  '(UTC) Monrovia, Reykjavik',
	'Africa/Casablanca'  =>  '(UTC) Casablanca',
	'Europe/Belgrade'  =>  '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
	'Europe/Sarajevo'  =>  '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
	'Europe/Brussels'  =>  '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
	'Africa/Algiers'  =>  '(UTC+01:00) West Central Africa',
	'Europe/Amsterdam'  =>  '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
	'Europe/Minsk'  =>  '(UTC+02:00) Minsk',
	'Africa/Cairo'  =>  '(UTC+02:00) Cairo',
	'Europe/Helsinki'  =>  '(UTC+02:00) Helsinki, Riga, Sofia, Tallinn, Vilnius',
	'Europe/Athens'  =>  '(UTC+02:00) Athens, Bucharest',
	'Europe/Istanbul'  =>  '(UTC+02:00) Istanbul',
	'Asia/Jerusalem'  =>  '(UTC+02:00) Jerusalem',
	'Asia/Amman'  =>  '(UTC+02:00) Amman',
	'Asia/Beirut'  =>  '(UTC+02:00) Beirut',
	'Africa/Windhoek'  =>  '(UTC+02:00) Windhoek',
	'Africa/Harare'  =>  '(UTC+02:00) Harare',
	'Asia/Kuwait'  =>  '(UTC+03:00) Kuwait, Riyadh',
	'Asia/Baghdad'  =>  '(UTC+03:00) Baghdad',
	'Africa/Nairobi'  =>  '(UTC+03:00) Nairobi',
	'Europe/Moscow'  =>  '(UTC+03:00) Moscow, Volgograd',
	'Asia/Tehran'  =>  '(UTC+03:30) Tehran',
	'Asia/Tbilisi'  =>  '(UTC+04:00) Tbilisi',
	'Asia/Muscat'  =>  '(UTC+04:00) Abu Dhabi, Muscat',
	'Asia/Baku'  =>  '(UTC+04:00) Baku',
	'Asia/Yerevan'  =>  '(UTC+04:00) Yerevan',
	'Asia/Karachi'  =>  '(UTC+05:00) Islamabad, Karachi',
	'Asia/Tashkent'  =>  '(UTC+05:00) Tashkent',
	'Asia/Kolkata'  =>  '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
	'Asia/Colombo'  =>  '(UTC+05:30) Sri Jayawardenepura',
	'Asia/Katmandu'  =>  '(UTC+05:45) Kathmandu',
	'Asia/Dhaka'  =>  '(UTC+06:00) Dhaka',
	'Asia/Almaty'  =>  '(UTC+06:00) Almaty',
	'Asia/Yekaterinburg'  =>  '(UTC+06:00) Ekaterinburg',
	'Asia/Rangoon'  =>  '(UTC+06:30) Yangon (Rangoon)',
	'Asia/Novosibirsk'  =>  '(UTC+07:00) Novosibirsk',
	'Asia/Bangkok'  =>  '(UTC+07:00) Bangkok, Jakarta',
	'Asia/Brunei'  =>  '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
	'Asia/Krasnoyarsk'  =>  '(UTC+08:00) Krasnoyarsk',
	'Asia/Ulaanbaatar'  =>  '(UTC+08:00) Ulaan Bataar',
	'Asia/Kuala_Lumpur'  =>  '(UTC+08:00) Kuala Lumpur, Singapore',
	'Asia/Taipei'  =>  '(UTC+08:00) Taipei',
	'Australia/Perth'  =>  '(UTC+08:00) Perth',
	'Asia/Irkutsk'  =>  '(UTC+09:00) Irkutsk',
	'Asia/Seoul'  =>  '(UTC+09:00) Seoul',
	'Asia/Tokyo'  =>  '(UTC+09:00) Tokyo',
	'Australia/Darwin'  =>  '(UTC+09:30) Darwin',
	'Australia/Adelaide'  =>  '(UTC+09:30) Adelaide',
	'Australia/Canberra'  =>  '(UTC+10:00) Canberra, Melbourne, Sydney',
	'Australia/Brisbane'  =>  '(UTC+10:00) Brisbane',
	'Australia/Hobart'  =>  '(UTC+10:00) Hobart',
	'Asia/Vladivostok'  =>  '(UTC+10:00) Vladivostok',
	'Pacific/Guam'  =>  '(UTC+10:00) Guam, Port Moresby',
	'Asia/Yakutsk'  =>  '(UTC+10:00) Yakutsk',
	'Etc/GMT-11' => '(UTC+11:00) Solomon Is., New Caledonia',
	'Pacific/Fiji'  =>  '(UTC+12:00) Fiji',
	'Asia/Kamchatka'  =>  '(UTC+12:00) Kamchatka',
	'Pacific/Auckland'  =>  '(UTC+12:00) Auckland',
	'Asia/Magadan'  =>  '(UTC+12:00) Magadan',
	'Pacific/Tongatapu'  =>  '(UTC+13:00) Nukualofa',

	'Summary' => 'Ringkasan',
	'Detail' => 'Rincian',
	'LBL_USER_LIST_DETAILS' => 'Detail',

	'LBL_OLD_PASSWORD' => 'Kata Sandi Lama',
	'LBL_CHANGE_PASSWORD' => 'Ubah Kata Sandi',
	'LBL_NEW_PASSWORD' => 'Kata Sandi Baru',
	'LBL_CONFIRM_PASSWORD' => 'Konfirmasi Kata Sandi',
	'LBL_CHANGE_ACCESS_KEY' => 'Ubah Kunci Akses',
	'LBL_ACCESS_KEY_UPDATED_SUCCESSFULLY' => 'Kunci akses berhasil diperbarui',
	'LBL_FAILED_TO_UPDATE_ACCESS_KEY' => 'Gagal memperbarui kunci akses',
	'LBL_TRANSFER_OWNERSHIP' => 'Transfer Pemilik',
	'LBL_LOGIN_AS' => 'Masuk sebagai ',
	'LBL_USER_DELETED_SUCCESSFULLY' => 'Pengguna berhasil dihapus',
	'LBL_ACTIVE_USERS' => 'Pengguna Aktif',
	'LBL_INACTIVE_USERS' => 'Pengguna Tidak Aktif',
	'LBL_CREATE_USER' => 'Buat Pengguna',
	'LBL_DELETE_USER_PERMANENTLY' => 'Hapus Pengguna Secara Permanen',
	'LBL_DELETE_USER_PERMANENTLY_INFO' => 'Menghapus pengguna secara permanen akan mentransfer semua data, termasuk komentar dan riwayat, ke pengguna baru.',
	'LBL_RESTORE' => 'Pulihkan',
	'LBL_USER_RESTORED_SUCCESSFULLY' => 'Pengguna berhasil dipulihkan',
	//Login strings
	'LBL_TO_CRM' => 'Masuk ke Vtiger CRM',
	'LBL_INVALID_USER_OR_PASSWORD' => 'Nama pengguna atau kata sandi tidak valid.',
	'LBL_INVALID_USER_OR_EMAIL' => 'Nama pengguna atau alamat email tidak valid.',
	'LBL_EMAIL_SEND' => 'Anda telah mengirim email untuk mengatur ulang kata sandi Anda.',
	'ForgotPassword' => 'Lupa Kata Sandi',
	'LBL_CONNECT_WITH_US' => 'Hubungi Kami',
	'LBL_GET_MORE' => 'Dapatkan lebih banyak dari Vtiger',

	'LBL_TRANSFER_RECORDS_TO_USER' => 'Transfer data ke pengguna',
	'LBL_USER_TO_BE_DELETED' => 'Pengguna yang Akan Dihapus',
	'LBL_ALMOST_THERE'	=>	'Hampir selesai!',
	'LBL_ABOUT_ME'		=>	'Tentang Saya',
	'LBL_WE_PROMISE_TO_KEEP_THIS_PRIVATE'	=>	'(Kami berjanji untuk menjaga privasi ini)',
	'LBL_ALL_FIELDS_BELOW_ARE_REQUIRED'		=>	'(Semua kolom di bawah ini wajib diisi)',
	'LBL_GET_STARTED'	=> 'Mulai',
	'LBL_YOUR_CONTACT_NUMBER' => 'Nomor Kontak Anda',
	'LBL_WHERE_ARE_YOU_FROM' =>	'Dari mana asal Anda?',
	'LBL_SELECT_COUNTRY'	=> 'Pilih Negara',
	'LBL_COMPANY_SIZE'		=> 'Ukuran Perusahaan',
	'LBL_JOB_TITLE'			=> 'Jabatan',
	'LBL_DEPARTMENT'		=> 'Departemen',
	'LBL_BASE_CURRENCY'		=> 'Mata Uang Dasar',
	'LBL_CHOOSE_BASE_CURRENCY'	=> 'Pilih Mata Uang Dasar',
	'LBL_OPERATING_CURRENCY'	=> 'Mata uang dasar tidak dapat diubah nanti. Pilih mata uang operasional Anda',
	'LBL_LANGUAGE' => 'Bahasa',
	'LBL_CHOOSE_LANGUAGE'	=> 'Pilih Bahasa',
	'LBL_CHOOSE_TIMEZONE'	=> 'Pilih Zona Waktu',
	'LBL_DATE_FORMAT'		=> 'Format Tanggal',
	'LBL_CHOOSE_DATE_FORMAT'=> 'Pilih Format Tanggal',
	'LBL_PHONE'	=> 'Telepon',
	'Space' => 'Spasi',
	//picklist values for Default Calendar View field in MyPreference Page
	'ListView' => 'Tampilan Daftar',
	'MyCalendar' => 'Kalender Saya',
	'SharedCalendar' => 'Kalender Bersama',

	'LBL_CHANGE_OWNER' => 'Ubah Pemilik',
	'LBL_TRANSFER_OWNERSHIP' => 'Transfer Kepemilikan',
	'LBL_TRANSFER_OWNERSHIP_TO_USER' => 'Transfer Kepemilikan ke Pengguna',
	'LBL_OWNERSHIP_TRANSFERRED_SUCCESSFULLY' => 'Pemilik CRM berhasil diubah',
	'LBL_OWNERSHIP_TRANSFERRED_FAILED' => 'Gagal mengubah pemilik CRM',
	'Account Owner' => 'Pemilik Akun',
	'Starting Day of the week' => 'Hari Mulai dalam Seminggu',
	'Day starts at' => 'Hari dimulai pada',
	'Default Event Status' => 'Status Peristiwa Default',
	'Default Activity Type' => 'Jenis Aktivitas Default',
	'Default Record View' => 'Tampilan Rekaman Default',
	'Left Panel Hide' => 'Sembunyikan Panel Kiri',
	'Row Height' => 'Tinggi Baris',

	//Change Username labels
	'LBL_CHANGE_USERNAME' => 'Ubah Nama Pengguna',
	'LBL_USERNAME_CHANGED' => 'Nama pengguna berhasil diubah',
	'ERROR_CHANGE_USERNAME' => 'Terjadi kesalahan saat mengubah nama pengguna. Silakan coba lagi',

	'LBL_RESTORE_USER_FAILED' => 'Gagal memulihkan pengguna. Sudah ada pengguna CRM dengan nama pengguna ini.',

	'LBL_DUPLICATE_USER_EXISTS' => 'Pengguna Sudah Ada',

	/* For Vtiger7*/
	'LBL_USERS_SETTINGS' => 'PENGATURAN PENGGUNA',
	'LBL_TEMPLATES' => 'Templat',
);

$jsLanguageStrings = array(

	//Curency seperator validation messages
	'JS_ENTER_OLD_PASSWORD'=>'Silakan masukkan kata sandi lama Anda.',
	'JS_ENTER_NEW_PASSWORD'=>'Silakan masukkan kata sandi baru Anda.',
	'JS_ENTER_CONFIRMATION_PASSWORD'=>'Silakan masukkan konfirmasi kata sandi Anda.',
	'JS_REENTER_PASSWORDS'=>'Silakan masukkan kembali kata sandi. Nilai \"kata sandi baru\" dan \"konfirmasi kata sandi\" tidak cocok.',
	'JS_INVALID_PASSWORD'=>'Anda harus menentukan nama pengguna dan kata sandi yang valid.',
	'JS_PASSWORD_CHANGE_FAILED_1'=>'Perubahan kata sandi pengguna gagal untuk ',
	'JS_PASSWORD_CHANGE_FAILED_2'=>' gagal.  Kata sandi baru harus set.',
	'JS_PASSWORD_INCORRECT_OLD'=>'Kata sandi lama yang ditentukan salah. Masukkan kembali informasi kata sandi.',
	'JS_ENTERED_CURRENT_USERNAME_MSG' => 'Anda memasukkan nama pengguna saat ini. Silakan masukkan nama pengguna baru.',
	'JS_NEW_ACCESS_KEY_REQUESTED' => 'Kunci akses baru diminta',
	'JS_CHANGE_ACCESS_KEY_CONFIRMATION' => 'Anda telah meminta kunci akses baru.&lt;br&gt;&lt;br&gt;Dengan ketentuan kunci akses yang baru, Anda harus mengganti kunci akses lama dengan yang baru di semua ekstensi yang terpasang.&lt;br&gt;&lt;br&gt;Apakah Anda ingin melanjutkan?',
);