<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(

	// Footer
	'APPTITLE' => 'Vtiger CRM',
	'POWEREDBY'=> 'Didukung oleh Vtiger CRM',
	'LBL_READ_LICENSE' => 'Baca Lisensi',
	'LBL_PRIVACY_POLICY' => 'Kebijakan Privasi',

	// Common Actions
	'LBL_NEW' => 'Baru',
	'LBL_LINKED' => 'Tertaut',
	'LBL_SELECT_ALL' => 'Pilih semua',
	'LBL_SELECT_TO_LOAD_LIST' => 'Pilih untuk Memuat Daftar',
	'LBL_CREATING_NEW' => 'Membuat Baru',
	'LBL_ADDING_NEW' => 'Menambahkan baru',
	'LBL_EDITING' => 'Mengedit',
	'LBL_SAVE' => 'Simpan',
	'LBL_CANCEL' => 'Batal',
	'LBL_BACK' => 'Kembali',
	'LBL_IMPORT' => 'Impor',
	'LBL_EXPORT' => 'Ekspor',
	'LBL_FIND_DUPLICATES' => 'Temukan Duplikat',
	'LBL_MORE' => 'Lebih',
	'LBL_LESS' => 'Kurang',
	'LBL_ACTIONS' => 'Tindakan',
	'LBL_ADD' => 'Tambah',
	'LBL_EDIT' => 'Sunting',
	'LBL_DELETE' => 'Hapus',
	'LBL_COMMENT' => 'Komentar',
	'LBL_STARRED' => 'Berhenti Mengikuti',
	'LBL_NOT_STARRED' => 'Klik untuk mengikuti',
	'LBL_QUICK_VIEW' => 'Tampilan Cepat',
	'LBL_NOTIFICATION_CENTER' => 'Pusat Notifikasi',
	'LBL_NOTIFICATION' => 'Notifikasi',
	'LBL_STARRED_RECORD_TO' => '%s sampai %s',
	'LBL_STARRED_RECORD_UPDATED' => '%s diperbarui %s',
	'LBL_SETTINGS'=> 'Pengaturan',
	'LBL_ADD_COMMENT' => 'Tambah Komentar',
	'LBL_EDIT_FIELDS' => '%s Kolom & Tata Letak',
	'LBL_EDIT_WORKFLOWS' => '%s Alur Kerja',
	'LBL_EDIT_PICKLIST_VALUES' => 'Nilai Daftar Pilihan',
	'LBL_EDIT_MAILSCANNER' => 'Konverter Email',
	'LBL_RECORD_DELETE' => 'Data yang Anda coba lihat telah dihapus.',
	'LBL_RECORD_NOT_FOUND' => 'Rekaman yang Anda coba akses tidak ditemukan',
	'LBL_EDIT_REASON' => 'Alasan edit',
	//'LBL_EDIT_CURRENT_FILTER' => 'Edit Filter Saat Ini',
	//'LBL_DELETE_CURRENT_FILTER' => 'Hapus Filter Saat Ini',
	'LBL_SELECT' => 'Pilih',
	'LBL_CLEAR' => 'Bersih',
	'LBL_YES' => 'Ya',
	'LBL_NO' => 'Tidak',
	'LBL_SHOW_COMPLETE_DETAILS' => 'Detail Lengkap',
	'LBL_MINILIST_FIELDS_ARE_NOT_AVAILABLE_FOR_YOU' => 'Maaf! Kolom Minilist tidak tersedia untuk Anda.',
	'LBL_MASS_EDITING' => 'Edit Massal',
	'LBL_DESELECT_ALL_RECORDS' => 'Batalkan Pilihan Data di Semua Halaman',
	'LBL_QUICK_CREATE' => 'Buat Cepat',
	'LBL_QUICK_EDIT' => 'Edit Cepat',
	'LBL_SEND_EMAIL' => 'Kirim Email',
	//SEND EMAIL translations
	'LBL_ALL_EMAILS' => 'Semua akun email',
	'LBL_MUTIPLE_EMAIL_SELECT_ONE' => 'Silakan pilih salah satu opsi di bawah ini',
	//SEND EMAIL translations
	'LBL_GO_TO_FULL_FORM' => 'Buka formulir lengkap',
	'LBL_SEND_SMS' => 'Kirim SMS',
	'LBL_FOUND' => 'ditemukan',
	'LBL_CLICK_ADD' => 'Klik untuk menambahkan',
	'LBL_ADD_MORE_FIELDS' => 'Tambahkan kolom lainnya',
	'LBL_ADD_NOTE' => 'Tambah Dokumen',
	'LBL_CREATE_NEW' => 'Buat Baru',
	'LBL_ADD_EVENT' => 'Tambah Acara',
	'LBL_ADD_TASK' => 'Tambah Tugas',
	'LBL_MARKETING_AND_SALES' => 'PEMASARAN & PENJUALAN',
	'LBL_TOOLS_HEADER' => 'ALAT',
	'LBL_SUPPORT' => 'DUKUNGAN',
	'LBL_INVENTORY' => 'INVENTARIS',
	'LBL_ANALYTICS' => 'ANALYTICS',
	'LBL_CONTACT' => 'MANAJEMEN KONTAK',
	'LBL_HOME' => 'Beranda',
	'LBL_NO_ATTACHMENTS' => 'Tidak Ada Lampiran',
	'LBL_COMPOSE_EMAIL_WARNING' => ' Peringatan: Email Anda mungkin masuk ke spam. Tambahkan Vtiger sebagai pengirim resmi untuk domain Anda. Pelajari selengkapnya',
	// Common Link Labels
	'LBL_REARRANGE_DASHBOARD_TABS' => 'Atur Ulang Tab',
	'LBL_DONE' => 'Selesai',
	'LBL_DELETE_DASHBOARD_TAB' =>'Hapus Tab',
	'LBL_DASHBOARD_TAB_ALREADY_EXIST' => 'Nama Tab Sudah Ada',
	'LBL_TABS_LIMIT_EXCEEDED' => 'Maaf! Tidak dapat menambahkan lebih dari 10 tab',
	'LBL_TODOS' => 'Tugas',
	'LBL_LAST_VIEWED_RECORDS' => 'Rekaman Terakhir Dilihat',
	'LBL_DASHBOARD' => 'Dasbor',
	'LBL_USER_SETTINGS' => 'Pengaturan Pengguna',
	'LBL_MY_PREFERENCES' => 'Preferensi Saya',
	'LBL_SIGN_OUT' => 'Keluar',
	'LBL_HELP' => 'Bantuan',
	'LBL_DOCUMENTATION' => 'Dokumentasi',
	'LBL_VIDEO_TUTORIAL' => 'Tutorial Video',
	'LBL_FEEDBACK' => 'Umpan Balik',
	'LBL_CHAT_SUPPORT'=>'Dukungan Obrolan',
	'LBL_CRM_SETTINGS' => 'Pengaturan CRM',
	'LBL_ON_DEMAND_ADMIN' => 'Tambah/Hapus Pengguna',
	'LBL_ANNOUNCEMENT' => 'Pengumuman',
	'LBL_CALENDAR' => 'Kalender',
	'LBL_POST' => 'Posting',
	'LBL_GUIDER' => 'Panduan',
	'LBL_VIDEOS' => 'Video',
	'LBL_DISPLAY_TYPE' => 'Tampilan Ketik',
	'LBL_DISPLAY_WIDETYPE' => 'Lebar',
	'LBL_DISPLAY_MEDIUMTYPE' => 'Sedang',
	'LBL_DISPLAY_NARROWTYPE' => 'Sempit',
	'LBL_TAG_THIS_RECORD' => 'Tandai Rekaman Ini',
	'LBL_SAME_TAG_EXISTS' => 'Ada tag duplikat',
	'LBL_MAKE_PUBLIC' => 'Buat Publik',
	'LBL_PAGE' => 'Halaman',
	'LBL_LISTVIEW_PAGE_JUMP' => 'Lompat Halaman',
	'LBL_LISTVIEW_JUMP_TO' => 'Lompat Ke',
	'LBL_PROFILE_PASSWORD' => 'Profil / Kata Sandi',
	'LBL_INFO' => 'Info',
	'LBL_CANT_MOVE_FROM_PUBLIC_TO_PRIVATE' => 'Tidak dapat untuk berpindah dari tag Publik ke Private tag.',
	'LBL_EDIT_TAG'=>'Edit Tag',
	'LBL_NO_TAG_EXISTS' => 'Tidak Ada Tag' ,
	'LBL_RELATED_USERS' => 'Pengguna Terkait',

	// Common Fields
	'LBL_USER' => 'Pengguna',
	'LBL_GROUP' => 'Grup',
	'Last Modified By' => 'Terakhir Dimodifikasi Oleh',
	'Created Time' => 'Waktu Dibuat',
	'Modified Time' => 'Waktu Dimodifikasi',
	'Description' => 'Deskripsi',
	'Assigned To'=>'Ditugaskan Kepada',

	//Loading Labels
	'LBL_LOADING' => 'Memuat',
	'LBL_LOADING_WIDGET' => 'Memuat Widget',
	'LBL_LOADING_LISTVIEW_CONTENTS'	=> 'Memuat, Harap tunggu.',

	// Detail View
	'LBL_HISTORY' => 'Riwayat',
	'LBL_UPDATES' => 'Pembaruan',
	'LBL_SHOW_FULL_DETAILS' => 'Tampilkan Detail Lengkap',
	'LBL_SUMMARY_DETAILS' => 'Ringkasan Detail',
	'LBL_ADD_NEW_COMMENT' =>'Tambah Komentar Baru',
	'LBL_NO_UPDATES' => 'Tidak Ada Pembaruan',
	'LBL_ACTIVITIES' => 'Aktivitas',
	'LBL_NO_PENDING_ACTIVITIES' => 'Tidak ada aktivitas yang tertunda',
	'LBL_SUMMARY' => 'Ringkasan',
	'LBL_KEY_FIELD' => 'Kolom Kunci',
	'LBL_DETAILS' => 'Detail',
	'LBL_NAME_EMAIL' => 'Nama dan Email',

	// Popup window
	'LBL_SEARCH_FOR' => 'Cari Untuk',
	'LBL_IN' => 'di',
	'LBL_TYPE_SEARCH' => 'Ketik untuk mencari',
	'LBL_SEARCH_BUTTON' => 'Tombol Pencarian',
	'LBL_ADVANCE_SEARCH' => 'Lanjutan',
	'LBL_LOADING_PLEASE_WAIT' => 'Memuat, Harap tunggu.',
	'LBL_PLEASE_SELECT_MODULE' => 'Silakan pilih modul apa pun untuk dicari',

	//DropDown Category
	'LBL_USERS' => 'Pengguna',
	'LBL_GROUPS' => 'Grup',

	//EditView Form Links
	'LBL_FULL_FORM' => 'Formulir Lengkap',
	'LBL_SIMPLE_FORM' => 'Formulir Sederhana',

	//Recent Comments
	'LBL_IS_REMOVED' => 'Dihapus',
	'LBL_ADD_YOUR_COMMENT_HERE' => 'Tambahkan komentar Anda di sini...',
	'LBL_REASON_FOR_CHANGING_COMMENT' => 'Alasan mengubah komentar',
	'LBL_REPLY' => 'Balas',
	'LBL_VIEW_THREAD' => 'Lihat Utas',
	'LBL_NO_COMMENTS' => 'Tidak ada komentar',
	'LBL_REPLIES' => 'balasan',
	'LBL_REPLY_ALL' => 'Balas semua',
	'LBL_INTERNAL_COMMENT_TOOTLTIP' => 'Pelanggan tidak dapat melihat komentar ini',
	'LBL_EXTERNAL_COMMENT_TOOTLTIP' => 'Pelanggan mungkin melihat komentar ini melalui notifikasi atau portal pelanggan',

	//Translation for all modules
	'Accounts' => 'Organisasi',
	'Assets' => 'Aset',
	'Calendar' => 'Kalender',
	'Campaigns' => 'Kampanye',
	'Contacts' => 'Kontak',
	'Documents' => 'Dokumen',
	'Leads' => 'Prospek',
	'ModComments' => 'Komentar',
	'Potentials' => 'Peluang',
	'PriceBooks' => 'Buku Harga',
	'Products' => 'Produk',
	'Project' => 'Proyek',
	'ProjectMilestone' => 'Milestone Proyek',
	'ProjectTask' => 'Tugas Proyek',
	'ServiceContracts' => 'Kontrak Layanan',
	'Services' => 'Layanan',
	'Vendors' => 'Vendor',
	'Rss' => 'RSS',
	'Quotes'=>'Penawaran',
	'PurchaseOrder'=>'Pesanan Pembelian',
	'SalesOrder'=>'Pesanan Penjualan',
	'Invoice'=>'Faktur',
	'MailManager' => 'Manajer Email',
	'Activities' => 'Aktivitas',
	'Portal' => 'Situs Kami',
	'Email Templates' => 'Templat Email',
	'Recycle Bin' => 'Keranjang Sampah',

	//Basic String Translation
	'LBL_ADD_RECORD' => 'Tambah Rekaman',
	'LBL_RECENTLY_MODIFIED' => 'Baru Dimodifikasi',
	'LBL_RECORDS_LIST' => 'Daftar Rekaman',
	'LBL_RECORD_SUMMARY' => 'Ringkasan Modul',
	'LBL_RECORD_SUMMARY' => 'Detail Modul',
	'LBL_ACCESS_DENIED_FOR' => 'Akses Ditolak untuk',
	'LBL_GO_BACK' => 'Kembali',
	'LBL_NO_DATA_AVAILABLE' => 'Tidak ada data tersedia',

	// Global Search
	'LBL_GLOBAL_SEARCH' => 'Ketik kata kunci dan tekan enter',
	'LBL_ALL_RECORDS' => 'Semua Data',
	'LBL_NO_RECORDS_FOUND' => 'Tidak ada data yang ditemukan',

	//Filters & Advance Filter
	'LBL_AND' => 'dan',
	'LBL_OR' => 'atau',
	'LBL_APPLBL_NONEROVE' => 'Setujui',
	'LBL_DENY' => 'Tolak',
	'LBL_EQUALS' => 'sama dengan',
	'LBL_NOT_EQUAL_TO' => 'tidak sama dengan',
	'LBL_STARTS_WITH' => 'dimulai dengan',
	'LBL_ENDS_WITH' => 'diakhiri dengan',
	'LBL_CONTAINS' => 'berisi',
	'LBL_DOES_NOT_CONTAIN' => 'tidak berisi',
	'LBL_LESS_THAN' => 'kurang dari',
	'LBL_GREATER_THAN' => 'lebih besar dari',
	'LBL_LESS_THAN_OR_EQUAL' => 'kurang atau sama dengan',
	'LBL_GREATER_OR_EQUAL' => 'lebih besar atau sama dengan',
	'LBL_BEFORE' => 'sebelum',
	'LBL_AFTER' => 'sesudah',
	'LBL_BETWEEN' => 'di antara',
	'LBL_SEARCH' => 'Cari',
	'LBL_SEARCH_IN' => 'Cari di',
	'LBL_ADD_CONDITION' => 'Tambahkan Kondisi',
	'LBL_ADD_GROUP' => 'Tambahkan Grup Kondisi',
	'LBL_FILTER_CONDITIONS' => 'Daftar Kondisi',
	'LBL_ALL_CONDITIONS' => 'Semua Kondisi',
	'LBL_ALL_CONDITIONS_DESC' => 'Semua kondisi harus terpenuhi',
	'LBL_ANY_CONDITIONS' => 'Semua Kondisi',
	'LBL_ANY_CONDITIONS_DESC' => 'Setidaknya satu kondisi harus terpenuhi',
	'LBL_SELECT_FIELD' => 'Pilih Kolom',
	'LBL_SELECT_MODULE' => 'Pilih Modul',
	'LBL_CREATE_NEW_FILTER' => 'Buat Daftar Baru',
	'All' => 'Semua',
	'Others' => 'Others',
	'Pending' => 'Tertunda',
	'Public' => 'Public',

	//Advance Search
	'LBL_SAVE_FILTER' => 'Simpan Daftar',
	'LBL_SAVE_MODIFY_FILTER' => 'Simpan/Ubah Pencarian',
	'LBL_SEARCH_RESULTS' => 'Hasil Pencarian',
	'LBL_SAVE_AS_FILTER' => 'Simpan Sebagai Daftar',

	//Exception String Translation
	'LBL_NOT_ACCESSIBLE' => 'Akses ditolak',

	//Line Items
	'LBL_ITEM_DETAILS'=> 'Detail Item',
	'LBL_CURRENCY' => 'Mata Uang',
	'LBL_TAX_MODE' => 'Mode Pajak',
	'LBL_INDIVIDUAL' => 'Individu',
	'LBL_GROUP' => 'Grup',
	'LBL_TOOLS' => 'Perkakas',
	'LBL_ITEM_NAME' => 'Nama Barang',
	'LBL_QTY_IN_STOCK' => 'Stok',
	'LBL_QTY' => 'Jumlah',
	'LBL_LIST_PRICE' => 'Harga Jual',
	'LBL_TOTAL' => 'Total',
	'LBL_NET_PRICE' => 'Harga Bersih',
	'LBL_DISCOUNT' => 'Diskon',
	'LBL_TOTAL_AFTER_DISCOUNT' => 'Total Setelah Diskon',
	'LBL_TAX' => 'Pajak',
	'LBL_ADD_PRODUCT' => 'Tambah Produk',
	'LBL_ADD_SERVICE' => 'Tambah Layanan',
	'LBL_LI_ADD_PRODUCT' => 'Produk',
	'LBL_LI_ADD_SERVICE' => 'Layanan',
	'LBL_ITEMS_TOTAL' => 'Total Barang',
	'LBL_SHIPPING_AND_HANDLING_CHARGES' => 'Biaya Pengiriman & Penanganan',
	'LBL_PRE_TAX_TOTAL' => 'Total Sebelum Pajak',
	'LBL_TAX_FOR_SHIPPING_AND_HANDLING' => 'Pajak untuk Pengiriman dan Penanganan',
	'LBL_SET_SHIPPING_AND_HANDLING_TAXES_FOR' => 'Tetapkan Pajak S&H untuk',
	'LBL_ADJUSTMENT' => 'Penyesuaian',
	'LBL_DEDUCT' => 'Potong',
	'LBL_GRAND_TOTAL' => 'Total Keseluruhan',
	'LBL_ZERO_DISCOUNT' => 'Diskon Nol',
	'LBL_OF_PRICE' => 'Harga',
	'LBL_DIRECT_PRICE_REDUCTION' => 'Penurunan Harga Langsung',
	'LBL_SET_DISCOUNT_FOR' => 'Tetapkan Diskon Untuk',
	'LBL_STOCK_NOT_ENOUGH' => 'Stok tidak cukup',
	'LBL_MAX_QTY_SELECT' => 'Nilai maksimum adalah',
	'LBL_DRAG' => 'Seret',
	'LBL_TOTAL_TAX_AMOUNT' => 'Total Pajak',
	'LBL_DIRECT_AMOUNT_DISCOUNT' => 'Diskon Langsung',
	'LBL_FINAL_DISCOUNT_AMOUNT' => 'Jumlah Diskon Akhir',
	'LBL_MORE_CURRENCIES' => 'lebih banyak mata uang',
	'LBL_SET_TAX_FOR' => 'Tetapkan Pajak untuk',
	'LBL_GROUP_TAX' => 'Pajak Grup',
	'LBL_BILLING_ADDRESS_FROM' => 'Salin Alamat Penagihan dari',
	'LBL_SHIPPING_ADDRESS_FROM' => 'Salin Alamat Pengiriman dari',
	'LBL_COPY_SHIPPING_ADDRESS' => 'Alamat Pengiriman',
	'LBL_COPY_BILLING_ADDRESS' => 'Alamat Penagihan',
	'LBL_OVERALL_DISCOUNT' => 'Diskon Keseluruhan',
	'LBL_CHARGES' => 'Biaya',
	'LBL_CHARGES_TOTAL' => 'Total Biaya',
	'LBL_TAXES_ON_CHARGES' => 'Pajak atas Biaya',
	'LBL_DEDUCTED_TAXES' => 'Pajak yang Dipotong',
	'LBL_DEDUCTED_TAXES_TOTAL' => 'Total Pajak yang Dipotong',
	'LBL_DEFAULT' => 'Default',
	'LBL_ITEM' => 'Barang',
	'LBL_ADD_DASHBOARD' =>'Tambah dasbor',

	//DetailView Actions
	'LBL_CREATE' => 'Buat',
	'LBL_GENERATE' => 'Buat',
	'LBL_DUPLICATE' => 'Duplikat',
	'Add Note' => 'Tambah Dokumen',

	//Dashboard String
	'LBL_ADD_WIDGET' => 'Tambah Widget',
	'LBL_COMMENTS' => 'Komentar',
	'LBL_REFRESH' => 'Segarkan',
	'LBL_CLOSE' => 'Tutup',
	'LBL_ALL' => 'Semua',
	'LBL_UPDATED' => 'perbarui',
	'LBL_VIA_TASK' => 'melalui tugas',
	'LBL_form' => 'dari',
	'LBL_FROM' => 'Dari',
	'LBL_TO' => 'Ke',
	'LBL_to' => 'kepada',
	'LBL_ON' => 'aktif',
	'LBL_OF' => 'dari',
	'LBL_BY' => 'oleh',
	'LBL_ADDED' => 'tambahkan',
	'LBL_FOR' => 'untuk',
	'LBL_CREATED' => 'dibuat',
	'LBL_DELETED' => 'hapus',
	'LBL_RESTORED' => 'dipulihkan',
	'LBL_COMMENTED' => 'dikomentari',
	'LBL_REMOVED' => 'dihapus',
	'LBL_REMOVE' => 'Hapus',
	'LBL_AT' => 'di',
	'LBL_MINE' => 'Milikku',
	'LBL_ME' => 'Aku',
	'History' => 'Riwayat',
	'Upcoming Tasks' => 'Tugas Mendatang',
	'LBL_YEAR' => 'tahun',
	'LBL_YEARS' => 'tahun',
	'LBL_MONTH' => 'bulan',
	'LBL_MONTHS' => 'bulan',
	'LBL_DAY' => 'hari',
	'LBL_DAYS' => 'hari',
	'LBL_DAY(S)' => 'hari',
	'LBL_HOUR' => 'jam',
	'LBL_HOURS' => 'jam',
	'LBL_HOUR(S)' => 'jam',
	'LBL_MINUTE' => 'menit',
	'LBL_MINUTES' => 'menit',
	'LBL_SECOND' => 'detik',
	'LBL_SECONDS' => 'detik',
	'LBL_JUSTNOW' => 'baru saja',
	'LBL_CUSTOM_INFORMATION' => 'Informasi Khusus',
	'LBL_NO_RECENT_UPDATES' => 'Tidak ada pembaruan terkini',
	'LBL_NO_DATA' => 'Tidak ada Data',
	'LBL_PERMISSION_DENIED' => 'Izin ditolak',
	'LBL_HANDLER_NOT_FOUND' => 'Penangan tidak ditemukan',
	'LBL_FILTER' => 'Daftar',
	'LBL_DUE' => 'jatuh tempo dalam',
	'LBL_DAYS' => 'hari',
	'LBL_COMPLETED' => 'selesai',
	'LBL_AGO' => 'lalu',
	'LBL_CHANGED' => 'berubah',
	'SINGLE_Users' => 'Pengguna',
	'LBL_MATCHED_THIS_CRITERIA'=> 'cocok dengan kriteria ini',
	'LBL_NO_SCHEDULED_ACTIVITIES' => 'Tidak ada aktivitas terjadwal',
	'LBL_NO_OVERDUE_ACTIVITIES' => 'Tidak ada aktivitas yang terlambat',
	'LBL_NO_UPDATES_OR_COMMENTS' => 'Tidak ada pembaruan atau komentar',
	'LBL_MINI_LIST' => 'Daftar Mini',
	'LBL_NOTEPAD' => 'Buku Catatan',
	'LBL_NOTEPAD_NAME' => 'Nama Buku Catatan',
	'LBL_NOTEPAD_CONTENT' => 'Isi Buku Catatan',
	'LBL_LAST_SAVED_ON' => 'Terakhir disimpan pada',
	'Mini List' => 'Daftar Mini',
	'Notebook' => 'Buku Catatan',
	'LBL_RESULT_FOR_THE_TAG' => 'Hasil untuk tag',
	'LBL_ALL_USERS' => 'Semua Pengguna',
	'LBL_BOTH' => 'Keduanya',
	'LBL_SHOW' => 'Tampilkan',
	'LBL_MY' => 'Saya',
	'LBL_SELECT_DATE_RANGE' => 'Pilih Rentang Tanggal',

	// Basic Strings- custom view
	'LBL_VIEW_NAME' => 'Nama Daftar',
	'LBL_CREATE_VIEW' => 'Membuat tampilan baru',
	'LBL_BASIC_DETAILS' => 'Detail dasar',
	'LBL_CHOOSE_COLUMNS' => 'Pilih kolom dan urutan',
	'LBL_MAX_NUMBER_FILTER_COLUMNS' => 'Maksimal 15',
	'LBL_FILTER_ON_DATE' => 'Tanggal daftar',
	'LBL_CHOOSE_FILTER_CONDITIONS' => 'Pilih kondisi Daftar',
	'LBL_ADD_CONDITION' => 'Tambahkan Kondisi',
	'LBL_SET_AS_DEFAULT' => 'Tetapkan sebagai Default',
	'LBL_LIST_IN_METRICS' => 'Daftar dalam Metrik',
	'LBL_SET_AS_PUBLIC' => ' Tetapkan sebagai Publik',
	'LBL_AND' => 'dan',
	'LBL_OR' => 'atau',
	'LBL_ADD_MORE_COLUMNS' => 'Klik untuk memilih kolom',
	'LBL_ADD_GROUP' => 'Tambahkan Grup',

	//DateFilter Conditions
	'LBL_CUSTOM' => 'Khusus',
	'LBL_PREVIOUS_FY' => 'Tahun Anggaran Sebelumnya',
	'LBL_CURRENT_FY' => 'Tahun Anggaran Saat Ini',
	'LBL_NEXT_FY' => 'Tahun Anggaran Berikutnya',
	'LBL_PREVIOUS_FQ' => 'Tahun Anggaran Sebelumnya',
	'LBL_CURRENT_FQ' => 'Tahun Anggaran Saat Ini',
	'LBL_NEXT_FQ' => 'Tahun Anggaran Berikutnya',
	'LBL_YESTERDAY' => 'Kemarin',
	'LBL_TODAY' => 'Hari Ini',
	'LBL_TOMORROW' => 'Besok',
	'LBL_LAST_WEEK' => 'Minggu Sebelumnya',
	'LBL_CURRENT_WEEK' => 'Minggu Saat Ini',
	'LBL_NEXT_WEEK' => 'Minggu Depan',
	'LBL_LAST_MONTH' => 'Bulan Sebelumnya',
	'LBL_CURRENT_MONTH' => 'Bulan Ini',
	'LBL_NEXT_MONTH' => 'Bulan Depan',
	'LBL_LAST_7_DAYS' => '7 Hari Terakhir',
	'LBL_LAST_14_DAYS' => '14 Hari Terakhir',
	'LBL_LAST_30_DAYS' => '30 Hari Terakhir',
	'LBL_LAST_60_DAYS' => '60 Hari Terakhir',
	'LBL_LAST_90_DAYS' => '90 Hari Terakhir',
	'LBL_LAST_120_DAYS' => '120 Hari Terakhir',
	'LBL_NEXT_30_DAYS' => '30 Hari Berikutnya',
	'LBL_NEXT_60_DAYS' => '60 Hari Mendatang',
	'LBL_NEXT_90_DAYS' => '90 Hari Mendatang',
	'LBL_NEXT_120_DAYS' => '120 Hari Mendatang',

	//advanced Filter Options
	'LBL_NONE' => 'Tidak Ada',
	'LBL_EQUALS' => 'sama dengan',
	'LBL_NOT_EQUAL_TO' => 'tidak sama dengan',
	'LBL_STARTS_WITH' => 'dimulai dengan',
	'LBL_ENDS_WITH' => 'diakhiri dengan',
	'LBL_CONTAINS' => 'berisi',
	'LBL_DOES_NOT_CONTAIN' => 'tidak berisi',
	'LBL_LESS_THAN' => 'kurang dari',
	'LBL_GREATER_THAN' => 'lebih besar dari',
	'LBL_LESS_THAN_OR_EQUAL' => 'kurang atau sama',
	'LBL_GREATER_OR_EQUAL' => 'lebih besar atau sama',
	'LBL_BEFORE' => 'sebelum',
	'LBL_AFTER' => 'sesudah',
	'LBL_BETWEEN' => 'di antara',
	'LBL_IS_EMPTY'=> 'kosong',
	'LBL_IS_NOT_EMPTY' => 'tidak kosong',
	'LBL_APPROVE' => 'Setuju',
	'LBL_HAS_CHANGED' => 'telah berubah',
	'LBL_HAS_CHANGED_TO' => 'telah berubah menjadi',
	'LBL_HAS_CHANGED_FROM' => 'telah berubah dari',
	'LBL_LESS_THAN_OR_EQUAL_TO' => 'kurang dari atau sama dengan',
	'LBL_GREATER_THAN_OR_EQUAL_TO' => 'lebih besar dari atau sama dengan',
	'LBL_IS_NOT' => 'tidak',
	'LBL_IS_ADDED' => 'ditambahkan',
	'LBL_IS_TODAY' => 'hari ini',
	'LBL_IS_TOMORROW' => 'besok',
	'LBL_IS_YESTERDAY' => 'kemarin',
	'LBL_LESS_THAN_DAYS_LATER' => 'kurang dari beberapa hari kemudian',
	'LBL_MORE_THAN_DAYS_LATER' => 'lebih dari beberapa hari kemudian',

	//Detail view summary widgets
	'LBL_OWNER' => 'Pemilik',
	'LBL_CREATED_ON' => 'Dibuat pada',
	'LBL_MODIFIED_ON' => 'Dimodifikasi pada',
	'LBL_MODIFIED' => 'Dimodifikasi',
	'LBL_COMMENTED' => 'Berkomentar',

	//calender set-reminder
	'LBL_BEFORE_EVENT' => ' Sebelum Acara',

	//Dashboard widgets
	'History' => 'Riwayat',
	'Upcoming Activities' => 'Aktivitas Mendatang',
	'Overdue Activities' => 'Aktivitas Terlambat',
	'Funnel' => 'Corong',
	'Potentials by Stage' => 'Peluang Berdasarkan Tahap',
	'Pipelined Amount' => 'Jalur Penjualan',
	'Total Revenue' => 'Total Pendapatan',
	'Top Potentials' => 'Peluang Teratas',
	'Forecast' => 'Prakiraan',
	'Leads Created' => 'Prospek yang Dibuat',
	'Leads by Status' => 'Prospek Berdasarkan Status',
	'Leads by Source' => 'Prospek Berdasarkan Sumber',
	'Leads by Industry' => 'Prospek Berdasarkan Industri',
	'Tickets by Status' => 'Tiket berdasarkan Status',
	'Open Tickets' => 'Tiket Terbuka',
	'Funnel Amount' => 'Jumlah Total berdasarkan Tahap Penjualan',
	'Key Metrics' => 'Metrik Utama',
	'Mini List' => 'Daftar Mini',
	'Tag Cloud' => 'Tag Cloud',
	'Notebook' => 'Buku Catatan',

	//Exports strings
	'LBL_EXPORT_ALL_DATA' => 'Ekspor semua data',
	'LBL_EXPORT_DATA_IN_CURRENT_PAGE' => 'Ekspor data di halaman saat ini',
	'LBL_EXPORT_SELECTED_RECORDS' => 'Ekspor Rekaman yang Dipilih',
	'LBL_EXPORT_RECORDS' => 'Ekspor Rekaman',
	'LBL_NO_RECORD_SELECTED' => 'Tidak ada rekaman yang dipilih.',
	'LBL_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Tidak dapat menghapus widget default',
	'LBL_CUSTOM_VIEW_NAME_DUPLICATES_EXIST' => 'Daftar sudah ada',
	'LBL_TYPE_AND_SEARCH' => 'Ketik dan Cari',
		'LBL_EXPORT_CURRENCY_TOOLTIP_TEXT'=>'Untuk mengekspor nilai Mata Uang dalam Item Baris, Vtiger akan menggunakan pengaturan ini untuk mengekspor sebagai mata uang ini. Nilai mata uang apa pun di luar tabel item baris akan diekspor dalam mata uang pilihan Pengguna (dipilih di \'Preferensi Saya\')',
		'LBL_EXPORT_LINEITEM_CURRENCY'=>'Pilih Mata Uang (Untuk Nilai Item Baris)',
		'LBL_EXPORT_USER_CURRENCY' =>'Mata Uang Pilihan Saya',
		'LBL_EXPORT_RECORD_CURRENCY'=>'Mata Uang Ditentukan dalam Rekaman',
	'LBL_EXPORT_FORMAT' => 'Format Ekspor',
	'LBL_EXPORT_DATA' => 'Ekspor Data',

	'LBL_CUSTOMIZE' => 'Kustomisasi',
	'LBL_ADD_MANAGE_MODULES' => 'Modul',
	'LBL_CUSTOMIZE_MAIN_MENU' => 'Menu Kiri',
	'LBL_LABELS' => 'Label',
	'LBL_WORKFLOWS' => 'Alur Kerja',
	'LBL_PICKLIST' => 'Daftar Pilihan',

	// Added Common Keys for all modules
	'Account Name' => 'Nama Organisasi',
	'Add Comment' => 'Tambahkan Komentar',
	'Adjustment' => 'Penyesuaian',
	'Annual Revenue' => 'Pendapatan Tahunan',
	'Apparel'=>'Pakaian',
	'Banking'=>'Perbankan',
	'Billing Address' => 'Alamat Penagihan',
	'Billing City' => 'Kota Penagihan',
	'Billing Code' => 'Kode Pos Penagihan',
	'Billing Country' => 'Negara Penagihan',
	'Billing Po Box' => 'Kotak Pos Penagihan',
	'Billing State' => 'Negara Bagian Penagihan',
	'Biotechnology'=>'Bioteknologi',

	//for SO PO and Quotes
	'FedEx'=>'FedEx',
	'UPS'=>'UPS',
	'USPS'=>'USPS',
	'DHL'=>'DHL',
	'BlueDart'=>'BlueDart',
	'Carrier' => 'Pengangkut',
	'Category'=>'Kategori',
	'Chemicals'=>'Bahan Kimia',
	'City' => 'Kota',

	'Cold Call'=>'Cold Call',
	'Existing Customer'=>'Pelanggan Lama',
	'Self Generated'=>'Dihasilkan Sendiri',
	'Employee'=>'Karyawan',
	'Partner'=>'Mitra',
	'Public Relations'=>'Hubungan Masyarakat',
	'Direct Mail'=>'Surat Langsung',
	'Conference'=>'Konferensi',
	'Trade Show'=>'Pameran Dagang',
	'Web Site'=>'Situs Web',
	'Word of mouth'=>'Dari mulut ke mulut',
	'Other'=>'Lainnya',

	//for leads and accounts
	'--None--'=>'--Tidak Ada--',
	'Acquired'=>'Diakuisisi',
	'Active'=>'Aktif',
	'Market Failed'=>'Pasar Gagal',
	'Project Cancelled'=>'Proyek Dibatalkan',
	'Shutdown'=>'Penutupan',
	'Apparel'=>'Pakaian',
	'Banking'=>'Perbankan',
	'Biotechnology'=>'Bioteknologi',
	'Chemicals'=>'Bahan Kimia',
	'Communications'=>'Komunikasi',
	'Construction'=>'Konstruksi',
	'Consulting'=>'Konsultasi',
	'Education'=>'Pendidikan',
	'Electronics'=>'Elektronik',
	'Energy'=>'Energi',
	'Engineering'=>'Teknik',
	'Entertainment'=>'Hiburan',
	'Environmental'=>'Lingkungan Hidup',
	'Finance'=>'Keuangan',
	'Food & Beverage'=>'Makanan & Minuman',
	'Government'=>'Pemerintah',
	'Healthcare'=>'Kesehatan',
	'Hospitality'=>'Perhotelan',
	'Insurance'=>'Asuransi',
	'Machinery'=>'Mesin',
	'Manufacturing'=>'Manufacturing',
	'Media'=>'Media',
	'Not For Profit'=>'Nirlaba',
	'Recreation'=>'Rekreasi',
	'Retail'=>'Ritel',
	'Shipping'=>'Pengiriman',
	'Technology'=>'Teknologi',
	'Telecommunications'=>'Telekomunikasi',
	'Transportation'=>'Transportasi',
	'Utilities'=>'Utilitas',

	'Contact Name' => 'Nama Kontak',
	'Conversion Rate' => 'Nilai Konversi',

	'Shipping Address' => 'Alamat Pengiriman',
	'Shipping City' => 'Kota Pengiriman',
	'Shipping State' => 'Negara Bagian Pengiriman',
	'Shipping Code' => 'Kode Pengiriman',
	'Shipping Country' => 'Negara Pengiriman',
	'Shipping Po Box' => 'Kotak Pos Pengiriman',
	'Country' => 'Negara',
	'Description' => 'Deskripsi',

	'Created'=>'Dibuat',
	'Approved'=>'Disetujui',
	'Delivered'=>'Terkirim',
	'Cancelled'=>'Dibatalkan',

	'Currency' => 'Mata Uang',
	'LBL_BASE_CURRENCY' => 'Mata Uang Default',

	'Discount Percent' => 'Persen Diskon',
	'Discount Amount' => 'Jumlah Diskon',
	'Item Discount Amount' => 'Jumlah Diskon Barang',
	'Net Price' => 'Harga Bersih', 
	'Item Discount Percent' => 'Persen Diskon Barang',

	'Due Date' => 'Tanggal Jatuh Tempo',
	'Due Date & Time' => 'Tanggal & Waktu Jatuh Tempo',
	'Email' => 'Email Utama',
	'Secondary Email' => 'Email Sekunder',
	'Other Email' => 'Email Lain',
	'Email Opt Out' => 'Berhenti Berlangganan Email',
	'Is Converted From Lead' => 'Dikonversi Dari Prospek',
	'Expected Close Date' => 'Tanggal Penutupan yang Diharapkan',
	'Fax' => 'Faks',

	'Last Name' => 'Nama Belakang',
	'First Name' => 'Nama Depan',

	'High' => 'Tinggi',
	'Low' => 'Rendah',
	'In Progress' => 'Sedang Diproses',

	'Subject' => 'Subjek',
	'Shipping Address'=>'Alamat Pengiriman',
	'Shipping Po Box'=>'Kotak Pos Pengiriman',
	'Shipping City'=>'Kota Pengiriman',
	'Shipping State'=>'Negara Bagian Pengiriman',
	'Shipping Code'=>'Kode Pos Pengiriman',
	'Shipping Country'=>'Negara Pengiriman',
	'Terms & Conditions' => 'Syarat & Ketentuan',
	'Item Name' => 'Nama Barang',
	'Quantity' => 'Kuantitas',
	'List Price' => 'Harga Jual',
	'Image' => 'Gambar',
	'Purchase Cost' => 'Harga Pembelian',
	'Margin' => 'Margin',
	'Item Comment' => 'Komentar Barang',
	'Tax1' => 'Pajak1',
	'Tax2' => 'Pajak2',
	'Tax3' => 'Pajak3',
	'Excise Duty' => 'Bea Cukai',
	'Total' => 'Total',
	'Sub Total' => 'Subtotal',
	'Tax Type' => 'Jenis Pajak',
	'S&H Amount' => 'Jumlah S&H',
	'Status' => 'Status',
	'Vendor Name'=>'Nama Vendor',

	'LBL_ADDRESS_INFORMATION' => 'Detail Alamat',
	'LBL_DESCRIPTION_INFORMATION' => 'Detail Deskripsi',
	'LBL_TERMS_INFORMATION' => 'Syarat & Ketentuan',
	'LBL_PRICING_INFORMATION' => 'Informasi Harga',
	'LBL_RELATED_PRODUCTS' => 'Detail Produk',
	'LBL_REMINDER_INFORMATION' => 'Detail Pengingat',

	'LBL_FOLDER_SAVED' => 'Folder tersimpan',
	'LBL_FOLDER_EXISTS' => 'Folder sudah ada',
	'LBL_FOLDER_DELETED' => 'Folder dihapus',
	'LBL_EDIT_FOLDER' => 'Edit Folder',

	'Lead Source' => 'Sumber Prospek',
	'Mobile' => 'Ponsel',

	'Notify Owner' => 'Notif Pemilik',
	'Other Phone' => 'Phone Sekunder',
	'Phone' => 'Phone Primer',

	'State' => 'State',
	'Po Box' => 'PO Box',
	'Postal Code' => 'Kode Pos',

	'Potential Name' => 'Opportunity Name',
	'Priority'=>'Prioritas',

	'Product Name' => 'Product Name',
	'Rating' => 'Rating',

	'Related To'=>'Related To',
	'Type' => 'Jenis',

	'Reviewed'=>'Ditinjau',
	'Salutation' => 'Salam',
	'Street' => 'Jalan',
	'Support Start Date' => 'Tanggal Mulai Dukungan',
	'Support Expiry Date' => 'Tanggal Kedaluwarsa Dukungan',
	'Sales Start Date'=>'Tanggal Mulai Penjualan',
	'Sales End Date'=>'Tanggal Akhir Penjualan',

	//Dashboard list of widgets translation
	'Open Ticktes' => 'Buka Tiket',
	'LBL_SELECT_STATUS' => 'Pilih Status',
	'LBL_BLANK' => '-Kosong-',

	//PageTitle translations
	'LBL_VTIGER_CRM_HONEST_OPEN_SOURCE' => 'vtiger CRM On Demand',

	//Translations used in inventory modules for sopy address
	'SINGLE_Accounts' => 'Organisasi',
	'SINGLE_Contacts' => 'Kontak',

	//Weekdays in 3 letters translations
	'LBL_Sun' => 'Min',
	'LBL_Mon' => 'Sen',
	'LBL_Tue' => 'Sel',
	'LBL_Wed' => 'Rab',
	'LBL_Thu' => 'Kam',
	'LBL_Fri' => 'Jum',
	'LBL_Sat' => 'Sab',

	//Months in 3 letters translations
	'LBL_Jan' => 'Jan',
	'LBL_Feb' => 'Feb',
	'LBL_Mar' => 'Mar',
	'LBL_Apr' => 'Apr',
	'LBL_May' => 'Mei',
	'LBL_Jun' => 'Jun',
	'LBL_Jul' => 'Jul',
	'LBL_Aug' => 'Agu',
	'LBL_Sep' => 'Sep',
	'LBL_Oct' => 'Okt',
	'LBL_Nov' => 'Nov',
	'LBL_Dec' => 'Des',

	'LBL_CALENDAR_SETTINGS' => 'Pengaturan Kalender',
	'Reminder Interval' => 'Popup Interval Pengingat',

	//Translations used in inventory modules for address
	'SINGLE_Accounts' => 'Organisasi',
	'SINGLE_Contacts' => 'Kontak',
	'HelpDesk' => 'Tiket',
	'LBL_TAG_CLOUD' => 'Tag Cloud',

	'LBL_NO_RECORDS' => 'Tidak Ada Rekaman',
	'LBL_NO_RELATED' => 'Tidak Terkait',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE' => 'Hanya 100 pertama Hasil semua modul ditampilkan di bawah ini. Untuk hasil spesifik modul, silakan pilih modul dan cari.',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE_FOR_MODULE' => 'Hanya 100 hasil pertama yang ditampilkan di bawah ini. Silakan lakukan Pencarian Lanjutan jika Anda tidak puas dengan hasilnya',

	// used in reports detail view
	'LBL_ACTION' => 'Tindakan',
	'LBL_NOTE' => 'Catatan',
	'LBL_SELECT_OPTION' => 'Pilih Opsi',

	//Module Manager
	'LBL_TOOLTIP' => 'Manajemen Tooltip',
	'LBL_MODULE_SEQUENCE_NUMBERING' => 'Penomoran %s',
	'LBL_CUSTOM_FIELD_MAPPING' => 'Pemetaan Kolom Kustom',
	'LBL_WEBFORMS' => 'Formulir Web',

	//Compose Email Strings
	'SINGLE_Emails' => 'Email',
	'Emails' => 'Email',
	'LBL_SELECT_EMAIL_IDS' => 'Pilih Alamat Email',
	'LBL_SUBJECT' => 'Subjek',
	'LBL_ATTACHMENT' => 'Lampiran',
	'LBL_BROWSE_CRM' => 'Telusuri CRM',
	'LBL_SEND' => 'Kirim',
	'LBL_SAVE_AS_DRAFT' => 'Simpan sebagai Draf',
	'LBL_GO_TO_PREVIEW' => 'Buka Pratinjau',
	'LBL_SELECT_EMAIL_TEMPLATE' => 'Pilih Templat Email',
	'LBL_COMPOSE_EMAIL' => 'Tulis Email',
	'LBL_CC' => 'Cc',
	'LBL_BCC' => 'Bcc',
	'LBL_ADD_CC' => 'Tambahkan Cc',
	'LBL_ADD_BCC' => 'Tambahkan Bcc',
	'LBL_MAX_UPLOAD_SIZE' => 'Ukuran unggahan maksimum adalah',
	'LBL_EXCEEDED' => 'Terlampaui',
	'LBL_OPERATION_NOT_PERMITTED' => 'Operasi tidak diizinkan',
	'LBL_MERGE' => 'Gabungkan',
	'LBL_FIND_DUPLICATES' => 'Temukan Duplikat',
	'LBL_MERGING_CRITERIA_SELECTION' => 'Pemilihan Kriteria Penggabungan',
	'LBL_AVAILABLE_FIELDS' => 'Kolom yang Tersedia',
	'LBL_MERGE_RECORDS_DESCRIPTION' => 'Rekaman utama akan disimpan setelah penggabungan. Anda dapat memilih kolom untuk menyimpan nilainya.
										Rekaman lainnya akan dihapus, tetapi informasi terkait akan digabungkan.',
	'LBL_MERGE_RECORDS_IN' => 'Gabungkan Rekaman',
	'LBL_FIELDS' => 'Kolom',
	'LBL_RECORD' => 'Rekaman',
	'LBL_NO_DUPLICATED_FOUND' => 'Tidak ditemukan duplikat',
	'LBL_MERGE_SELECT' => 'Gabungkan Pilihan',

	//sbproducts translation
	'LBL_BACK_TO_PRODUCTS' => 'Kembali ke produk',

	//Translations used for Export to Pdf
	'Valid Date' => 'Tanggal Valid',
	'Phone: ' => 'Telepon: ',
	'Issued Date' => 'Tanggal Terbit',
	'Shipping & Handling Charges' => 'Biaya Pengiriman & Penanganan',
	'Shipping & Handling Tax:' => 'Pajak Pengiriman & Penanganan:',
	'Discount'=>'Diskon',
	'Net Total' => 'Total Bersih',
	'Product Code'=>'Kode Produk',
	'Customer Name'=>'Nama Pelanggan',
	'Price'=>'Harga',
	'Tax:' => 'Pajak:',
	'Contact Name' => 'Nama Kontak',
	'Grand Total:' => 'Total Keseluruhan:',
	'Fax: ' => 'Faks: ',
	'Website: ' => 'Situs Web: ',
	'Tax' => 'Pajak',
	'LBL_ALPHABETS' => 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z',

	//Realted tab strings
	'Service Contracts' => 'Kontrak Layanan',
	'Projects' => 'Proyek',
	'Sales Order' => 'Pesanan Penjualan',
	'Purchase Order' => 'Pesanan Pembelian',
	'Payments' => 'Pembayaran',
	'List and Campaigns' => 'Daftar dan Kampanye',
	'Project Tasks' => 'Tugas Proyek',
	'Project Milestones' => 'Milestone Proyek',

	'Labels Editor' => 'Editor Label',
	'LBL_IGNORE_EMPTY_VALUES' =>'Abaikan nilai kosong',

	//Related tabs of Products
	'Product Bundles' => 'Paket Produk',
	'Parent Product' => 'Produk Induk',
	'LBL_PRODUCT_BUNDLE' => 'Paket Produk',
	'LBL_EDIT_QUANTITY' => 'Edit Kuantitas',
	'LBL_ADD_TO_PRODUCTS' => 'Tambah Produk',

	'LBL_MANAGE_USERS' => 'Kelola Pengguna',
	'LBL_TRANSFER_OWNERSHIP' => 'Transfer Kepemilikan',
	'LBL_SELECT_RELATED_MODULES' => 'Pilih Modul Terkait',
	'LBL_ASSIGNED_TO' => 'Ditugaskan Kepada',
	//Comments Field Labels for Workflow
	'Comment' => 'Komentar',
	'Last Comment' => 'Komentar Terakhir',
	'Last 5 Comments' => '5 Komentar Terakhir',
	'All Comments' => 'Semua Komentar',

	//Feedback on removing old version
	'LBL_OLD_VERSION_REMOVED_SOON' => 'Catatan Penting tentang Tampilan Lama',
	'LBL_FEEDBACK_ON_REMOVING_OLD_VERSION' => 'Dengan senang hati kami sampaikan bahwa tampilan lama akan tersedia hingga Februari 2014. Kami baru saja menambahkan fitur-fitur berikut ke tampilan baru<br><br>1. Laporan Pivot<br>2. Chart Kustom<br>3. Pencarian Cepat dalam Daftar<br><br>Jika Anda memiliki saran tentang tampilan baru, silakan bagikan dengan kami di bawah ini.',
	'LBL_FEEDBACK_PLACEHOLDER' => 'Bagikan saran Anda di sini..',
	'LBL_SUBMIT_FEEDBACK' => 'Kirim masukan',
	'LBL_DONT_SHOW_AGAIN' => 'Jangan tampilkan ini lagi',
	'LBL_CONTINUE_TO_OLD_LOOK' => 'Lanjutkan ke Tampilan Lama',
	'LBL_LEFT_PANEL_SHOW_HIDE' => 'Tampilkan/Sembunyikan Panel Kiri',

	//Products Popup View
	'NOT_A_BUNDLE' => 'Bukan bundel',
	'LBL_SUB_PRODUCTS' => 'Sub Produk',
	'LBL_MARK_AS_HELD' => 'Tandai Sebagai Ditahan',
	'LBL_MARK_AS_COMPLETED' => 'Tandai Sebagai Selesai',
	'LBL_SMS_MAX_CHARACTERS_ALLOWED' => 'Maksimal 160 karakter diperbolehkan untuk pesan teks',
	'LBL_HIDE_COMPLETED_EVENTS' => 'Sembunyikan Acara Kalender yang Telah Selesai',
	'LBL_SETUP_WEBFORMS' => 'Siapkan Formulir Web',
	'LBL_SPECIAL_OPTIONS' => 'Opsi Khusus',
	'LBL_PARENT_OWNER' => 'Pemilik Rekaman Induk',
	'LBL_PASSWORD_LINK_EXPIRED_OR_INVALID_PASSWORD' => 'Tautan kata sandi telah kedaluwarsa atau kata sandi yang Anda masukkan tidak valid',

	// Recurring Invoice
	'Half-Yearly' => 'Setengah Tahunan',
	'LBL_FULLSCREEN' => 'Layar Penuh',
	'LBL_SETUP_WEBFORMS' => 'Siapkan Formulir Web',
	'LBL_MODULE_DISABLED' => ' Modul dinonaktifkan',
	'Organization Name' => 'Nama Organisasi',
	'LBL_SOCIAL_TWITTER_WIDGET' => 'Aktivitas Twitter',
	'LBL_WEEK' => 'Minggu',
	//Convert Lead and Potential
	'CANNOT_CONVERT' => 'Tidak Dapat Mengonversi',
	'LBL_CONVERT_ERROR_TITLE' => 'Modul Dinonaktifkan',
	'LBL_FOLLOWING_ARE_POSSIBLE_REASONS' => 'Kemungkinan penyebabnya antara lain:',
	'LBL_MANDATORY_FIELDS_ARE_EMPTY' => 'Kolom wajib kosong',

	// SMSNotifier Phone Format Warning
	'LBL_PHONE_FORMAT_WARNING' => 'Pastikan nomor telepon dalam format internasional E.164',
	'LBL_PHONEFORMAT_WARNING_CONTENT' => 'Format nomor E.164 dapat memiliki maksimal lima belas digit dan biasanya ditulis sebagai berikut: [+][negara Kode [nomor pelanggan termasuk kode area]
										 Misalnya, untuk mengonversi nomor telepon AS (415 599 2671) ke format E.164, Anda perlu menambahkan awalan \'+\' dan kode negara (yaitu 1) di depan nomor tersebut (+1 415 599 2671). Di Inggris dan banyak negara lain di dunia, panggilan lokal memerlukan penambahan angka 0 di depan nomor pelanggan. Namun, untuk menggunakan format E.164, angka 0 ini harus dihilangkan. Nomor seperti 020 7183 8750 di Inggris akan diformat sebagai +44 20 7183 8750.',
	'LBL_WARNING' => 'Peringatan',
	'LBL_ORIGIN' => 'Asal',
	'SENT' => 'Terkirim',
	'RECEIVED' => 'Diterima',
	'QUEUED'=> 'Antri',
	'FAILED'=> 'Gagal',
	'SAVED' => 'Draf',
	'MailManager' => 'Manajer Email',
	'MAILSCANNER' => 'Konverter Email',
	'LBL_SENDER_NAME' => 'Nama Pengirim',
	'SMSNotifier'=>'Pemberitahu SMS',

	'Mobile Call' => 'Panggilan Seluler',
	'LBL_NO_MORE_RESULTS' => 'Tidak ada hasil lagi!',
	'Related To' => 'Related To',

	// Date Conditions
	'LBL_LESS_THAN_DAYS_AGO' => 'Kurang dari hari yang lalu',
	'LBL_MORE_THAN_DAYS_AGO' => 'Lebih dari hari yang lalu',
	'LBL_IN_LESS_THAN' => 'Kurang dari',
	'LBL_IN_MORE_THAN' => 'Lebih dari',
	'LBL_DAYS_AGO' => 'Beberapa hari yang lalu',
	'LBL_DAYS_LATER' => 'Beberapa hari kemudian',
	'LBL_LESS_THAN_HOURS_BEFORE' => 'Kurang dari beberapa jam sebelumnya',
	'LBL_LESS_THAN_HOURS_LATER' => 'Kurang dari beberapa jam kemudian',
	'LBL_MORE_THAN_HOURS_BEFORE' => 'Lebih dari beberapa jam sebelumnya',
	'LBL_MORE_THAN_HOURS_LATER' => 'Lebih dari Beberapa Jam Kemudian',
	'LBL_INTERNAL_COMMENT' => 'Komentar Internal',
	'LBL_NOTE_EXISTING_ATTACHMENTS_WILL_BE_REPLACED' => 'Catatan: Lampiran (gambar/berkas) yang ada akan diganti',

	//common standard fields
	'Created By' => 'Dibuat Oleh',
	'LBL_SEND_PDF_FOR_SIGNING' => 'Kirim PDF untuk ditandatangani',
	'LBL_CLICK_TO_EDIT' => 'Klik untuk mengedit',
	'LBL_SIGNATURE_BLOCK' => 'Tanda Tangan',
	'LBL_INCLUDE_SIGNATURE_INFO' => 'Tanda tangan yang diatur di Preferensi Saya akan ditambahkan di bagian bawah email',
	'LBL_INCLUDE_SIGNATURE' => 'Sertakan Tanda Tangan',

	// module builder created module first block label 
	'LBL_BASIC_INFORMATION' => 'Informasi Dasar',
	'LBL_CLICK_HERE'=>'klik di sini',

	//Recipient preferences labels
	'LBL_SELCT_EMAIL_RECIPIENTS' => 'Pilih Penerima Email',
	'LBL_REMEMBER_MY_PREF' => 'Ingat preferensi saya',
	'LBL_RECIPIENT_PREFS'=>'Preferensi Penerima',
	'LBL_EMAIL_RECIPIENT_PREFS'=>'Preferensi Penerima Email',
	'LBL_ERROR_SAVING_PREF' => 'Terjadi kesalahan saat menyimpan preferensi. Silakan coba lagi nanti!',
	'LBL_NO_PREF_GIVEN' => 'Tidak ada preferensi yang diberikan!',
	'LBL_PLEASE_ADD_EMAIL_FIELDS' => 'Silakan tambahkan kolom email dan coba lagi',
	'LBL_RECIPIENT_SAVE_MESSAGE'=>'Penyimpanan berhasil. Preferensi ini akan diperlakukan sebagai alamat email penerima ketika Anda mengirim email dari modul ini.',
	'LBL_PREF_RESET_MESSAGE' => 'Preferensi email penerima Anda telah diatur ulang!',

	'LBL_COMPANY_DETAILS' => 'Detail Perusahaan',
	'COMPANY_LOGO_HELP_TEXT' => 'Silakan unggah logo perusahaan Anda yang menarik. <br>Selain menampilkan logo perusahaan Anda di CRM,<br>
									nama dan detail alamat perusahaan Anda digunakan dalam <br>Kampanye Email (diperlukan untuk memenuhi peraturan span)<br>
									dan dalam Tanda Kutip.',
	'COMPANY_LOGO_HELP_TEXT_2' =>"Anda dapat mengedit detail perusahaan nanti dari <br>
									'Pengaturan CRM > Template > Halaman Detail Perusahaan'",
	'LBL_CHOOSE_PREFERENCES' => 'Pilih Preferensi Anda',
	'PREFERENCES_HELP_TEXT' => 'Mata Uang Dasar - Pilihmata uang utama. Jika Anda menggunakan beberapa<br> 
								mata uang, semua nilai akan dikonversi ke mata uang dasar dan disimpan,<br>
								menggunakan nilai tukar yang dikonfigurasi di CRM.',
	'PREFERENCES_HELP_TEXT_2' => 'Preferensi pribadi dapat dikonfigurasi oleh setiap pengguna di tim Anda.<br>
									Ini termasuk Zona Waktu, Bahasa, Format Tanggal, Format Angka.<br>
									Referensi Format Angka digunakan untuk Mata Uang dan <br>
									bidang angka lainnya di CRM<br>
									Anda dapat mengedit preferensi Anda nanti dari \'Nama Pengguna > Preferensi Saya\'',
	'LBL_CANNOT_BE_CHANGED_LATER' => 'Tidak dapat diubah nanti',
	'IMPORT_CONTACTS_GOOGLE_HELP_TEXT' => 'Kami dapat mengambil kontak dari Google dan <br> Anda juga dapat mengaktifkan sinkronisasi dua arah agar<br>
									kontak Vtiger dan kontak Google (dalam grup yang dipilih) tetap diperbarui.<br>
									Klik tombol untuk mengotorisasi dan mendapatkan Kontak dari Google.',
	'IMPORT_CONTACTS_CSV_HELP_TEXT' => 'Anda dapat mengimpor Kontak dari berkas CSV.',
	'IMPORT_CONTACTS_CSV_HELP_TEXT2' => 'Untuk mengimpor Peluang, Prospek, Tiket, silakan cari tombol Tindakan > Impor pada salah satu
										 tampilan daftar.',
	'LBL_DOEST_FIRST_ROW_HEADER' => 'Apakah baris pertama dalam berkas Anda berisi tajuk kolom?',
	'LBL_SELECT_CSV_FILE' => 'Pilih berkas CSV',
	'LBL_START_IMPORTING' => 'Mulai Mengimpor',
	'LBL_PRIMARY' => 'Utama',
	'LBL_GOOGLE_SYNC_INTIATED_MSG' => 'Impor Anda dijadwalkan, Kontak Anda akan segera diimpor.<br> Melanjutkan ke langkah Berikutnya tidak akan menghentikan impor.',
	'LBL_IMPORT_SYNC_INTIATED_MSG' => 'Impor Anda sedang berlangsung. Anda akan menerima email saat impor selesai.<br> Melanjutkan ke langkah Berikutnya tidak akan menghentikan impor.',
	'LBL_TELL_US_ABOUT_YOU' => 'Bantu kami dengan memberi tahu kami tentang Perusahaan Anda',
	'TELL_US_ABOUT_YOU_HELP_TEXT' => 'Kami terus melakukan peningkatan pada CRM, dan <br>
									 mengenali pengguna kami dengan lebih baik akan membantu kami memprioritaskan peningkatan.',
	'TELL_US_ABOUT_YOU_HELP_TEXT_2' => 'Data yang Anda kirimkan di sini tidak akan diungkapkan kepada siapa pun <Br>
										di luar Vtiger.',
	'LBL_INVALID_IMAGE' => 'Gambar Tidak Valid',
	'LBL_IMPORT_CONTACTS' => 'Impor Kontak',
	'LBL_FROM_GOOGLE' => 'Dari Google',
	'LBL_FROM_CSV' => 'Dari Berkas CSV',
	'LBL_NEXT' => 'Berikutnya',
	'LBL_FINISH' => 'Selesai',
	'LBL_GET_CONTACTS_FROM_GOOGLE' => 'Dapatkan Kontak dari Google',
	'LBL_PHONE_NUMBER' => 'Nomor Telepon',
	'LBL_NUMBER_OF_EMPLOYEES' => 'Jumlah Karyawan',
	'LBL_INDUSTRY' => 'Industri',
	'LBL_HELP_DESK_EMAIL_HELP_TEXT' => 'Notifikasi terkait tiket akan dikirim dari alamat email ini',
	'LBL_SOCIAL_DETAILS' => 'Tautan ke jejaring sosial untuk menemukan pelanggan baru, dan menanggapi pertanyaan',
	'LBL_SOCIAL_AUTHORIZE_HELP'=>'Hubungkan dengan akun Twitter perusahaan Anda untuk memposting pesan dan melacak interaksi',
	'LBL_SOCIAL_AUTHORIZE' => 'Hubungkan dengan Twitter',
	'LBL_SOCIAL_LINKED' => 'Vtiger Anda kini terhubung ke',
	'LBL_ENTER_KEYWORDS_HELP'=>'Vtiger akan memindai Twitter dan menemukan pesan dengan kata-kata ini',
	'LBL_ENTER_KEYWORDS' => 'Masukkan Kata Kunci',

	 // Social Module Strings
	'LBL_TWEETS' => 'Tweet',
	'LBL_FAVOURITES' => 'Favorit',
	'LBL_FOLLOWING' => 'Mengikuti',
	'LBL_FOLLOWERS' => 'Pengikut',
	'LBL_VIEW_FULL_PROFILE' => 'Lihat Profil Lengkap',
	'LBL_LOCATION' => 'Lokasi',
	'LBL_DESCRIPTION' => 'Deskripsi',
	'LBL_JOINED' => 'Bergabung',
	'LBL_SEARCH_PROFILES_IN_TWITTER' => 'Cari Profil di Twitter',
	'LBL_CHOOSE_ANOTHER_PROFILE' => 'Pilih Profil Lain',
	'LBL_ADD_TICKET' => 'Tambah Tiket',
	'LBL_ADD_OPPORTUNITY' => 'Tambah Peluang',
	'LBL_RETWEET' => 'Retweet',
	'LBL_RETWEETS' => 'Retweet',
	'LBL_UNDO_RETWEET' => 'Batalkan Retweet',
	'LBL_FAVOURITE' => 'Favorit',
	'LBL_UNDO_FAVOURITE' => 'Batalkan Favorit',
	'LBL_TWITTER_HANDLER_MSG' => 'Untuk melihat ringkasan dan riwayat profil kontak ini, tambahkan Nama Pengguna Twitter mereka atau cari profil menggunakan tautan di bawah ini.',
	'LBL_ADD_EVENT_OR_TODO' => 'Tambahkan Acara/Tugas',
	'LBL_ADD_TICKET_CONTACT' => 'Tambah Tiket + Kontak',
	'LBL_ADD_CASE_CONTACT' => 'Tambah Kasus + Kontak',
	'LBL_ADD_OPPORTUNITY_CONTACT' => 'Tambah Peluang + Kontak',
	'LBL_TWITTER_HANDLER_DETAILS' => 'Detail Nama Pengguna Twitter',
	'LBL_PRIMARY_TWITTER' => 'Nama Pengguna Twitter',
	'LBL_ADD_TWITTER_HANDLER' => 'Tambah Nama Pengguna Twitter',
	'LBL_VIEW_TICKET' => 'Lihat Tiket',
	'LBL_VIEW_CASE' => 'Lihat Kasus',
	'LBL_VIEW_OPPORTUNITY' => 'Lihat Peluang',
	'LBL_CLICK_TO_SELECT_PROFILE' => 'Klik untuk memilih profil',
	'LBL_INVALID_IMAGE' => 'Gambar Tidak Valid',
	'LBL_NEXT' => 'Berikutnya',
	'LBL_FINISH' => 'Selesai',
	// Module field to store Source of Record
	'Source' => 'Sumber',

	'LBL_DEFAULT_REPLY_TO' => 'Balasan Default untuk Email', 
	'outgoing_server_from_email' => 'Server Keluar Dari Email', 
	'hepldesk_support_email' => 'ID Email Dukungan Helpdesk', 
	'user_primary_email' => 'Email Utama Pengguna', 
	'LBL_DEFAULT_REPLY_TO_INFO' => 'Pengaturan ini hanya berlaku untuk email langsung dari CRM. Pengaturan ini tidak memengaruhi email yang dikirim dari alur kerja, kampanye email, dll.', 
	'search_in_all_fields'=>'Cari di Semua Kolom',
	'search_in_name_field'=>'Cari di kolom Nama',
	'LBL_LOOKUP_SEARCH_MODE_INFO'=>'Contoh: Dalam formulir pembuatan Kontak, ketika Anda memasukkan teks di kotak nama organisasi, pengaturan ini akan mengontrol kolom mana di Organisasi yang akan dicari',

	'VAT' => 'PPN',
	'Sales' => 'Penjualan',
	'Service' => 'Layanan',
	'Pre Tax Total' => 'Total Sebelum Pajak',
	'Received' => 'Diterima',
	'Balance' => 'Saldo',
	'S&H Amount' => 'Biaya',
	'S&H Percent' => 'Pajak Atas Biaya',
	'Tax Region' => 'Wilayah Pajak',

	//Singular Modulenames
	'SINGLE_Potentials' => 'Peluang',
	'SINGLE_HelpDesk' => 'Tiket',
	'SINGLE_Accounts' => 'Organisasi',
	'SINGLE_Contacts' => 'Kontak',
	'SINGLE_Project' => 'Proyek',
	'LBL_ROLLUP_COMMENTS_INFO' => "Jika Roll up diatur ke 'Aktif', komentar pada rekaman terkait akan ditampilkan. 
								 Misalnya, jika Anda melihat komentar pada rekaman Organisasi, komentar yang ditambahkan ke Kontak, Peluang, Tiket, dll. terkait juga akan ditampilkan.",
	'LBL_ROLLUP_COMMENTS' => "Komentar Rollup",

	//others
	'Engagement Score' => 'Skor Keterlibatan',
	'group' => 'Grup',
	'individual' => 'Individu',
	'LBL_VIEW_FILE'=>'Lihat berkas',
	'LBL_DOWNLOAD_FILE' => 'Unduh berkas',
	'LBL_PREVIEW_NOT_AVAILABLE' => 'Pratinjau Tidak Tersedia',
	'LBL_PREVIEW_SUPPORTED_FILES' => '<b><strong>Jenis Berkas yang Didukung: </strong></b><br><br><b>Berkas PDF</b><br><b>Berkas Teks - </b>txt, csv, ics<br><b>Berkas Dokumen Terbuka - </b>membuka dokumen teks (odt), membuka dokumen spreadsheet (ods), dan membuka presentasi dokumen (odp)<br><b>Berkas Multimedia - </b>berkas gambar, audio & video<br>',
	'Mailing Address' => 'Alamat Surat',
	'Other Address' => 'Alamat Lain',
	'LBL_PREVIOUS' => 'Sebelumnya',
	'LBL_NEXT' => 'Berikutnya',
	'Workflows' => 'Alur Kerja',
	'Primary Twitter' => 'Nama Pengguna Twitter',

	/* Vtiger7 Language Strings */
	'LBL_CLICK_HERE_TO_SELECT_ALL_RECORDS'=>'Pilih semua data di halaman ini',
	'LBL_CLICK_HERE_TO_MANAGE_LIST_COLUMNS'=>'Klik di sini untuk mengelola kolom Daftar',
	'LBL_SHOW_MORE' =>'Tampilkan lebih banyak',
	'LBL_DISPLAYING_RESULTS' => 'Menampilkan Hasil',
	'LBL_ADD_STAR' => 'Tambahkan Bintang',
	'LBL_REMOVE_STAR' => 'Hapus Bintang',
	'LBL_UPDATE_LIST' => 'Perbarui Daftar',
	'LBL_SHARE_THIS_LIST' => 'Bagikan daftar ini',
	'LBL_ADD_USERS_ROLES' => 'Tambahkan pengguna dan peran',
	'LBL_LISTS' => 'Daftar',
	'LBL_SEARCH_FOR_LIST' => 'Cari Daftar',
	'LBL_MY_LIST' => 'Daftar Saya',
	'LBL_SHARED_LIST' => 'Daftar Bersama',
	'LBL_MERGE_SELECTED_RECORDS' => 'Gabungkan data yang dipilih',
	'LBL_MATCH_CRITERIA' => 'Kriteria Pencarian Ganda',
	'LBL_MATCH_FIELDS' => 'Cocokkan Kolom',
	'LBL_EDIT_CUSTOM'=>'Edit Daftar',
	'LBL_SHOW_MAP'=>'Tampilkan Peta',
	'LBL_ADD_TAB'=>'Tambah Tab',
	'LBL_TAB_NAME'=>'Nama Dasbor',
	'LBL_SHARED_TAGS_ACCESS'=>'Tag bersama dapat diakses oleh semua pengguna di Vtiger',
	'LBL_GOTO_TAGS'=>'Buka Pengaturan > Preferensi Saya > Tag Saya untuk Mengedit atau Menghapus tag pribadi Anda',
	'LBL_UNLINK'=>'Batalkan Tautan',
	'LBL_SWITCH_TO_OLD'=>'Beralih ke versi lama',
	'LBL_SLA_INFORMATION' => 'Informasi SLA',

	//configure columns
	'LBL_UPDATE_LIST' => 'Perbarui Daftar',
	'LBL_CONFIG_COLUMNS' => 'Konfigurasi Kolom',
	'LBL_SELECTED_FIELDS' => 'Kolom yang Dipilih',
	'LBL_AVAILABLE_FIELDS' => 'Kolom yang Tersedia',
	'LBL_SEARCH_FIELDS' => 'Cari Kolom',

	// Extensions
	'ExtensionStore' =>'Penyimpanan Ekstensi',
	'LBL_EXTENSIONS' => 'Ekstensi',
	'LBL_SYNC_LOG' => 'Log Sinkronisasi',
	'LBL_SYNC_SETTINGS' => 'Pengaturan Sinkronisasi',
	'LBL_SYNC_NOW' => 'Sinkronkan Sekarang',
	'LBL_DATE' => 'Tanggal',
	'LBL_TIME' => 'Waktu',
	'LBL_SKIPPED' => 'Dilewati',
	'vt_create' => 'Rekaman Dibuat di Vtiger',
	'vt_update' => 'Rekaman Diperbarui di Vtiger',
	'vt_delete' => 'Rekaman Dihapus di Vtiger',
	'vt_skip' => 'Rekaman dilewati di Vtiger',
	'app_create' => 'Rekaman Dibuat di %s',
	'app_update' => 'Rekaman Diperbarui di %s',
	'app_delete' => 'Rekaman Dihapus di %s',
	'app_skip' => 'Rekaman dilewati di %s',
	'LBL_DOWNLOAD_AS_CSV' => 'Unduh Sebagai CSV',
	'LBL_SOURCE_MODULE' => 'Modul Sumber',
	'LBL_RECORD_NAME' => 'Nama Rekaman',
	'LBL_REASON' => 'Alasan',
	'LBL_SELECT_MODULES_TO_SYNC' => 'Pilih modul yang akan disinkronkan',
	'LBL_DATA' => 'Data',
	'LBL_ENABLE_SYNC' => 'Aktifkan Sinkronisasi',
	'LBL_FIELD_MAPPING' => 'Pemetaan Lapangan',
	'LBL_SYNC_DIRECTION' => 'Arah Sinkronisasi',
	'LBL_SYNC_BOTH_WAYS' => 'Sinkronkan Dua Arah',
	'LBL_SAVE_SETTINGS' => 'Simpan Pengaturan',
	'LBL_CONFIGURE' => 'Konfigurasi',
	'LBL_VIEW' => 'Lihat',
	'LBL_CHANGE_USER' => 'Ubah Pengguna',

	'LBL_CREATE_LIST' => 'Buat Daftar Baru',
	'sent' => 'Terkirim',
	'accepted' => 'Diterima',
	'SINGLE_Users' => 'Pengguna',
	'LBL_RECENT_COMMENTS' => 'Komentar Terbaru',
	'LBL_ENGAGEMENT_HISTORY' => 'Riwayat Keterlibatan',
	'LBL_NO_ENGAGEMENTS_FOUND' => 'Tidak Ada Titik Kontak Terkait',
	'LBL_MARKETING' => 'MARKETING',
	'LBL_SALES' => 'PENJUALAN',
	'LBL_PROJECT' => 'PROYEK',
	'LBL_TOOLS' => 'ALAT',
	'LBL_TAGS' => 'Tag',
	'LBL_SHARE_TAGS' => 'Tag Publik',
	'LBL_SHARE_TAG' => 'Tag Bersama',
	'private' => 'pribadi',
	'Tags' => 'Tag',
	'public' => 'dibagi',
	'Private/Shared' => 'Pribadi/Dibagi',
	'LBL_TAG_FOR' => 'Tag Untuk %s',
	'LBL_CURRENT_TAGS' => 'Tag Saat Ini',
	'LBL_CREATE_NEW_TAG'=> 'BuatTag Baru',
	'LBL_ADD_TAG' => 'Tambah Tag',
	'LBL_REMOVE_TAG' => 'Hapus Tag',
	'LBL_TAG_SEPARATOR_DESC' => 'Gunakan koma untuk memisahkan beberapa tag',
	'LBL_ENTER_TAG_NAME'=> 'Masukkan nama tag',

	'LBL_SELECT_COLOR' => 'Pilih Warna',
	'LBL_NO_TAG_EXISTS' => 'Tidak Ada Tag',
	'LBL_ADD_NEW_TAG' => 'Tambah Tag',
	'LBL_SELECT_EXISTING_TAG' => 'Ketik di sini untuk memilih tag yang ada',
	'LBL_CREATE_NEW_TAG' => 'Buat tag baru',
	'LBL_ADD_OR_SELECT_TAG' => 'Tambah/Pilih Tag',
	'LBL_SELECT_FROM_AVAIL_TAG' => 'Pilih dari tag yang tersedia',
	'LBL_MARKET_PLACE' => 'Market Place',

	'LBL_SHARE_THIS_LIST' => 'Bagikan daftar',
	'LBL_ADD_USERS_ROLES' => 'Tambahkan Pengguna, Peran...',
	'EmailTemplates' => 'Templat Email',
	'LBL_BILLING' => 'Penagihan',
	'LBL_ENABLED' => 'Diaktifkan',

	//Title added for buttons
	'LBL_CREATE_FILTER' => 'Buat Filter',
	'LBL_IS' => 'adalah',
	'LBL_CREATION' => 'pembuatan',
	'LBL_UPLOAD' => 'Unggah',
	'LBL_ATTACH_FILES' => 'Lampirkan File',
	'LBL_KEY_FIELDS' => "Bidang Kunci",
	'LBL_ADD_TODO' => 'Tambahkan Tugas',

	"LBL_VIEW_DETAILS" => "Lihat Detail",

	//Engagements History
	"LBL_HAPPENED_ON" => "Terjadi Pada",
	"LBL_HAPPENED" => 'Terjadi',
	"LBL_TYPE" => "Jenis",
	"LBL_STATUS" => "Status",
	"LBL_CUSTOMER" => "Terkait Dengan",
	"LBL_SUMMARY" => "Ringkasan",
	"LBL_ENGAGEMENTS" => "Titik Kontak",

	'LBL_PLEASE_SELECT_ATLEAST_ONE_OPTION' => 'Silakan pilih setidaknya satu opsi',
	'LBL_STARRED' => 'Klik untuk berhenti mengikuti',
	'LBL_UNSTARRED' => 'Ikuti',
	'LBL_EDIT_EMAIL_PREFERENCE_TOOLTIP' => 'Edit preferensi ini dari menu tarik-turun Pengaturan di tampilan detail modul atau daftar',
	'LBL_SYSTEM' =>'Sistem',
	'LBL_SHOW_MAP' => 'Tampilkan Peta',
	'LBL_GOOGLE_MAP' => 'Google Map',
	'LBL_CREATION' => 'pembuatan',
	'LBL_ADD_TODO' => 'Tambah Tugas',

	'LBL_KEY_METRICS' => 'Metrik Utama',

	//Print template strings
	'LBL_TEMPLATE_NAME' => 'Nama Templat',
	'LBL_MODULE' => 'Modul',
	'LBL_IS_DEFAULT' => 'Templat Default',
	'LBL_SELECT_RECORD_FIELD' => 'Pilih Kolom Rekaman',
	'LBL_PREVIEW' => 'Pratinjau',
	'LBL_UNLINKED' => 'Tidak Tertaut',

	'LBL_FOLLOW' => 'Ikuti',
	'LBL_UNFOLLOW' => 'Berhenti Mengikuti',
	'Any' => 'Apa Saja',
	'LBL_NA' => '-NA-',
	'LBL_DISABLED' => 'Dinonaktifkan',

	//help
	'LBL_HELP_ANSWERS' => 'Jawaban',
	'LBL_HELP_ARTICLES' => 'Artikel',
	'LBL_HELP_TOUR' => 'Tur',
	'LBL_NO_HELP_ARTICLE_FOUND' => 'Maaf, tidak ada Artikel yang ditemukan',
	'LBL_HELP_SEARCH' => 'Bantuan Pencarian',
	'LBL_HELP_BROWSE_ALL' => 'Telusuri semua',

	'LBL_EXPORT_FILE_NAME' => 'Ekspor Nama Berkas',
	'LBL_EXTENSION_NOT_ALLOWED_FOR_NONADMIN' => 'Sinkronisasi %s hanya diperbolehkan untuk pengguna admin',
	'SINGLE_Invoice' => 'Faktur',
	'SINGLE_SalesOrder' => 'Pesanan Penjualan',
	'SINGLE_PurchaseOrder' => 'Pesanan Pembelian',
	'SINGLE_Quotes' => 'Penawaran Harga',
	'LBL_POST_YOUR_COMMENT_HERE' => 'Kirim komentar Anda di sini',
	// Phone Calls
	'LBL_CLICK_TO_CALL' => 'Klik untuk Menelepon',
	'LBL_SHOW_TOTAL_NUMBER_OF_RECORDS' => 'Klik untuk ukuran daftar ini',

	'LBL_GENERAL_FIELDS' => 'Bidang Umum',
	'LBL_ROLL_UP' => 'Gulir',

	'LBL_TOUCH_POINTS' => 'Titik Sentuh',
	'LBL_HISTORY' => 'Titik Sentuh',
	'LBL_ENGAGEMENT_HISTORY' => 'Riwayat Titik Sentuh',
	'LBL_SETTINGS' => 'Pengaturan',

	//List View and thumbnail view button labels
	'LBL_LIST_VIEW'=>'Tampilan Daftar',
	'LBL_THUMBNAIL_VIEW'=>'Tampilan Thumbnail',
	'LBL_CHART_VIEW'=>'Tampilan Chart',
	'LBL_EMAIL_SUPPORT' => 'Dukungan Email',
	'LBL_NO_ENTITIES_FOUND' => 'Tidak ditemukan %s',

	'LBL_TRANSFER_ALL_CASES_TO' => 'Pindahkan Semua Kasus Ke',
	'LBL_SLA_TO_BE_DELETED' => 'SLA yang Akan Dihapus',
	'LBL_TO_USE_SWITCH_TO_NEW_LOOK' => 'Untuk menggunakan <b>%s</b>, kami sarankan Anda beralih ke tampilan baru.',
	'LBL_INTERNAL_COMMENT_INFO' => 'Komentar hanya akan dilihat oleh pengguna CRM, jika kotak centang komentar internal diaktifkan. Untuk memberi tahu pelanggan (melalui alur kerja yang dapat dikonfigurasi atau portal pelanggan), biarkan kotak centang ini dinonaktifkan',
	'LBL_CHANGE' => 'Ubah',
	'LBL_REVOKE_ACCESS' => 'Cabut Akses',
	'GOOGLE_REVOKE_ACCESS_MESSAGE' => 'Mengklik ini akan menghapus autentikasi Google yang ada untuk Kontak dan Kalender. Ini tidak akan menghapus data yang sudah disinkronkan.',
	'OFFICE_REVOKE_ACCESS_MESSAGE' => 'Mengklik ini akan menghapus autentikasi Office365 yang ada untuk Kontak, Kalender, dan Email. Ini tidak akan menghapus data yang sudah disinkronkan.',
	'LBL_START_GUIDED_TOUR' => 'Mulai Tur Terpandu',
	'LBL_MENU' => 'Menu',
	'LBL_EMAIL_DOMAIN_HELPTEXT'=>'Kolom Domain Email akan digunakan untuk mencocokkan Kasus dan Kontak yang dibuat dari Email. '
	. 'Misalnya, jika email dukungan baru berasal dari john@company.com, email tersebut akan ditautkan ke Organisasi yang memiliki '
	. 'company.com di kolom Domain email. Beberapa domain harus dipisahkan dengan koma',

	'LBL_SHARED_LIST_NON_ADMIN_MESSAGE' => 'Ini adalah daftar Bersama. Silakan hubungi Administrator CRM Anda untuk mengonfigurasi kolom untuk Semua daftar',
	'LBL_SHARED_LIST_OWNER_MESSAGE' => 'Ini adalah daftar bersama. Silakan hubungi %s untuk mengubah kolom daftar ini',

	'Mr.' => 'Tn.',
	'Ms.' => 'Nn.',
	'Mrs.' => 'Ny.',
	'Dr.' => 'Dr.',
	'Prof.' => 'Prof.',
	'SINGLE_Cases'=>'Kasus',
	'LBL_TAX_MODE_INFO' =>'Jika Individu, Pajak akan ditanggungdari catatan Produk. Jika Grup, Pajak akan dipilih dari pengaturan Global.',
	'LBL_CURRENCY_INFO' =>'Nilai akan diubah ke mata uang yang dipilih berdasarkan nilai tukar yang dikonfigurasi.',
	'LBL_TAX_REGION_INFO' =>'Untuk pajak Variabel, persentase pajak akan didasarkan pada Wilayah Pajak yang dipilih.',
	'LBL_TAX_CONFIGURE' =>'Konfigurasikan wilayah pajak',
	'LBL_SEND_MSG_TO_SUPPORT' => 'Kirim email ke dukungan',
	'LBL_CHAT_WITH_SUPPORT' => 'Obrolan langsung dengan pakar CRM',

	'LBL_ROLES' => 'Peran',
	'LBL_ROLEANDSUBORDINATE' => 'Peran dan Bawahan',
	'LBL_YOUR_LEARNING_SCORE' => 'Skor pembelajaran CRM Anda',
	'LBL_SWITCH_TO_VTIGER7_NOW' => 'Beralih ke Vtiger7 sebelum 15 Februari',
	'LBL_VTIGER6_RETIREMENT_NOTICE' => 'Versi ini akan dihentikan pada 15 Februari 2016',
	'ModTracker' => 'Pembaruan',
	'LBL_MAIL_SENT_SUCCESSFULLY' => 'Email Berhasil Terkirim',
        'LBL_MAIL_SAVED_SUCCESSFULLY' => 'Email Berhasil Disimpan',
	'LBL_FAILED_TO_SEND' => 'Gagal Terkirim',

	'LBL_ESSENTIALS' => 'Esensial',
	'LBL_ALL_SETTINGS' => 'Semua Pengaturan',
	'On' => 'Aktif',
	'LBL_OPEN_IN_NEW_TAB' => 'Buka di tab baru',
	'LBL_DELETE_FOREVER'=>'Hapus selamanya',
	'LBL_PLEASE_CLICK_ON_EDIT_TO_ADD_NOTE' =>'Silakan klik edit untuk menambahkan catatan di sini..',
	'LBL_PLEASE_ENTER_YOUR_NOTE' => 'Silakan masukkan catatan Anda di sini..',
	'LBL_PORTAL' => 'Portal',
	'LBL_SESSION' =>'Sesi',
	'LBL_SESSIONS' => 'Sesi',
	'week days later' => 'beberapa hari kemudian',
	'more than week days later' => 'lebih dari beberapa hari kemudian',
	'less than week days later' => 'kurang dari beberapa hari kemudian',
	'week days ago' => 'beberapa hari yang lalu',
	'more than week days ago' => 'lebih dari beberapa hari yang lalu',
	'less than week days ago' => 'kurang dari beberapa hari yang lalu',

	'LBL_DUPLICATES' => 'Duplikat',
	'LBL_DUPLICATES_DETECTED' => 'Duplikat terdeteksi!',
	'LBL_DUPLICATES_FOUND_MESSAGE' => '%s ini tidak dapat disimpan karena duplikat %s terdapat di Vtiger dengan nilai yang cocok untuk %s.',
	'LBL_VTIGER_NOTIFICATION' => 'Pesan dari: Notifikasi Sistem Vtiger',
	'LBL_DUPLICATION_FAILURE_FROM_WORKFLOWS' => '%s berikut tidak dapat disimpan dari alur kerja "%s", karena terdapat %s lain dengan nilai yang sama.',
	'LBL_DUPLICATION_FAILURE_FROM_WEBFORMS' => '%s berikut tidak dapat disimpan dari formulir web "%s", karena terdapat %s lain dengan nilai yang sama.',
	'LBL_DUPLICATION_FAILURE_FOR_ADMIN' => 'Anda dapat %s mengubah aturan pencegahan duplikat.',
	'LBL_DUPLICATION_FAILURE_FOR_NON_ADMIN' => 'Hubungi administrator Anda untuk merevisi aturan duplikat',
	'LBL_DUPLICATE_RECORD_LISTS' =>'Duplikat %s :',
	'LBL_COLUMNS_ADDED'=>'dari %s kolom yang ditambahkan',
	'LBL_SHOW_ALL'=>'Tampilkan semua',
	'LBL_LanguageEditor_WEBTITLE' => 'Editor Label',
	'LBL_TAX_CALCULATIONS_WEBTITLE' => 'Manajemen Pajak',
	'LBL_Tags_WEBTITLE' => 'Tag Saya',
	'LBL_HIDE' => 'Sembunyikan',
	'LBL_PRINT' => 'Cetak',
	'LBL_FORWARD' => 'Teruskan',
	'LBL_NO_DEDUCTED_TAX'=>'Tidak pajak terpotong',
	'LBL_CLICK_TO_CONFIGURE'=>'Klik di sini untuk mengonfigurasi',
	'LBL_KANBAN_VIEW_INFO' => 'Tampilan Kanban hanya menampilkan peluang yang sesuai dengan kondisi daftar ini',
	'LBL_CUSTOM_FIELDS_MAX_LIMIT' => 'Anda hanya dapat menambahkan maksimum %s bidang kustom',
	'LBL_EXCEEDED_MODULE_RECORD_LIMIT' => 'Batas %s catatan (%s) terlampaui',
	'LBL_EXCEEDED_MODULE_RECORD_LIMIT_TEXT' =>'Kami menemukan bahwa Anda memiliki lebih dari %s catatan dalam %s. <br> Melebihi batas maksimum edisi ini. <br>Silakan hapus data berlebih dan coba lagi',
	'LBL_TEMPLATE_INFO_PART1'=>'Untuk melihat semua templat atau templat modul lain, masukkan nama modul atau "Semua" di kotak pencarian Nama Modul.', 
	'LBL_TEMPLATE_INFO_PART2'=>'Jika penerima di kolom KEPADA bukan dari modul yang sama dengan templat, pelacakan tidak akan diaktifkan untuk penerima tersebut, dan kolom gabungan tidak akan digabungkan.',
	'LBL_HIDDEN_BECAUSE_OF_DEPENDENCY' => 'Kolom disembunyikan karena aturan ketergantungan',
	'MAILCHIMP_REVOKE_ACCESS_MESSAGE' => 'Mengklik ini akan menghapus autentikasi MailChimp yang ada. Ini tidak akan menghapus data apa pun yang sudah disinkronkan.',
	// Added for Event Forms
	'LBL_VIEW_ANSWERS' => 'Lihat jawaban',
	'LBL_ANSWERS' => 'Jawaban',

	//Default sort order translations
	'LBL_DEFAULT_SORT_ORDER' => 'Kolom dan urutan sortir default',
	'LBL_SELECT_COLUMN' => 'Pilih Kolom',
	'LBL_SELECT_SORT_ORDER' => 'Pilih Urutan Sortir',
	'LBL_ASCENDING' => 'Ascending',
	'LBL_DESCENDING' => 'Descending',
	'LBL_DEFAULT_SORT_MESSAGE' => 'Daftar selalu diurutkan pada kolom ini secara default untuk setiap sesi pengguna baru.',
	'LBL_QUEUED' => 'Antri',
	// End
	//Added for Inbox
	'LBL_EMAILS'=>'Email',
	'LBL_CONVERSATIONS'=>'Percakapan',
	'LBL_FROM_DISABLED_MESSAGE'=>'Server email yang dipilih di halaman pengaturan server keluar tidak mengizinkan perubahan alamat Dari.',
	// End
	'LBL_MODULE_MANDATORY' => 'Modul wajib diisi',
	'Online' => 'Online',
	'Busy' => 'Sibuk',
	'LBL_BETA'=>'BETA',
	'JS_SHARED_WITH'=>'Dibagikan dengan',
	 'LBL_REPLY_TO' =>'Balas ke',
	'LBL_MODULE_ASSIGNMENT_RULES' => '%s Aturan Penugasan',

	'LBL_RECENT_UPDATES' => 'Pembaruan Terbaru',
	'LBL_VIEW_UPDATES_IN_DETAIL' => 'Baca Selengkapnya ...',
	'LBL_DEFAULT_DASHBOARD_TOOLTIP'=>'Jadikan dasbor ini sebagai default dengan mengaturnya ulang sebagai tab pertama!',
	'LBL_RELATED_MODULES_PERMISSION_DENIED' => 'Izin modul terkait ditolak',
	'LBL_RECORD_PERMISSION_DENIED' => 'Record permissions denied',
	'LBL_MASS_SELECT' => 'Pilihan Massal',
);

$jsLanguageStrings = array(
	'JS_EMAIL_SERVER_CONFIGURATION' => 'Silakan konfigurasikan pengaturan server keluar Anda dari halaman pengaturan',
	'JS_SMS_SERVER_CONFIGURATION' => 'Silakan konfigurasikan notifikasi SMS Anda dari halaman pengaturan notifikasi SMS',
	'JS_PLEASE_SELECT_ONE_RECORD' => 'Silakan pilih setidaknya satu rekaman',
	//dropdown categary
	'JS_USERS' => 'Pengguna',
	'JS_GROUPS' => 'Grup',
	'JS_ALL' => 'Semua',
	//Validation Error Message
	'JS_PLEASE_ENTER_VALID_VALUE' => 'Silakan masukkan nilai yang valid',
	'JS_PLEASE_ENTER_VALID_TAG_NAME' => 'Silakan masukkan nama tag yang valid',
	'JS_TAG_SAVED_SUCCESSFULLY' => 'Tag Tersimpan Berhasil',
	'JS_PLEASE_ENTER_VALID_EMAIL_ADDRESS' => 'Harap masukkan alamat email yang valid',
	'JS_CONTAINS_ILLEGAL_CHARACTERS' => 'Mengandung karakter ilegal',
	'JS_PHONE_NUMBER_LENGTH_EXCEEDED' => 'Panjang nomor telepon melebihi batas',
	'JS_ACCEPT_POSITIVE_NUMBER' => 'Hanya menerima angka positif',
	'JS_ACCEPT_WHOLE_NUMBERS' => 'Hanya menerima angka bulat',
	'JS_VALUE_SHOULD_BE_GREATER_THAN_ZERO' => 'Nilai harus lebih besar dari nol',
	'JS_NUMBER_SHOULD_BE_LESS_THAN_32' => 'Angka harus kurang dari 32',
	'JS_PLEASE_ENTER_VALID_DATE' => 'Harap Masukkan Tanggal yang Valid',
	'JS_PLEASE_ENTER_VALID_TIME' => 'Silakan Masukkan Waktu yang Valid',
	'JS_INVALID_PAGE_NUMBER' => 'Nomor Halaman Tidak Valid',
	'JS_SUBJECT_VALUE_CANT_BE_EMPTY' => 'Nilai subjek tidak boleh kosong',
	'JS_PERCENTAGE_SHOULD_BE_LESS_THAN_100' => 'Persentase harus kurang dari 100',


	'INVALID_NUMBER_OF' => 'Jumlah tidak valid',
	'INVALID_NUMBER' => 'Jumlah tidak valid',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Apakah Anda yakin ingin menghapus?',

	'OVERWRITE_EXISTING_MSG1' => 'Timpa alamat yang ada dengan yang dipilih ',
	'OVERWRITE_EXISTING_MSG2' => 'detail alamat?',
	'SINGLE_Accounts' => 'Organisasi',
	'SINGLE_Contacts' => 'Kontak',
	'SINGLE_Project' => 'Proyek',
	'SINGLE_ProjectMilestone' => 'Milestone Proyek',

	'LBL_DELETE_CONFIRMATION' => 'Apakah Anda yakin ingin menghapus?', // This is added as duplicate as we need to show different message for different modules. Ex:Accounts has different message
	'LBL_UNLINK_CONFIRMATION' => 'Apakah Anda yakin ingin memutuskan tautan?',
	'LBL_DELETE_USER_CONFIRMATION' => 'Ketika Pengguna dihapus, pengguna akan ditandai sebagai "Tidak Aktif" dan tidak ada catatan baru yang dapat diberikan kepada Pengguna tersebut, dan pengguna tidak akan dapat masuk. Apakah Anda yakin ingin menghapus?',
	'LBL_DELETE_CONFIRMATION_NOTE' => 'Catatan: Data yang dihapus akan disimpan di Recycle Bin dan dihapus setelah %s hari',
	'LBL_MASS_DELETE_CONFIRMATION' => 'Apakah Anda yakin ingin menghapus Data yang dipilih?',
	'JS_LBL_SAVE' => 'Simpan',
	'JS_LBL_CANCEL' => 'Batal',
	'JS_DUPLICTAE_CREATION_CONFIRMATION' => 'Nama Organisasi sudah ada. Apakah Anda ingin membuat data duplikat?',

	'SHOULD_BE_LESS_THAN_TODAY' => 'Harus terjadi sebelum hari ini',
	'JS_PLEASE_SELECT_ATLEAST_ONE_OPTION' => 'Silakan pilih setidaknya satu opsi',
	'JS_SELECT_MODULE' => 'Silakan Pilih Modul',
	'JS_PLEASE_SELECT_ATLEAST_ONE_MANDATORY_FIELD' => 'Silakan pilih setidaknya satu Kolom Wajib',
	'JS_SELECT_MODULE' => 'Silakan pilih satu modul',
	'JS_PLEASE_ENTER_INTEGER_VALUE' => 'Silakan masukkan nilai integer',
	'JS_PLEASE_ENTER_DECIMAL_VALUE' => 'Silakan masukkan nilai desimal',
	'JS_PLEASE_ENTER_POSITIVE_DECIMAL_VALUE' => 'Silakan masukkan nilai desimal positif',

	'JS_START_TIME_SHOULD_BE_GREATER_THAN_CURRENT_TIME' => 'Waktu Mulai harus lebih besar dari Waktu Saat Ini',
	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'harus lebih kecil dari Tanggal Saat Ini',
	'JS_SHOULD_BE_GREATER_THAN_CURRENT_DATE' => 'harus lebih besar dari Tanggal Saat Ini',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'harus lebih besar dari atau sama dengan',
	'JS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO' => 'harus lebih kecil dari atau sama dengan',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'harus lebih besar dari atau sama dengan',
	'JS_CURRENT_DATE' => 'Tanggal Saat Ini',
	'JS_PERCENTAGE_VALUE_SHOULD_BE_LESS_THAN_100' => 'Nilai persentase harus kurang dari 100',
	'JS_ACCEPT_ONLY_NUMBER' => 'Hanya menerima angka',
	'JS_THIS_FILE_HAS_ALREADY_BEEN_SELECTED' => 'Berkas ini telah dipilih',
	'JS_MAX_FILE_UPLOAD_EXCEEDS' => 'Unggahan berkas maksimum terlampaui',
	'JS_THIS_DOCUMENT_HAS_ALREADY_BEEN_SELECTED' => 'Dokumen ini telah dilampirkan',
	'JS_LIST_EXIST' => 'Daftar sudah ada',


	//Roles
	'JS_FAILED_TO_SAVE' => 'Gagal menyimpan perubahan di server',

	//Import Translations
	'JS_IMPORT_FILE_CAN_NOT_BE_EMPTY' => 'Berkas Impor tidak boleh Kosong',
	'JS_PLEASE_SELECT_ONE_FIELD_FOR_MERGE' => 'Pilih setidaknya satu kolom yang cocok',
	'JS_MAP_NAME_CAN_NOT_BE_EMPTY' => 'Nama Peta tidak boleh kosong',
	'JS_MAP_NAME_ALREADY_EXISTS' => 'Nama Peta sudah ada',
	'JS_SELECT_FILE_EXTENSION' => 'Silakan pilih berkas dengan folEkstensi lowing:',
	'JS_UPLOADED_FILE_SIZE_SHOULD_BE_LESS_THAN' => 'Ukuran file yang diunggah harus kurang dari',
	'JS_UPLOADED_FILE_SIZE_EXCEEDS' => 'Ukuran file yang diunggah melebihi',
	'JS_PLEASE_SPLIT_FILE_AND_IMPORT_AGAIN' => 'Silakan bagi file menjadi beberapa file yang lebih kecil dan impor kembali.',
	'JS_FIELD_MAPPED_MORE_THAN_ONCE' => 'Kolom dipetakan lebih dari sekali',
	'JS_MAP_MANDATORY_FIELDS' => 'Harap petakan kolom wajib',
	'JS_MAP_MERGE_CRITERIA_FIELDS' => 'Harap petakan kolom yang cocok',
	'JS_PLEASE_ENTER_SOME_VALUE' => 'Harap masukkan beberapa nilai untuk pencarian',
	'JS_VCF_FILE_IMPORT_WARNING' => 'Anda telah memilih berkas VCF. Hanya Kontak yang dapat diimpor dari berkas VCF. Untuk mengimpor berkas ini, silakan mulai impor dari modul Kontak',
	'JS_ICS_FILE_IMPORT_WARNING' => 'Anda telah memilih berkas ICS. Hanya Kalender yang dapat diimpor dari berkas ICS. Untuk mengimpor berkas ini, silakan mulai impor dari modul Kalender',
	//Select2 elements validation message
	'JS_YOU_CAN_SELECT_ONLY'=> 'Anda hanya dapat memilih',
	'JS_ITEMS' => 'item',

	'JS_LBL_PERMISSION' => 'Izin',
	'JS_CHECK_FILE_INTEGRITY' => 'Periksa Integritas Berkas',
	'JS_DUPLICATE_RECORD' => 'Duplikat Rekaman',

	//advance filter checkbox type condition values
	'JS_IS_ENABLED' => 'diaktifkan',
	'JS_IS_DISABLED' => 'dinonaktifkan',

	'JS_PLEASE_ENTER_SOME_TEXT_FOR_COMMENT' => 'Silakan masukkan beberapa teks untuk komentar',
	'JS_LBL_COMMENT_VALUE_CANT_BE_EMPTY' => 'Nilai komentar tidak dapat kosong',
	'JS_REQUIRED_FIELD' => 'Kolom ini wajib diisi',
	'JS_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Tidak dapat menghapus Widget Default',
	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'harus kurang dari Tanggal Saat Ini',
	'JS_NO_CREATE_OR_NOT_QUICK_CREATE_ENABLED' => 'Tidak ada izin pembuatan atau tidak diaktifkan untuk pembuatan cepat',

	//Image Action
	'LBL_IMAGE_DELETED_SUCCESSFULLY' => 'Gambar Berhasil Dihapus',
	'LBL_IMAGE_NOT_DELETED' => 'Gambar Tidak Dihapus',
	'LBL_YES' => 'Ya',
	'LBL_NO' => 'Tidak',
	'AM' => 'AM',
	'PM' => 'PM',
	'JS_ERROR' => 'Error',
	'JS_INFORMATION' => 'Informasi',
	'JS_DO_NOT_HAVE_AN_EMAIL_ID' => 'tidak memiliki alamat email',
	'NONE_OF_THE_FIELD_VALUES_ARE_CHANGED_IN_MASS_EDIT' => 'Tidak ada nilai kolom yang diubah dalam Edit Massal',

	//Notification messages for inventory module
	'JS_PLEASE_SELECT_AN_ACCOUNT_TO_COPY_ADDRESS' => 'Silakan pilih Organisasi untuk menyalin alamat',
	'JS_PLEASE_SELECT_AN_CONTACT_TO_COPY_ADDRESS' => 'Silakan pilih Kontak untuk menyalin alamat',
	'JS_SELECTED_ACCOUNT_DOES_NOT_HAVE_AN_ADDRESS' => 'Organisasi yang dipilih tidak memiliki alamat untuk disalin',
	'JS_SELECTED_CONTACT_DOES_NOT_HAVE_AN_ADDRESS' => 'Kontak yang dipilih tidak berisi alamat yang akan disalin',
	'JS_PLEASE_ENTER_PRIMARY_EMAIL_VALUE_TO_ENABLE_PORTAL_USER' => 'Silakan masukkan alamat email utama untuk mengaktifkan pengguna portal',
	'JS_PRIMARY_EMAIL_FIELD_DOES_NOT_EXISTS' => 'Kolom email utama tidak ada untuk mengaktifkan pengguna portal',

	//Tag Cloud validation messages
	'JS_PLEASE_ENTER_A_TAG' => 'Silakan masukkan tag',
	'JS_TAG_NAME_ALREADY_EXIST' => 'Nama tag sudah ada',
	'JS_MAX_TAG_LENGTH_EXCEEDS' => 'Panjang tag melebihi ukuran maksimum',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'Anda tidak akan memiliki izin untuk melihat rekaman ini Setelah disimpan. Apakah Anda ingin melanjutkan?',
	'JS_NO_RECORDS_RELATED_TO_THIS_FILTER' => 'Tidak Ada Rekaman yang Terkait dengan Daftar Ini',

	// Calendar Reminder popup
	'JS_START_DATE_TIME' => 'Tanggal & Waktu Mulai',
	'JS_END_DATE_TIME' => 'Tanggal & Waktu Berakhir',
	'JS_POSTPONE' => 'Tunda',
	'JS_MESSAGE' => 'Pesan',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'Anda tidak akan memiliki izin untuk melihat rekaman ini setelah disimpan. Apakah Anda ingin melanjutkan?',

	//Settings page translations
	'JS_SUCCESSFULLY_PINNED' => 'Pintasan berhasil ditambahkan',
	'JS_SUCCESSFULLY_UNPINNED' => 'Pintasan berhasil dihapus',
	'JS_SHORTCUT_ALREADY_ADDED' => 'Pintasan ini sudah ditambahkan',
	'JS_MESSAGE' => 'Pesan',
	'JS_MASS_EDIT_LIMIT' => 'Operasi Edit Massal dapat dilakukan pada 500 rekaman atau kurang sekaligus',

	//Module Manager
	'JS_MODULE_ENABLED' => 'Modul Diaktifkan',
	'JS_MODULE_DISABLED' => 'Modul Dinonaktifkan',

	//Crom tasks
	'JS_VALUE_SHOULD_NOT_BE_LESS_THAN' => 'Frekuensi setiap tugas cron yang dikonfigurasi tidak boleh kurang dari daripada',
	'JS_MINUTES' => 'menit',

	//PickList
	'JS_ITEM_RENAMED_SUCCESSFULLY' => 'Item Berhasil Diganti Namanya',
	'JS_ITEM_ADDED_SUCCESSFULLY' => 'Item Berhasil Ditambahkan',
	'JS_NO_ITEM_SELECTED' => 'Tidak Ada Item yang Dipilih',
	'JS_MORE_THAN_ONE_ITEM_SELECTED' => 'Lebih dari satu Item yang Dipilih',
	'JS_ITEMS_DELETED_SUCCESSFULLY' => 'Item Berhasil Dihapus',
	'JS_DUPLICATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Entri duplikat ditemukan untuk nilai tersebut',
	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => 'Anda harus memilih data dalam grup yang sama untuk digabungkan',
	'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING' => 'Pilih setidaknya dua data untuk digabungkan',
	'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS' => 'Anda diperbolehkan memilih maksimal tiga data',
	//Notification message for dashboard widget delete
	'JS_ARE_YOU_SURE_TO_DELETE_WIDGET' => 'Apakah Anda yakin ingin menghapus widget? dapatkan - %s?',
	'JS_ARE_YOU_SURE_TO_DELETE_DASHBOARDTAB' => 'Apakah Anda yakin ingin menghapus tab dasbor ini - %s?',
	'JS_TABS_LIMIT_EXCEEDED' => 'Maaf! Tidak dapat menambahkan lebih dari 10 tab',
	'JS_DUPLICATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Entri duplikat ditemukan untuk nilai tersebut',
	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => 'Anda harus memilih data dalam grup yang sama untuk digabungkan',
	'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING' => 'Pilih setidaknya dua data untuk digabungkan',
	'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS' => 'Anda diperbolehkan memilih maksimal tiga data',
	'JS_TOTAL_RECORDS' => 'Total data',
	'JS_PAGE_NOT_EXIST' => 'Halaman tidak ada',
	'JS_YOU_ARE_IN_PAGE_NUMBER' => 'Anda berada di nomor halaman',

	//More currencies message
	'JS_PLEASE_ENABLE_BASE_CURRENCY_FOR_PRODUCT' => 'Harap aktifkan mata uang dasar untuk produk',
	'JS_PLEASE_SELECT_BASE_CURRENCY_FOR_PRODUCT' => 'Harap pilih mata uang dasar untuk produk',
	'JS_BASE_CURRENCY_CHANGED_TO_DISABLE_CURRENCY' => 'Mata Uang Dasar harus diubah untuk menonaktifkan ',

	//Delete Records message
	'JS_RECORDS_ARE_GETTING_DELETED' => 'Rekaman sedang dihapus',
	'JS_RECORD_GETTING_DELETED' => 'Rekaman sedang dihapus',
	'JS_NO_RESULTS_FOUND' => 'Tidak Ada Hasil Ditemukan',

	'JS_RECORDS TRANSFERRED SUCCESSFULLY' => 'Kepemilikan rekaman telah berhasil ditransfer',

	//TextSearch Language String
	'LBL_SEARCHING' => 'Mencari di ',
	'JS_RECORDS_TRANSFERRED_SUCCESSFULLY' => 'Kepemilikan rekaman berhasil ditransfer.',
	'JS_USER_DELETED_SUCCESSFULLY' => 'Pengguna berhasil dihapus.',

	'JS_MAX_RECORDS_LIMIT' => 'Maksimum Rekaman untuk Dicetak adalah :',
	'JS_USER_EXISTS' => 'Pengguna Sudah Ada',
	'JS_REENTER_PASSWORDS' => 'Masukkan Kata Sandi Penyewa',
	'LBL_SIGN_IN_AS_USER'=>'Masuk sebagai pengguna lain akan mengakhiri sesi saat ini. Yakin ingin melanjutkan?',
	'JS_REENTER_PASSWORDS' => 'Kata Sandi Penyewa',
	'SINGLE_Vendors' => 'Vendor',

	//Feedback on removing old version
	'JS_PLEASE_GIVE_YOUR_FEEDBACK' => 'Silakan Isi Umpan Balik Anda',
	'JS_PBX_CALL_FROM' => 'Panggilan Dari',
	'JS_PBX_INCOMING_CALL' => 'Panggilan Masuk',
	'JS_PBX_OUTGOING_SUCCESS'=>'Angkat gagang telepon ekstensi untuk menghubungi nomor',
	'JS_PBX_OUTGOING_FAILURE'=>'Panggilan Gagal',
	'JS_PBX_FILL_ALL_FIELDS'=>'Silakan isi semua kolom',
	'JS_PBX_CAMPAIGN_NAME' => 'Nama Kampanye',
	'JS_PBX_CAMPAIGN_NUMBER' => 'Nomor Kampanye',
	'JS_MIN_SEARCH_KEY_LENGTH' => 'Kunci Pencarian minimal harus 3 karakter',
	'JS_NO_MATCH' => 'Tidak Ditemukan Data yang Cocok',
	'JS_PBX_OUTGOING_CALL' => 'Panggilan Keluar',
	'JS_PBX_CALL_TO' => 'Panggilan Ke',
	'JS_REQUIRED' => 'Wajib',
	'JS_PHONE_NUMBER' => 'Nomor Telepon',
	'JS_NO_CREATE_PERMISSION' => 'Panggilan perlu dijawab sebelum membuat data',
	'HelpDesk' => 'Tiket',
	'Potentials' => 'Peluang',
	'JS_CALL_NOT_ANSWERED_UPDATE_PERMISSION' => "Panggilan perlu dijawab sebelum menghubungkan rekaman", 
	'JS_CALL_NOT_ANSWERED' => "Panggilan perlu dijawab sebelum melakukan tindakan",
	// ends
	'JS_NO_EDIT_PERMISSION' => 'Anda tidak memiliki izin untuk mengedit acara ini',

	//Google Synchronization
	'SYNC_REMOVED_SUCCESSFULLY' => 'Sinkronisasi Google berhasil dihapus.',
	'REMOVE_SYNCHRONIZATION_MESSAGE' => 'Mengklik ini akan menghapus autentikasi Gmail yang ada. Ini tidak akan menghapus rekaman yang sudah disinkronkan.',
	'REMOVE_SYNCHRONIZATION' => 'Hapus Sinkronisasi',
	'FIELD_MAPPING' => 'Pemetaan Kolom',
	'LBL_SYNC_BUTTON' => 'Sinkronkan Sekarang',
	'LBL_SYNCRONIZING' => 'Sinkronkan....',
	'LBL_NOT_SYNCRONIZED' => 'Anda belum melakukan sinkronisasi',
	'LBL_FIELD_MAPPING' => 'Pemetaan Kolom',

	'LBL_RESTORE_CONFIRMATION' => 'Apakah Anda yakin ingin memulihkan pengguna ini?',
	'LBL_DELETE_USER_PERMANENT_CONFIRMATION' => 'Setelah dihapus, pengguna ini tidak dapat dipulihkan kembali. Apakah Anda yakin ingin menghapus pengguna ini secara permanen?',

	'LBL_LANGUAGE_LABEL_VALIDATION' => 'Nilai label tidak boleh kosong. Anda harus memasukkan nilai tertentu.',
	'JS_CHANGES_WILL_BE_LOST' => 'Perubahan Anda akan hilang!',
	'JS_RECORD_DELETED' => 'Rekaman dihapus',
	'JS_NO_DELETE_PERMISSION' => 'Tidak ada izin hapus',
	'JS_CONFIRM_MARK_AS_HELD' => 'Apakah Anda yakin ingin menandai Acara sebagai Telah Diselenggarakan?',
	'JS_CONFIRM_MARK_AS_COMPLETED' => 'Apakah Anda yakin ingin menandai Tugas sebagai Selesai?',
	'JS_TODO_MARKED_AS_COMPLETED' => 'Tugas ditandai sebagai Selesai',
	'JS_EVENT_MARKED_AS_HELD' => 'Acara ditandai sebagai Telah Diselenggarakan',
	'JS_FUTURE_EVENT_CANNOT_BE_MARKED_AS_HELD' => 'Acara mendatang tidak dapat ditandai sebagai Ditahan',
	'JS_PERMISSION_DENIED' => 'Izin ditolak',
	'LBL_SMS_MAX_CHARACTERS_ALLOWED' => 'Maksimal 160 karakter diperbolehkan untuk pesan teks',
	'JS_VIEWNAME_ALERT' => 'Maksimal 40 karakter diperbolehkan untuk nama daftar',
	'JS_EXCEEDS_MAX_UPLOAD_SIZE' => 'Melebihi ukuran unggahan maksimum',
	'JS_FUTURE_EVENT_CANNOT_BE_HELD' => 'Tidak Dapat Ditahan untuk Mendatang',
	'LBL_WARNING' => 'Peringatan',
	'DELETE_USER_PERMANENT_WARNING' => 'Menghapus pengguna secara permanen akan mentransfer semua data termasuk komentar dan riwayat ke pengguna baru.',
	'JS_DECIMAL_SEPARATOR_AND_GROUPING_SEPARATOR_CANT_BE_SAME' => 'Pemisah desimal dan pemisah pengelompokan tidak boleh sama',
	'JS_FUTURE_EVENT_CANNOT_BE_HELD' => 'Tidak Dapat Disimpan untuk Masa Mendatang',
	'JS_CLOSE' => 'Tutup',

	// For Line Iteam Currency Symbol select while Import
	'JS_CURRENCY_TOOLTIP_CONTENT_TITLE' => 'Mata Uang Item Baris',
	'JS_CURRENCY_TOOLTIP_CONTENT_MESSAGE' => 'Untuk mengimpor nilai Mata Uang dalam Item Baris, Vtiger akan menggunakan pengaturan ini untuk mengidentifikasi mata uang. Nilai mata uang apa pun di luar tabel item baris diasumsikan dalam mata uang pilihan Pengguna (dipilih di \'Preferensi Saya\')',
	'LBL_CANT_SELECT_CONTACT_FROM_LEADS' => 'Tidak dapat memilih Kontak terkait untuk Prospek',
	'JS_TRY_LATER' => 'Silakan coba lagi nanti!',
	'JS_FILE_NAME' => 'Nama File',
	'JS_EXTERNAL_FILE_URL' => 'Url File',
	'JS_PLEASE_SELECT_A_FILE' => 'Silakan pilih file',
	// SMSNotifier Phone Format Warning
	'JS_PHONEFORMAT_ERROR' => 'Harap periksa apakah nomor telepon dalam format internasional E.164 dengan awalan \'+\' dan kode negara Ex +1 415 599 2671',

	// Leads and Potentials Field Mapping
	'JS_NONE' => 'None',
	'JS_IS_ALREADY_BEEN_MAPPED' => 'sudah dipetakan',
	'JS_CANT_MAP' => 'Tidak bisa dipetakan',
	'JS_WITH' => 'dengan',
	'JS_MAPPING_DELETED_SUCCESSFULLY' => 'Pemetaan Berhasil Dihapus',

	//JS Field Type Translation
	'JS_phone' => 'Telepon',
	'JS_picklist' => 'Daftar Pilihan',
	'JS_email' => 'Surel',
	'JS_text' => 'String',
	'JS_currency' => 'Mata Uang',
	'JS_multiSelectCombo' => 'Kotak Kombo Pilihan Ganda',
	'JS_time' => 'Waktu',
	'JS_textArea' => 'Text Area',
	'JS_url' => 'Url',
	'JS_string' => 'String',
	'JS_checkBox' => 'Check Box',
	'JS_date' => 'Tanggal',
	'JS_decimal' => 'Desimal',
	'JS_percent' => 'Persen',
	'JS_skype' => 'Skype',
	'JS_None' => 'Tidak Ada',
	'JS_integer' => 'Integer',
	'JS_double' => 'Desimal',
	'JS_reference' => 'referensi',
	'JS_image' => 'Gambar',

	// AutoFill Overwriting message
	'JS_OVERWRITE_AUTOFILL_MSG1' => 'Apakah Anda ingin menimpa yang sudah ada',
	'JS_OVERWRITE_AUTOFILL_MSG2' => 'dengan yang dipilih',

	//Demo Data Module Translatios
	'JS_ADD_DEMO_DATA_CONFIRMATION'=> 'Apakah Anda yakin ingin menambahkan demo? data ke semua modul?',
	'JS_ADD_DEMO_DATA_INFO'=> 'Data demo dapat dihapus dengan mengeklik tombol "Hapus Data Demo".',
	'JS_CLEAR_DEMO_DATA_CONFIRMATION'=> 'Apakah Anda yakin ingin menghapus data demo di semua modul?',
	'JS_CLEAR_DEMO_DATA_INFO'=> 'Data demo dapat ditambahkan dengan mengeklik tombol "Tambahkan Data Demo".',
	'JS_DEMO_DATA_GETTING_POPULATED'=> 'Data Demo sedang ditambahkan, harap tunggu...',
	'JS_DEMO_DATA_GETTING_CLEARED'=> 'Data demo sedang dihapus, harap tunggu...',
	'JS_DEMO_DATA_ADDED' => 'Data demo ditambahkan ke semua modul.',
	'JS_DEMO_DATA_CLEARED' => 'Data demo dihapus dari semua modul.',
	'JS_HOME_DASH_BOARD_CLEAR_INFO'=>'Catatan: Anda dapat mengaktifkan kembali data demo dari',
	'JS_SETTINGS_PATH'=>'Pengaturan > Konfigurasi > Editor Konfigurasi.',
	'JS_PRINT' => 'Cetak',
	'JS_SAVE_AS_IMAGE' => 'Simpan Sebagai Gambar',
	'JS_DIRECTORY_IS_EMPTY' => 'Direktori kosong',
	'JS_PLEASE_SELECT_AN_RELATED_TO_COPY_ADDRESS' => 'Silakan pilih Modul Prospek/Kontak untuk menyalin alamat',
	'SINGLE_Leads' => 'Prospek',
	'JS_SELECTED_LEAD_DOES_NOT_HAVE_AN_ADDRESS' => 'Prospek yang dipilih tidak berisi alamat untuk disalin',
	'JS_INVALID_EMAILS' => 'Email Tidak Valid',
	'JS_DIRECTORY_IS_EMPTY' => 'Direktori kosong',
	'JS_NO_LINE_ITEM' =>'Item baris tidak boleh kosong.',
	'JS_INTERNAL_COMMENT' => 'Komentar Internal',
	'JS_INTERNAL_COMMENT_INFO' => 'Komentar hanya akan dilihat oleh pengguna CRM jika kotak centang komentar internal diaktifkan. Untuk memberi tahu pelanggan (melalui alur kerja yang dapat dikonfigurasi atau portal pelanggan), biarkan kotak centang ini dinonaktifkan',

	'JS_NO_TAXES_EXISTS' => 'Tidak ada pajak',
	'JS_CONFIRM_TAXES_AND_CHARGES_REPLACE' => 'Apakah Anda ingin memperbarui nilai pajak & biaya yang sesuai dengan wilayah yang dipilih?',
	'JS_PRINTTEMPLATEMODULE_DISABLED' => 'Modul PrintTemplates dinonaktifkan. Tidak dapat menjalankan operasi',
	'JS_SENT_FOR_SIGNATURE' => 'Dikirim untuk ditandatangani',
	'JS_FAILED_TO_SEND_FOR_SIGNATURE' => 'Gagal mengirim untuk ditandatangani',
	'JS_SUITABLE_VTIGER_FIELD_NOT_AVAILABLE_FOR_MAPPING' => 'Bidang Vtiger yang sesuai tidak tersedia untuk pemetaan',
	'JS_SAVED_SUCCESSFULLY' => 'Pengaturan berhasil disimpan',
	'phone' => 'Telepon',
	'email' => 'Email',
	'url' => 'Url',
	'home' => 'Rumah',
	'work' => 'Kantor',
	'custom' => 'Kustom',
	'mobile' => 'Ponsel',
	'main' => 'Utama',
	'work_fax' => 'Faks',
	'home_fax' => 'Faks Rumah',
	'pager' => 'Pager',
	'profile' => 'Profil',
	'blog' => 'Blog',
	'home-page' => 'Beranda',
	'address' => 'Alamat',

	// Cron
	'JS_NONE_OF_THE_VALUES_ARE_CHANGED' => 'Tidak ada nilai yang diubah',
	'JS_REMOVE_SYNC_CONFIRMATION' => 'Menghapus sinkronisasi hanya akan menghapus autentikasi yang ada, tidak akan menghapus data yang disinkronkan. Jika Anda menyinkronkan lagi dengan akun Google yang sama, data duplikat akan dibuat. Apakah Anda yakin ingin menghapus sinkronisasi?',

	//Recipient preferences labels
	'JS_LBL_GETTING_RECIPIENT_PREFS' => 'Mendapatkan preferensi penerima..',
	'JS_LBL_SAVING_PREFERENCES' => 'Menyimpan preferensi..',
	// Social Module Strings
	'JS_PLEASE_WAIT' => 'Mohon Tunggu...',
	'JS_SOCIAL_FIELD_ERROR' => 'Kolom wajib diisi',
	// Twitter Specific
	'JS_ADD_FAVOURITE_SUCCESS_MSG' => 'Tweet berhasil ditambahkan ke daftar favorit',
	'JS_UNDO_FAVOURITE_SUCCESS_MSG' => 'Tweet berhasil dihapus dari daftar favorit',
	'JS_UNDO_RETWEET_SUCCESS_MSG' => 'Urungkan Retweet',
	'JS_STATUS_UPDATE_SUCCESS_MSG' => 'Berhasil diperbarui',
	'JS_TWEET_DELETE_MSG' => 'Status berhasil dihapus',
	'JS_INVALID_TWITTER_HANDLER_NAME' => 'Nama Pengguna Twitter tidak valid',
	'JS_RELATION_ADDED_SUCESSFULLY' => 'Relasi Berhasil Ditambahkan',
	'JS_FAILED_TO_ADD_RELATION' => 'Gagal Menambahkan Relasi',
	'JS_SOCIAL_POST_DELETE_CONFIRMATION' => 'Anda yakin ingin menghapus?',
	'JS_EVENT_OR_TODO_ADDED_SUCCESS_MSG' => 'Acara/Tugas berhasil ditambahkan',
	'JS_LEAD_ADDED_SUCCESS_MSG' => 'Prospek berhasil ditambahkan',
	'JS_OPPORTUNITY_ADDED_SUCESS_MSG' => 'Peluang berhasil ditambahkan',
	'JS_TICKET_ADDED_SUCESS_MSG' => 'Tiket berhasil ditambahkan',
	'JS_CASE_ADDED_SUCESS_MSG' => 'Kasus berhasil ditambahkan',
	'JS_SELECT_OPTION' => 'Pilih Opsi',

	'JS_LOADING_PLEASE_WAIT' => 'Memuat... Harap tunggu..',
	'JS_SAVING_PLEASE_WAIT' => 'Menyimpan.. Harap tunggu..',
	'JS_DUPLICATE_EMAILS_PLEASE_CHECK' => 'Alamat email duplikat. Silakan periksa',
	'JS_USER_EXISTS' => 'Pengguna sudah ada',
	'JS_ALERT' => 'Peringatan',
	'JS_SUCCESS' => 'Berhasil',
	'JS_REMOVE_MASS_TAG_WARNING' => 'Apakah Anda yakin ingin menghapus tag %s untuk rekaman yang dipilih',
	'JS_VIEW_ALREADY_EXISTS' => 'Tampilan sudah ada',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE' => 'Silakan masukkan nilai dalam rentang',
	'JS_UPLOAD' => 'Unggah',
	'JS_TODO_ADDED_SUCCESS_MSG' => 'Tugas berhasil ditambahkan',
	'JS_EVENT_ADDED_SUCCESS_MSG' => 'Acara berhasil ditambahkan',
	'JS_ACTIVE' => 'Aktif',
	'JS_SNOOZED' => 'Ditunda',
	'JS_INVALID_URL' => 'URL tidak valid',
	'JS_MAX_ALLOWED_CHARACTERS' => 'Karakter maksimum yang diizinkan adalah',
	'JS_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Apakah Anda yakin ingin menghapus?',
	'JS_TAB_LABEL_EXCEEDS_CHARS' => 'Panjang label tab harus kurang dari %s karakter',
	'JS_STARRED' => 'Berhenti mengikuti',
	'JS_NOT_STARRED' => 'Ikuti',
	//Tags
	'JS_NO_TAG_EXISTS' => 'Tidak Ada Tag' ,
	//help wizard
	'JS_HELP_AND_SUPPORT' => 'Bantuan & Dukungan',
	'JS_WHAT_DO_YOU_NEED_HELP_WITH' => 'Bantuan apa yang Anda butuhkan?',
	'JS_SUBMIT' => 'Kirim',

	/** Vtiger7 translations **/
	'JS_ADD_MAX_15_ITEMS' => 'Anda hanya dapat menambahkan 15 item',
	'SINGLE_SLA' => 'SLA',

	'JS_DEFAULT_ENABLED' => 'Default diaktifkan',
	'JS_DEFAULT_DISABLED' => 'Default dinonaktifkan',
	'JS_EDIT_FIELDS' => '%s Kolom & Tata Letak',
	'JS_MORE_VTIGER' => 'Ada lebih banyak data yang akan disinkronkan di vtiger',
	'JS_MORE_GOOGLE' => 'Ada lebih banyak data yang akan disinkronkan di Google',
	'JS_MORE_OFFICE365' => 'Ada lebih banyak data yang akan disinkronkan di Office365',
	'JS_TOKEN_EXPIRED' => 'Autentikasi Office365 telah kedaluwarsa. Klik tombol Masuk dengan Office365 untuk mengotorisasi ulang.',
	'JS_EDIT_FIELDS' => '%s Kolom & Tata Letak',
	'JS_WISH_TO_PROCEED' =>"Apakah Anda yakin ingin melanjutkan?",
	'JS_SWITCH_TO_OLD_LOOK_CONFIRMATION_MESSAGE' => 'Beberapa fitur, termasuk notifikasi, warna daftar pilihan, dan rekaman tindak lanjut, tidak tersedia di versi lama. Anda dapat kembali ke versi baru dengan memilih versi baru dari menu kanan atas.',
	'JS_PROCEED_OLD_VERSION' => 'Lanjutkan ke versi lama',
	'JS_STAY_WITH_NEW_VERSION' => 'Tetap menggunakan versi baru',

	//TimeAgo plugin Strings
	'JS_AGO' => 'lalu',
	'JS_FROM_NOW' => 'mulai sekarang',
	'JS_LESSTHAN_A_MINUTE' => 'kurang dari satu menit',
	'JS_A_MINUTE' =>'satu menit',
	'JS_MINUTES' => 'menit',
	'JS_AN_HOUR' => 'satu jam',
	'JS_HOURS' => 'jam',
	'JS_A_DAY' => 'satu hari',
	'JS_DAYS' => 'hari',
	'JS_A_MONTH' => 'satu bulan',
	'JS_MONTHS' => 'bulan',
	'JS_A_YEAR' => 'setahun',
	'JS_YEARS' => 'tahun',
	'JS_TODAY' => 'hari ini',
	'JS_TOMORROW' => 'besok',
	'JS_YESTERDAY' => 'kemarin',

	'JS_CREATE_TASK' => 'Buat Tugas',

	//Notifications
	'JS_MENTION_ATLEAST_ONE_USER' => 'Sebutkan setidaknya satu pengguna',
	'JS_LOADING' => 'Memuat...',
	'JS_CASE_ACCEPTED_SUCCESSFULLY' => 'Kasus berhasil diterima',

	'JS_UPLOAD_SUCCESSFUL' => 'Berkas Berhasil Diunggah',
	'JS_UPLOAD_FAILED' => 'Unggahan Berkas Gagal',
	'JS_FAILED_TO_UPLOAD_FILE' => 'Gagal mengunggah berkas',
	'JS_DOCUMENT_CREATED' => 'Dokumen dibuat',
	'JS_DOCUMENT_CREATION_FAILED' => 'Pembuatan dokumen gagal',

	'JS_TEMPLATE_TEXT_EXCEEDS_LIMIT' => 'Ukuran templat melebihi ukuran maksimum yang diizinkan, yaitu 100 KB. Harap hapus beberapa teks di templat dan coba lagi',
	'JS_PLEASE_SELECT_IMAGE' => 'Silakan pilih gambar',

	'JS_LBL_MY_PREFERENCES' => 'Preferensi Saya',
	'JS_LBL_MY_PREFERENCES_TEXT' => 'Konfigurasikan preferensi pribadi Anda termasuk Zona Waktu, Mata Uang, dan Format Tanggal. Anda juga dapat mengunggah foto profil dari Preferensi Saya.',
	'JS_LBL_HELP' => 'Bantuan',
	'JS_LBL_HELP_TEXT' => 'Klik tombol Bantuan untuk menemukan Panduan dan FAQ, dan gunakan menu tarik-turun Bantuan untuk mendapatkan bantuan dari tim dukungan Vtiger',
	'JS_LBL_RESTART_TOUR' => 'Mulai Ulang Tur Terpandu',
	'JS_LBL_RESTART_TOUR_TEXT' => 'Klik di sini untuk memulai tur ini lagi',
	'JS_GOOGLE_REMOVE_SYNC_CONFIRMATION' => 'Mencabut akses hanya akan menghapus autentikasi Google yang ada untuk Kontak dan Kalender, tidak akan menghapus data yang disinkronkan. Jika Anda menyinkronkan lagi dengan akun Google yang sama, data duplikat akan dibuat. Apakah Anda yakin ingin mencabut akses?',
	'JS_OFFICE_REMOVE_SYNC_CONFIRMATION' => 'Mencabut akses hanya akan menghapus autentikasi Office365 yang ada untuk Kontak, Kalender, dan Email, tidak akan menghapus data yang disinkronkan. Jika Anda menyinkronkan lagi dengan akun Office365 yang sama, data duplikat akan dibuat. Apakah Anda yakin ingin mencabut akses?',
	'JS_FOLLOW_RECORD' => 'Mengikuti rekaman',
	'JS_FOLLOWING' => 'Mengikuti',
	'JS_UNFOLLOW_RECORD' => 'Berhenti mengikuti rekaman',
	'JS_UNFOLLOWING' => 'Berhenti mengikuti',
	'JS_RECORD_CREATED' => 'Rekaman dibuat',
	'JS_RECORD_UPDATED' => 'Rekaman diperbarui',
	'JS_LIST_SAVED' => 'Daftar disimpan',
	'JS_TAB_DELETED' => 'dihapus',
	'JS_TAB_RENAMED' => 'Diganti namanya',
	'JS_TAB_REORDERED' => 'Diurutkan ulang',
	'JS_RECIPIENT_PREFERENCES_SAVED' => 'Preferensi penerima disimpan',
	'JS_TASK_ADDED' => 'Tugas ditambahkan',
	'JS_MARKED_COMPLETED' => 'Ditandai sebagai selesai',
	'JS_TASK_PRIORITY_CHANGED' => 'Prioritas tugas diubah',
	'JS_NO_PERMISSION_TO_MARK_AS_HELD' => 'Anda tidak memiliki izin untuk menandai acara ini sebagai telah selesai',
	'JS_TAG_ADDED' => 'Tag ditambahkan',
	'JS_TAB_DELETED' => 'dihapus',
	'JS_TAB_RENAMED' => 'Diganti namanya',
	'JS_TAB_REORDERED' =>'Diubah urutannya',
	//Convert Lead
	'JS_CONVERT_LEAD_ERROR' => 'Anda harus mengaktifkan modul Organisasi atau Kontak untuk mengonversi Prospek.',

	'JS_CHECK_START_AND_END_DATE'=>'Tanggal & Waktu Akhir harus lebih besar dari atau sama dengan Tanggal & Waktu Mulai',
	'JS_CHECK_START_AND_END_DATE_SHOULD_BE_GREATER'=> 'Tanggal & Waktu Akhir harus lebih besar dari Tanggal & Waktu Mulai',
	'JS_HOLD_FOLLOW_UP_SHOULD_BE_LESS_THAN_CURRENT_DATE'=> 'Tindak Lanjut Penahanan harus lebih besar dari atau sama dengan Tanggal & Waktu Mulai',
	'JS_DUPLICATES_DETECTED' => 'Duplikat terdeteksi!',

	'JS_IS' => 'adalah',
	'JS_IS_NOT' => 'tidak',
	'JS_EQUALS' => 'sama dengan',
	'JS_NOT_EQUALS_TO' => 'tidak sama dengan',
	'JS_ONLY_LETTERS_AND_NUMBERS_ALLOWED' => 'Hanya huruf (a-z), angka (0-9), dan spasi yang diizinkan diizinkan',
	'JS_WIDGET_RESIZING_WAIT_MSG' => 'Isi widget akan dimuat setelah diubah ukurannya.',
	'JS_SLA_FULFILLMENT_RATE' => 'TINGKAT PEMENUHAN SLA',
	'JS_TICKET_COUNT' => 'JUMLAH KASUS',
	'JS_CASES_AGE_HOURS'=>'USIA KASUS (Jam)',
	'JS_BACKLOG'=> 'Backlog',
	'JS_AND' => 'dan',
	'JS_SEQUENCE_UPDATED_SUCCESSFULLY'=>'Urutan berhasil diperbarui',
	'JS_VIEW_RECORD' => 'Lihat Rekaman',
	'JS_HIDE'=>'Sembunyikan',
	'JS_SHOW_ALL'=>'Tampilkan semua',
	'JS_SHOW_LESS' => 'Tampilkan lebih sedikit',
	'JS_SHOW_MORE' => 'Tampilkan lebih banyak',

	'JS_KANBAN_ANCHORS_LIMIT_MESSAGE' => 'Anda hanya dapat memilih hingga 10 tahapan', 
	'JS_KANBAN_NO_MORE_RECORDS' => 'Tidak ada lagi rekaman yang ditemukan',
	'JS_DELETED' => 'dihapus',
	'JS_CLEAR_TEMPLATE_CONTENT_RECIPIENTS'=>'Mengubah modul akan menghapus templat yang dipilih dan penerima dari kolom TO. Apakah Anda ingin melanjutkan?',
	'JS_WORKFLOW_ACTIONS_LIMIT_EXCEEDED' => 'Melebihi batas maksimum tindakan dalam edisi ini.',
	'JS_RECORD_CREATION_LIMIT_EXCEEDED' => 'Buat Rekaman - Melebihi batas maksimum edisi ini.',
	'JS_KANBAN_NO_ANCHORS_CONFIGURED' => "Anda belum menentukan tahapan penjualan apa pun untuk alur penjualan Anda.",
	'JS_KANBAN_NO_ANCHORS_CONFIGURED_NON_ADMIN' => "Anda belum menentukan tahapan penjualan apa pun untuk alur penjualan Anda. Silakan hubungi Administrator Anda untuk menentukan tahapan penjualan sesuai proses penjualan Anda.",
	'JS_UPDATE_MAPPING_CONFIRMATION' => 'Ada beberapa kolom yang cocok dalam berkas CSV yang tidak tersimpan dalam pemetaan ini. Apakah Anda ingin memperbarui pemetaan ini dengan kolom baru?',
	'JS_MAPPING_UPDATED' => 'Pemetaan baru diperbarui.',
	'JS_MAILCHIMP_REMOVE_SYNC_CONFIRMATION' => 'Mencabut akses akan menghapus autentikasi MailChimp yang ada, tetapi tidak akan menghapus data yang disinkronkan. Apakah Anda yakin ingin mencabut akses?',
	'JS_WARNING' => 'Peringatan',
	'JS_CANT_SELECT_LEAD' => 'Tidak dapat memilih Prospek terkait',
	'JS_CANT_SELECT_CONTACT' => 'Tidak dapat memilih Kontak terkait',
	'JS_MSG_EMPTY_RB_CONFIRMATION' => 'Apakah Anda yakin ingin menghapus semua data yang dihapus secara permanen dari basis data Anda?',
	'JS_LBL_RESTORE_RECORDS_CONFIRMATION' => 'Apakah Anda yakin ingin memulihkan data?',
	'JS_COMMENT_POSTED_SUCCESSFULLY'=>'Komentar berhasil diposting',
	'JS_SHARED_PUBLICLY_WITH'=>'Dibagikan secara publik dengan',
	'JS_SHARED_PRIVATELY_WITH'=>'Dibagikan secara pribadi dengan',
	'JS_MAIL_SENT_SUCCESSFULLY'=>'Email berhasil terkirim',
	'JS_SHARED_PUBLICLY_TITLE'=>'Percakapan Publik juga dapat dilihat oleh pengguna di luar kotak surat yang terhubung, jika mereka memiliki akses ke Kontak, Peluang, dll. terkait',
	'JS_SHARED_PRIVATELY_TITLE'=>'Percakapan Pribadi hanya dapat dilihat oleh anggota kotak surat yang terhubung dengannya.',
	'JS_LINKED_RECORDS_SUCCESS'=>'Data yang terhubung berhasil diperbarui',
	'JS_MAIL_DRAFTED_SUCCESSFULLY'=>'Email berhasil disusun',

	//Custom view default sort translations.
	'JS_PLEASE_REMOVE_ONE_FIELD_FROM_CHOOSE_COLUMNS_LIST_TO_ADD_DEFAULT_SORT_FIELD' => 'Hanya 16 kolom yang diizinkan dalam tampilan daftar, termasuk kolom pengurutan.',
	'JS_DEFAULT_SORT_NOTIFY' => 'Daftar sekarang diurutkan berdasarkan kolom pengurutan default ',
	'JS_ENABLED' => 'Diaktifkan',
	'JS_DISABLED' => 'Dinonaktifkan',
	'JS_ONLY_ALLOWED_USERS_ARE_ALLOWED_TO_DO_ACTION'=>'Kami tidak dapat menandai percakapan sebagai belum dibaca/dibaca/dihapus/selesai/pribadi/publik karena Anda bukan pemiliknya.',
	'JS_SHARED_WITH'=>'Dibagikan dengan',
	'JS_DEFAULT_DASHBOARD_TOOLTIP' => 'Jadikan dasbor ini sebagai default oleh menyusun ulang sebagai tab pertama!',
	'JS_SET_DEFAULT_TAB' => 'ditetapkan sebagai dasbor default Anda',
	'JS_PASSWORD_MISMATCH_ERROR' => 'Silakan masukkan kembali kata sandi. Nilai "kata sandi baru" dan "konfirmasi kata sandi" tidak cocok.',
	'LBL_LIST_DELETE_CONFIRMATION' => 'Apakah Anda yakin ingin menghapus?',
	'JS_WIDGET_RESIZING_WAIT_MSG' => 'Isi widget akan dimuat setelah diubah ukurannya.',
        'JS_COPIED_SUCCESSFULLY' => 'Berhasil disalin',
        'JS_ATLEAST_SELECT_ONE_FIELD' => 'Setidaknya satu kolom harus dipilih',
        'JS_RELATED_ACCOUNT_IS_NOT_AVAILABLE' => 'Data Organisasi terkait tidak tersedia',
        'JS_RELATED_CONTACT_IS_NOT_AVAILABLE' => 'Data Kontak terkait tidak tersedia',
        'JS_REPEAT_DATE_SHOULD_BE_GREATER_THAN_START_DATE' => 'Tanggal pengulangan harus lebih besar atau sama dengan Tanggal Mulai Tanggal',
        'JS_PASSWORD_NOT_STRONG' => 'Untuk menjaga keamanan data Anda, kami sarankan Anda menggunakan kata sandi yang kuat &lt;br&gt; &lt;ul&gt; &lt;li&gt;Kata sandi harus minimal 8 karakter &lt;/li&gt; &lt;li&gt;Sertakan setidaknya satu angka &lt;/li&gt; &lt;li&gt;Sertakan setidaknya satu huruf kecil &lt;/li&gt; &lt;li&gt;Sertakan setidaknya satu huruf besar &lt;/li&gt; &lt;li&gt;Sertakan setidaknya satu karakter khusus dalam kata sandi &lt;/li&gt; &lt;/ul&gt;',
);
