<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LayoutEditor' => 'Editor Tata Letak',
	'LBL_FIELDS_AND_LAYOUT_EDITOR' => 'Kolom dan Editor Tata Letak',
	'LBL_CREATE_CUSTOM_FIELD' => 'Buat Kolom Kustom',
	'LBL_DETAILVIEW_LAYOUT' => 'Tata Letak Tampilan Detail',
	'LBL_ARRANGE_RELATED_TABS' => 'Atur Tab Terkait',
	'LBL_ADD_CUSTOM_FIELD' => 'Tambahkan Kolom Kustom',
	'LBL_ADD_CUSTOM_BLOCK' => 'Tambahkan Blok',
	'LBL_SAVE_FIELD_SEQUENCE' => 'Simpan Urutan Kolom',
	'LBL_BLOCK_NAME' => 'Nama Blok',
	'LBL_ADD_AFTER' => 'Tambahkan Setelah',
	'LBL_ACTIONS' => 'Tindakan',
	'LBL_ALWAYS_SHOW' => 'Selalu Tampilkan',
    'LBL_SHOW_INACTIVE_FIELDS' => 'Tampilkan Kolom yang Tidak Aktif',
	'LBL_SHOW_HIDDEN_FIELDS' => 'Lihat Kolom Tersembunyi',
	'LBL_DELETE_CUSTOM_BLOCK' => 'Hapus Blok Kustom',
	'LBL_MANDATORY_FIELD' => 'Kolom Wajib',
	'LBL_ACTIVE' => 'Aktif',
	'LBL_QUICK_CREATE' => 'Buat Cepat',
	'LBL_SUMMARY_FIELD' => 'Tampilan Ringkasan',
    'LBL_KEY_FIELD_VIEW' => 'Tampilan Kolom Kunci',
	'LBL_MASS_EDIT' => 'Edit Massal',
	'LBL_DEFAULT_VALUE' => 'Nilai Default',
	'LBL_SELECT_FIELD_TYPE' => 'Pilih Jenis Kolom',
	'LBL_LABEL_NAME' => 'Nama Label',
	'LBL_LENGTH' => 'Panjang',
	'LBL_DECIMALS' => 'Desimal',
	'LBL_ENTER_PICKLIST_VALUES' => 'Masukkan Nilai Daftar Pilihan..',
	'LBL_PICKLIST_VALUES' => 'Nilai Daftar Pilihan',
	'LBL_INACTIVE_FIELDS' => 'Kolom Tidak Aktif',
	'LBL_REACTIVATE' => 'Aktifkan Kembali',
	'LBL_ARRANGE_RELATED_LIST' => 'Atur Daftar Terkait',
	'LBL_SELECT_MODULE_TO_ADD' => 'Pilih Modul yang Akan Ditambahkan',
    'LBL_SELECT_HIDDEN_MODULE' => 'Pilih modul Tersembunyi',
	'LBL_NO_RELATED_INFORMATION' => 'Tidak Ada Informasi Terkait',
	'LBL_RELATED_LIST_INFO' => 'Seret dan letakkan modul untuk menyusun ulang daftar',
	'LBL_REMOVE_INFO' => 'Klik ikon hapus untuk menghapus hubungan secara permanen dari daftar',
	'LBL_ADD_MODULE_INFO' => 'Pilih modul dari modul yang dihapus untuk ditambahkan kembali ke daftar',
    'LBL_MANY_MANY_TEXT' => 'Hubungan Banyak-Banyak saat ini hanya tersedia untuk %s dan %s',
	'LBL_SELECT_MODULE' => 'Pilih Modul..',
	'LBL_DUPLICATES_EXIST' => 'Nama Blok sudah ada',
	'LBL_NON_ROLE_BASED_PICKLIST' => 'Daftar Pilihan Non-Peran',
	'LBL_DUPLICATE_FIELD_EXISTS' => 'Kolom Duplikat Ada',
	'LBL_WRONG_FIELD_TYPE' => 'Jenis Kolom Salah',
	'LBL_ROLE_BASED_PICKLIST' => 'Daftar Pilihan Berdasarkan Peran',
	'LBL_CLICK_HERE_TO_EDIT' => 'Klik di sini untuk mengedit',
    'LBL_EDIT_FIELD' => 'Edit properti Kolom: %s',

	//Field Types
	'Text'=>'Teks',
	'Decimal'=>'Desimal',
	'Integer'=>'Bilangan Bulat',
	'Percent'=>'Persen',
	'Currency'=>'Mata Uang',
	'Date'=>'Tanggal',
	'Email'=>'Email',
	'Phone'=>'Telepon',
	'PickList'=>'Daftar Pilihan',
	'MultiSelectCombo'=>'Kombo Pilihan Ganda Kotak',
	'URL' => 'URL',
	'Checkbox' => 'Kotak Centang',
	'TextArea' => 'Area Teks',
	'Skype'=>'Skype',
	'Time'=>'Waktu',
	
	//Translation for module
	'Calendar' => 'Tugas',
	'LBL_FIELD_COULD_NOT_BE_CREATED'=>'Bidang %s tidak dapat dibuat',
	'SELECT_MODULE' => 'Pilih Modul',
    
    //Related Lists 
    'LBL_RELATION_SHIPS' => 'Hubungan',
    'LBL_ADD_RELATIONSHIP' => 'Tambahkan Hubungan',
    'LBL_RELATED_MODULE' => 'Modul Terkait',
    'LBL_ADDING_RELATIONSHIP' => 'Menambahkan Hubungan untuk %s',
    'LBL_SELECTED_RELATED_MODULE' => 'Pilih terkait modul',
    'LBL_SELECTED_RELATION_TYPE' => 'Pilih jenis hubungan',
    'ONE_ONE_AND_MANY_ONE_RELATIONSHIP' => 'Hubungan Satu-satu & Banyak-satu',
    'ONE_MANY_RELATIONSHIP' => 'Hubungan Satu-banyak & Banyak-banyak',
    '1-1' => 'Satu ke Satu',
    '1-N' => 'Satu ke Banyak',
    'N-1' => 'Banyak ke Satu',
    'N-N' => 'Banyak ke Banyak',
    
	
	//New layout translations
	'LBL_FIELD_TYPES'                   => 'Jenis Bidang', 
	'LBL_BASIC_FIELDS'             => 'Bidang Dasar', 
	'LBL_MANDATORY'                => 'Bidang Wajib', 
	'LBL_PROPERTIES'               => 'Properti', 
	'LBL_DRAG_UI_TYPE'             => 'Seret dan Hapus Bidang di sini', 
	'LBL_RELATION_FIELDS'          => 'Bidang Relasi', 
	'LBL_SELECT_BLOCK'             => 'Pilih Blok', 
    'LBL_RELATION_ADDED_SUCCESS'   => 'Relasi berhasil ditambahkan',
    
    'FIELD_NAME_IN_PRIMARY_MODULE' => 'Bidang Relasi dalam %s',
    'FIELD_NAME_IN_RELATED_MODULE' => 'Bidang Relasi dalam %s',
    'TAB_IN_PRIMARY_MODULE'        => 'Tabel/Tab dalam %s',
    'TAB_IN_RELATED_MODULE'        => 'Tabel/Tab dalam %s',
    
    'LBL_DETAIL_VIEW'              => 'Tampilan Detail',
    'LBL_EXPANDED'                 => 'Diperluas',
    'LBL_COLLAPSED'                => 'Diciutkan',
    
    'LBL_FILED_IN_PRIMARY_HELP_TEXT' => 'Bidang referensi modul %s',
    'LBL_TAB_IN_PRIMARY_HELP_TEXT'   => 'Tabel/Tab modul %s',
    'LBL_FILED_IN_RELATED_HELP_TEXT' => 'Kolom referensi modul  %s',
    'LBL_TAB_IN_RELATED_HELP_TEXT'   => 'Tabel/Tab modul %s',
    'LBL_NO_RELATION_TYPE'         => 'Tidak ada hubungan jenis ini',

	'LBL_CREATE_ITEM_CUSTOM_FIELD' => 'Buat Kolom Kustom Item Baris',
	'LBL_MAP_PRODUCT_FIELD' => 'Petakan ke kolom Produk',
	'LBL_MAP_SERVICE_FIELD' => 'Petakan ke kolom Layanan',
	'LBL_ENABLE_TO_MAP_PRODUCT_FIELD' => 'Aktifkan pemetaan kolom Produk',
	'LBL_ENABLE_TO_MAP_SERVICE_FIELD' => 'Aktifkan pemetaan kolom bidang Layanan',
    
    //Vtiger7 Strings
    'LBL_NO_RELATED_INFO' => 'Tidak ada hubungan',
    'LBL_ADD_NEW_FIELD_HERE' => 'Tambahkan bidang baru di sini',
    'LBL_SAVE_LAYOUT' => 'Simpan Tata Letak',
    'LBL_SHOW_FIELD' => 'Tampilkan Bidang',
    'LBL_ENABLE_OR_DISABLE_FIELD_PROP' => 'Aktifkan / Nonaktifkan properti bidang',
    'LBL_PROP_MANDATORY' => 'wajib',
    'LBL_DEFAULT_VALUE_NOT_SET' => 'Nilai default tidak ditetapkan',
    'LBL_INFO' => 'Info',
    'LBL_PRODUCTFIELDDEFAULTVALUE' => ' (Produk)',
    'LBL_SERVICEFIELDDEFAULTVALUE' => ' (Layanan)',
    'LBL_SHOW_THIS_FIELD_IN' => 'Klik di sini untuk menampilkan kolom ini dalam tampilan %s',
    'LBL_MAKE_THIS_FIELD' => 'Klik di sini untuk menjadikan kolom ini %s',
    'LBL_HIDE_THIS_FIELD_IN' => 'Klik di sini untuk menyembunyikan kolom ini dalam tampilan %s',
    'LBL_NOT_MAKE_THIS_FIELD' => 'Klik di sini untuk menjadikan kolom ini bukan %s',
    'LBL_TAB_NAME_HELP_TEXT' => 'Daftar %s yang ditampilkan dalam rekaman %s',
    'LBL_TAB_NAME_TEXT' => 'Nama tab %s dalam rekaman %s',
    'LBL_FILED_NAME_HELP_TEXT' => 'Kolom Referensi ke %s dalam rekaman %s akan ditambahkan',
    'LBL_FIELD_NAME_TEXT' => 'Nama kolom %s dalam rekaman %s',
	'LBL_COLLAPSE_BLOCK' => 'Ciutkan Blok',
	'LBL_COLLAPSE_BLOCK_DETAIL_VIEW' => 'Ciutkan blok dalam tampilan detail',
    'LBL_HEADER' => 'Header',
    'LBL_DETAIL_HEADER' => 'Header rekaman',
    'LBL_HEADER_FIELD' => 'Tampilan Header',

	'LBL_DUPLICATE_HANDLING' => 'Pencegahan Duplikat',
	'LBL_DUPLICATE_CHECK' => 'Aktifkan pemeriksaan duplikat',
	'LBL_DUPLICATION_INFO_MESSAGE' => 'Fitur pencegahan duplikat hanya mencegah rekaman duplikat baru dibuat oleh pengguna dan aplikasi eksternal. Rekaman yang dibuat dari Impor dan dari Alur Kerja tidak akan diperiksa duplikatnya.<br><br>Rekaman duplikat yang ada dapat dihapus menggunakan fitur "Temukan Duplikat" dari halaman modul.',
	'LBL_SELECT_FIELDS_FOR_DUPLICATION' => 'Pilih kolom unik tempat rekaman duplikat akan diperiksa',
	'LBL_SELECT_FIELDS' => 'Pilih Kolom',
	'LBL_MAX_3_FIELDS' => 'Maksimal 3 Kolom',
	'LBL_SELECT_RULE' => 'Pilih aturan untuk menangani duplikat',
	'LBL_ALLOW_DUPLICATES' => 'Izinkan Duplikat',
	'LBL_DO_NOT_ALLOW_DUPLICATES' => 'Jangan izinkan Duplikat',
	'LBL_DUPLICATES_IN_SYNC_MESSAGE' => 'Tindakan yang harus diambil jika rekaman duplikat ditemukan saat sinkronisasi dengan aplikasi eksternal',
	'LBL_PREFER_LATEST_RECORD' => 'Lebih suka rekaman terbaru',
	'LBL_PREFER_INTERNAL_RECORD' => 'Lebih suka rekaman internal',
	'LBL_PREFER_EXTERNAL_RECORD' => 'Lebih suka rekaman eksternal',
	'LBL_SYNC_TOOLTIP_MESSAGE' => 'Lebih suka rekaman terbaru - Data rekaman yang terakhir diubah akan disimpan<br>Lebih suka rekaman internal - Rekaman yang ada akan disimpan apa adanya<br>Lebih suka rekaman eksternal - Data dari aplikasi eksternal akan disalin',
);

$jsLanguageStrings = array(
	'JS_BLOCK_VISIBILITY_SHOW' => 'Penampilan blok diaktifkan',
	'JS_BLOCK_VISIBILITY_HIDE' => 'Penyembunyikan blok diaktifkan',
	'JS_CUSTOM_BLOCK_ADDED' => 'Blok Kustom Baru Ditambahkan',
	'JS_BLOCK_SEQUENCE_UPDATED' => 'Urutan Blok Diperbarui',
	'JS_SELECTED_FIELDS_REACTIVATED' => 'Kolom yang Dipilih Diaktifkan Kembali',
	'JS_FIELD_DETAILS_SAVED' => 'Detail Kolom Tersimpan',
	'JS_CUSTOM_BLOCK_DELETED' => 'Blok Kustom Dihapus',
	'JS_CUSTOM_FIELD_ADDED' => '%s Kolom Ditambahkan',
	'JS_CUSTOM_FIELD_DELETED' => 'Bidang Kustom Dihapus',
	'JS_LENGTH_SHOULD_BE_LESS_THAN_EQUAL_TO' => 'Panjang harus kurang dari atau sama dengan',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_2TO5' => 'Desimal harus dalam rentang 2 hingga 5',
	'JS_SAVE_THE_CHANGES_TO_UPDATE_FIELD_SEQUENCE' => 'Simpan perubahan untuk memperbarui urutan Bidang',
	'JS_RELATED_INFO_SAVED' => 'Info Terkait Tersimpan',
	'JS_BLOCK_NAME_EXISTS' => 'Nama Blok sudah ada',
	'JS_NO_HIDDEN_FIELDS_EXISTS' => 'Tidak Ada Bidang yang Tidak Aktif',
	'JS_SPECIAL_CHARACTERS' => 'Karakter Khusus seperti',
	'JS_NOT_ALLOWED' => 'tidak diizinkan',
	'JS_FIELD_SEQUENCE_UPDATED' => 'Urutan Bidang Diperbarui',
	'JS_DUPLICATES_VALUES_FOUND' => 'Nilai Duplikat ditemukan',
    'JS_FIELD_IN_RELATED_MODULE'  => 'Bidang relasi dalam %s',
    'JS_TAB_IN_RELATED_MODULE' => 'Tabel/Tab dalam %s',
    'JS_FILED_IN_RELATED_HELP_TEXT' => 'Bidang referensi modul %s',
    'JS_TAB_IN_RELATED_HELP_TEXT'   => 'Tabel/Tab modul %s',
    'JS_TAB_FIELD_DELETION'   => 'Menghapus relasi akan menghapus bidang %s dalam modul %s dan menghapus %s Tabel/Tab dalam %s. Apakah Anda ingin melanjutkan?',
    'JS_ONE_ONE_RELATION_FIELD_DELETE' => 'Ini akan menghapus kolom %s di modul %s dan akan menghapus kolom %s di modul %s. Apakah Anda ingin melanjutkan?',
	'JS_CUSTOM_FIELDS_MAX_LIMIT' => 'Anda hanya dapat menambahkan maksimal %s kolom kustom di blok %s',
    'JS_DEFAULT_VALUE_NOT_SET' => 'Nilai default tidak ditetapkan',
    'JS_DEFAULT_VALUE' => 'Nilai Default',
    'JS_SAVE_MODULE_SEQUENCE' => 'Simpan perubahan untuk memperbarui urutan Modul Terkait',
    'JS_PRODUCTFIELDDEFAULTVALUE' => ' (Produk)',
    'JS_SERVICEFIELDDEFAULTVALUE' => ' (Layanan)',
    'JS_TAB_TAB_DELETION' => 'Ini akan menghapus tab %s di modul %s dan datanya. Apakah Anda ingin melanjutkan?',
    'JS_SHOW_THIS_FIELD_IN' => 'Klik di sini untuk menampilkan kolom ini dalam tampilan %s',
    'JS_MAKE_THIS_FIELD' => 'Klik di sini untuk menjadikan kolom ini %s',
    'JS_HIDE_THIS_FIELD_IN' => 'Klik di sini untuk menyembunyikan kolom ini dalam tampilan %s',
    'JS_NOT_MAKE_THIS_FIELD' => 'Klik di sini untuk menjadikan kolom ini bukan %s',
    'JS_TAB_NAME_HELP_TEXT' => 'Daftar %s yang ditampilkan dalam rekaman %s',
    'JS_TAB_NAME_TEXT' => 'Nama tab %s dalam rekaman %s',
    'JS_FILED_NAME_HELP_TEXT' => 'Kolom Referensi ke %s dalam rekaman %s akan ditambahkan',
    'JS_FIELD_NAME_TEXT' => 'Nama kolom %s dalam rekaman %s',
    'JS_PROP_MANDATORY' => 'wajib',
    'JS_SUMMARY' => 'Ringkasan',
    'JS_KEY_FIELD' => 'Kolom Kunci',
    
    'JS_QUICK_CREATE' => 'Buat Cepat',
    'JS_MASS_EDIT' => 'Edit Massal',
    'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Operasi ini akan mengakibatkan penghapusan data secara permanen.
                                                 Ketika sebuah kolom dihapus, nilai yang tersimpan di kolom ini akan dihapus dan tidak dapat diambil.
                                                 Jika Anda tidak yakin dan ingin melihat data ini di kemudian hari, Anda dapat menandai kolom tersebut sebagai Tidak Aktif, alih-alih menghapusnya. Kolom yang tidak aktif dapat diaktifkan kapan saja.
                                                 Apakah Anda yakin ingin menghapus kolom ini?',
    'JS_FIELD_DELETE_CONFIRMATION' => 'Hapus - Saya tidak membutuhkan data di kolom ini.',
	'JS_STATUS_CHANGED_SUCCESSFULLY' => 'Status berhasil diubah',
    'JS_FIELD_CAN_EITHER_BE_HEADER_OR_SUMMARY_ENABLED' => 'Kolom dapat berupa kolom header atau kolom kunci',
    'JS_DETAIL_HEADER' => 'Header rekaman',
    'JS_MAXIMUM_HEADER_FIELDS_ALLOWED' => 'Maksimal %s kolom header yang diizinkan',
    'JS_NAME_FIELDS_APPEAR_IN_HEADER_BY_DEFAULT' => 'Kolom nama muncul di Header secara default',
    'JS_FIELD_IS_HEADER_ENABLED_FOR_VTIGER7' => 'Bidang ini diaktifkan untuk Header Vtiger7, akan muncul di Tampilan Ringkasan',

	'JS_DUPLICATE_HANDLING_SUCCESS_MESSAGE' => 'Berhasil diperbarui untuk mempertimbangkan bidang terpilih dalam pencegahan duplikat',
	'JS_DUPLICATE_HANDLING_FAILURE_MESSAGE' => 'Gagal mempertimbangkan bidang terpilih dalam pencegahan duplikat',
	'JS_DUPLICATE_CHECK_DISABLED' => 'Pemeriksaan duplikat dinonaktifkan',
);
