<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	// Basic Strings
	'Settings' => 'Pengaturan',
	'LBL_MAILROOM'=>'Ruang Surat',
	'LBL_SEARCH_SETTINGS_PLACEHOLDER' => 'Pengaturan Pencarian',
	'LBL_SUMMARY' => 'Ringkasan',
	'LBL_ACTIVE_USERS' => 'Pengguna',
	'LBL_WORKFLOWS_ACTIVE' => 'Alur Kerja',
	'LBL_MODULES' => 'Modul',
	'LBL_SETTINGS_SHORTCUTS' => 'Pintasan Pengaturan',
	'LBL_UNPIN' => 'Lepas Pin',
	'LBL_PIN' => 'pin',

	// Blocks
	'LBL_STUDIO' => 'Studio',
	'LBL_COMMUNICATION_TEMPLATES' => 'Templat',
	'LBL_USER_MANAGEMENT' => 'Kontrol Pengguna & Akses',
	'LBL_ACCESS_MANAGEMENT' => 'Manajemen Akses',
	'LBL_MODULE_MANAGER' => 'Manajemen Modul',
	'LBL_NOTIFICATIONS' => 'Notifikasi',
	'LBL_EXTERNAL_SERVER_SETTINGS' => 'Pengaturan Server Eksternal',
	'LBL_OTHER_SETTINGS' => 'Pengaturan Lainnya',
	'LBL_EXTENSIONS_PLACE' => 'Tempat Ekstensi',
	'LBL_EXTENSIONS' => 'Ekstensi',
	'LBL_PBXMANAGER' => 'PBXManager',
    'LBL_INTEGRATION' => 'Integrasi',
    'LBL_EXCHANGE_CONNECTOR' => 'Konektor Exchange',
    
    // Fields
	'LBL_DESCRIPTION' => 'Deskripsi',
    
	// Other Strings
	'LBL_USER_DESCRIPTION' => 'Kelola pengguna yang dapat mengakses Vtiger CRM',
	'LBL_ROLES' => 'Peran',
	'LBL_ROLE_DESCRIPTION' => 'Atur hierarki peran dan tetapkan kepada pengguna',

	'LBL_PROFILES' => 'Profil',
	'LBL_PROFILE_DESCRIPTION' => 'Kelola akses modul khusus pengguna ke berbagai Peran',

	'USERGROUPLIST' => 'Grup',
	'LBL_GROUP_DESCRIPTION' => 'Kelola berbagai jenis tim berdasarkan peran, pengguna, dan profil',

	'LBL_SHARING_ACCESS' => 'Aturan Berbagi',
	'LBL_SHARING_ACCESS_DESCRIPTION' => 'Kelola aturan berbagi modul & aturan berbagi kustom',

	'LBL_WORKFLOW_LIST' => 'Daftar Alur Kerja',
	'LBL_AVAILABLE_WORKLIST_LIST' => 'Alur Kerja yang Tersedia',
	'LBL_FIELDFORMULAS' => 'Rumus Bidang',
	'LBL_FIELDFORMULAS_DESCRIPTION' => 'Tambahkan persamaan kustom ke bidang kustom',

	'VTLIB_LBL_MODULE_MANAGER' => 'Modul',
	'VTLIB_LBL_MODULE_MANAGER_DESCRIPTION' => 'Kelola perilaku modul di dalam vtiger CRM',
	'LBL_PICKLIST_EDITOR' => 'Nilai Bidang Daftar Pilihan',
	'LBL_PICKLIST_DESCRIPTION' => 'Sesuaikan nilai Daftar Pilihan di setiap modul',
	'LBL_PICKLIST_DEPENDENCY_SETUP' => 'Ketergantungan Daftar Pilihan',
	'LBL_PICKLIST_DEPENDENCY_DESCRIPTION' => 'Atur Ketergantungan antar nilai Daftar Pilihan di setiap modul',

	'LBL_FIELDFORMULAS' => 'Rumus Bidang',
	'LBL_FIELDFORMULAS_DESCRIPTION' => 'Tambahkan persamaan khusus ke bidang khusus',

	'LBL_MENU_EDITOR' => 'Menu Utama',
	'LBL_MENU_DESC' => 'Sesuaikan Urutan Menu',
	'LBL_MENU_EDITOR_MESSAGE' => 'Jumlah item menu yang ditampilkan akan bergantung pada ukuran layar dan mungkin lebih sedikit daripada item yang dipilih.',

	'EMAILTEMPLATES' => 'Templat Email',
	'LBL_EMAIL_TEMPLATE_DESCRIPTION' => 'Kelola templat untuk modul Email',

	'LBL_COMPANY_DETAILS' => 'Detail Perusahaan',
	'LBL_COMPANY_DESCRIPTION' => 'Tentukan alamat bisnis perusahaan',

	'LBL_MAIL_MERGE' => 'Gabungan Surat',
	'LBL_MAIL_MERGE_DESCRIPTION' => 'Kelola templat untuk Gabungan Surat',

	'LBL_TAX_SETTINGS' => 'Perhitungan Pajak',
	'LBL_TAX_DESCRIPTION' => 'Kelola pajak dan tarif pajak terkait',

	'LBL_MAIL_SERVER_SETTINGS' => 'Server Keluar',
	'LBL_MAIL_SERVER_DESCRIPTION' => 'Konfigurasi detail Server Surat Keluar',

	'INVENTORYTERMSANDCONDITIONS' => 'Inventaris: Syarat dan Ketentuan',
	'LBL_INV_TANDC_DESCRIPTION' => 'Tentukan syarat dan ketentuan untuk Penawaran Harga, Faktur, dan Pesanan Penjualan',

	'LBL_ANNOUNCEMENT_DESCRIPTION' => 'Kelola pengumuman di seluruh perusahaan',

	'LBL_CURRENCY_SETTINGS' => 'Mata Uang',
	'LBL_CURRENCY_DESCRIPTION' => 'Kelola mata uang dan nilai tukar internasional',

	'LBL_CUSTOMIZE_MODENT_NUMBER' => 'Penomoran Modul',
	'LBL_CUSTOMIZE_MODENT_NUMBER_DESCRIPTION' => 'Kustomisasi Nomor Entitas Modul',

	'LBL_MAIL_SCANNER' => 'Konverter Email',
	'LBL_MAIL_SCANNER_DESCRIPTION' => 'Konfigurasi kotak masuk email untuk pemindaian dan perekaman lampiran',

	'LBL_LIST_WORKFLOWS' => 'Alur Kerja',
	'LBL_LIST_WORKFLOWS_DESCRIPTION' => 'Buat dan edit alur kerja',
    'LBL_SELECT_DATE' => 'Pilih tanggal',

	'Configuration Editor' => 'Editor Konfigurasi',
	'LBL_CONFIG_EDITOR_DESCRIPTION' => 'Perbarui berkas konfigurasi aplikasi',
	'Update configuration file of the application' => 'Perbarui berkas konfigurasi aplikasi',
	'LBL_PERSONAL_EMAIL_TRACKING_INFO' => "Untuk melacak pembukaan email langsung yang dikirim ke kontak, harap aktifkan kotak centang ini. Harap diperhatikan bahwa email yang dikirim dari modul Kampanye Email selalu dilacak, dan tidak terpengaruh oleh pengaturan ini",
	'LBL_CUSTOMER_PORTAL' => 'CPortal Pelanggan',
	'PORTAL_EXTENSION_DESCRIPTION' => 'Memungkinkan Anda mengonfigurasi Plugin Portal Pelanggan',
	
	'LBL_LAYOUT_EDITOR_DESCRIPTION' => 'Merancang dan memodifikasi tata letak di setiap modul',
	'LBL_WEBFORMS_DESCRIPTION' => 'Membuat dan mengelola formulir web yang dapat digunakan untuk mendapatkan Prospek, Kontak, Tiket, dll.',
	'LBL_TO_ADD_NEW_USER_PLEASE_CLICK_ON' => 'Untuk menambahkan Pengguna baru, silakan klik ',
	'LBL_SETTINGS_ICON' => 'Ikon Pengaturan',
	'LBL_ADD_OR_DELETE_USERS' => 'Menambah/Menghapus Pengguna',
	'LBL_ADD_USER' => 'Menambah Pengguna',
	'LBL_LABELS_EDITOR' => 'Editor Label',
	'LBL_LABELS_EDITOR_DESCRIPTION' => 'Memungkinkan Anda menyesuaikan nama modul, label kolom, dan string lainnya sesuai dengan kebutuhan bisnis Anda',

	'Scheduler' => 'Penjadwal',
	'Allows you to Configure Cron Task' => 'Memungkinkan Anda mengonfigurasi Tugas Cron',

	'Webforms' => 'Formulir Web',
	'Allows you to manage Webforms' => 'Kelola Formulir Web',
	'LBL_CREATING_NEW' => 'Membuat baru',
	'LBL_EDITING' => 'Mengedit',
	'LBL_EDIT_RECORD' => 'Edit',
	'LBL_DELETE_RECORD' => 'Hapus',

	//Menu Editor
	'LBL_ADD_MOVE_MENU_ITEMS' => 'Menambahkan/Memindahkan Item Menu',
	'LBL_ADD_MENU_ITEM' => 'Menambahkan Item Menu',
	'LBL_MAX' => 'Maks',
	
	//Tax Calculations
	'LBL_TAX_CALCULATIONS' => 'Perhitungan Pajak',
	'LBL_TAX_DESC'=>'Kelola berbagai jenis tarif pajak, seperti Pajak Penjualan, PPN, dll.,',
	'LBL_PRODUCT_SERVICE_TAXES' => 'Pajak Produk & Jasa',
	'LBL_SHIPPING_HANDLING_TAXES' => 'Pajak Pengiriman & Penanganan',
	'LBL_ADD_NEW_TAX' => 'Tambah Pajak Baru',
	'LBL_EDIT_TAX' => 'Edit Pajak',
	'LBL_TAX_NAME' =>  'Nama Pajak',
	'LBL_TAX_VALUE' => 'Nilai Pajak',
	'LBL_STATUS' => 'Status',
	'LBL_TAX_STATUS_DESC' => 'Aktifkan kotak centang untuk mengaktifkan pajak',
	'LBL_ENTER_TAX_NAME' => 'Masukkan nama pajak',
	'LBL_ENTER_TAX_VALUE' => 'Masukkan nilai pajak',
	'LBL_TAX_NAME_EXIST' => 'Nama Pajak sudah ada',
	'LBL_TAXES' => 'Pajak',
	'LBL_CHARGES_AND ITS_TAXES' => 'Biaya (& pajaknya)',
	'LBL_TAX_REGIONS' => 'Wilayah Pajak',
	'LBL_NO_REGION_EXISTS' => 'Tidak ada Wilayah',
	'LBL_TYPE' => 'Jenis',
	'LBL_CALCULATION' => 'Perhitungan',
	'LBL_ADD_NEW_CHARGE' => 'Tambahkan Biaya Baru',
	'LBL_ADD_NEW_TAX_FOR_CHARGE' => 'Tambahkan Pajak Baru untuk Ditagihkan',
	'LBL_CHARGE_NAME' => 'Biaya Nama',
	'LBL_CHARGE_NAME_EXIST' => 'Nama Biaya sudah ada',
	'LBL_VALUE' => 'Nilai',
	'LBL_IS_TAXABLE' => 'Kena Pajak',
	'LBL_AVAILABLE_REGIONS' => 'Wilayah yang Tersedia',
	'LBL_ADD_NEW_REGION' => 'Tambah Wilayah Baru',
	'LBL_TAX_REGION_DESC' => 'Wilayah Pajak akan muncul saat membuat Pajak Variabel, dan dapat dipilih saat membuat Penawaran, Faktur, Pesanan Penjualan, Pesanan Pembelian',
	'LBL_TAX_CALCULATION' => 'Perhitungan Pajak',
	'LBL_SIMPLE' => 'Sederhana',
	'LBL_COMPOUND' => 'Majemuk',
	'LBL_DEDUCTED' => 'Dipotong',
	'LBL_TAX_TYPE' => 'Jenis Pajak',
	'LBL_FIXED' => 'Tetap',
	'LBL_VARIABLE' => 'Variabel',
	'LBL_COMPOUND_ON' => 'Gabungan Aktif',
	'LBL_DEFAULT_VALUE' => 'Bawaan',
	'LBL_ADD_TAX_BRACKET' => 'Tambahkan Braket Pajak',
	'LBL_TAX_BRACKETS_DESC' => 'Jika Anda tidak menetapkan nilai pajak untuk suatu wilayah, nilai bawaan akan digunakan',
	'LBL_SELECT_SIMPLE_TAXES' => 'Pilih Pajak Sederhana',
	'LBL_REGION_NAME' => 'Nama Wilayah',
	'LBL_ENTER_REGION_NAME' => 'Masukkan Nama Wilayah',
	'LBL_EDIT_REGION' => 'Edit Wilayah',
	'LBL_TAX_REGION_EXIST' => 'Nama Wilayah sudah ada',
	'LBL_EDIT_CHARGE' => 'Edit Biaya',
	'LBL_CHARGE_FORMAT' => 'Format Biaya',
	'LBL_FLAT' => 'Tetap',
	'LBL_DIRECT_PRICE' => 'Harga Langsung',
	'LBL_PERCENT' => 'Persen',
	'LBL_CHARGE_TYPE' => 'Jenis Biaya',
	'LBL_CHARGE_VALUE' => 'Nilai Biaya',
	'LBL_ENTER_CHARGE_NAME' => 'Masukkan Nama Biaya',
	'LBL_ENTER_CHARGE_VALUE' => 'Masukkan Nilai Biaya',
	'LBL_REGIONS' => 'Wilayah',
	'LBL_ENABLE_TAXES_FOR_CHARGE' => 'Aktifkan jika biaya dikenakan pajak',
	'LBL_SELECT_TAX' => 'Pilih Pajak',
	'LBL_SELECT_TAXES' => 'Pilih Pajak',
	'LBL_SELECT_REGIONS' => 'Pilih Wilayah',
	'LBL_SELECT_TAX_DESC' => 'Hanya pajak atas biaya yang ditampilkan',
	'LBL_CHARGE_STORE_DISC' => 'Nilai biaya selalu disimpan dalam mata uang dasar',
	'LBL_DEDUCTED_TAX_DISC' => 'Pajak yang dipotong dihitung berdasarkan total Barang, dan dipotong dari Total',

	//Terms & conditions
	'LBL_TERMS_AND_CONDITIONS' => 'Syarat & Ketentuan',
	'LBL_SPECIFY_TERMS_AND_CONDITIONS' => 'Tentukan Syarat & Ketentuan di sini',
	//Announcements
	'LBL_ANNOUNCEMENTS' => 'Pengumuman',
	'LBL_ENTER_ANNOUNCEMENT_HERE' => 'Masukkan pengumuman di sini',
	'LBL_ANNOUNCEMENT_DESC' => 'Ubah teks yang muncul di pengumuman tampilkan di bagian atas setiap halaman',

	//Outgoing Server
	'LBL_RESET_TO_DEFAULT' => 'Atur Ulang ke Default',
	'LBL_SERVER_NAME' => 'Nama Server',
	'LBL_USER_NAME' => 'Nama Pengguna',
	'LBL_PASSWORD' => 'Kata Sandi',
	'LBL_FROM_EMAIL' => 'Dari Email',
    'LBL_SERVER_TYPE' => 'Jenis Server',
    'LBL_OTHERS' => 'Lainnya',
    'LBL_GMAIL' => 'Gmail',
    'LBL_HOTMAIL' => 'Hotmail',
    'LBL_YAHOO' => 'Yahoo',
    'LBL_OFFICE365' => 'Office365',
    'LBL_VTIGER' => 'Vtiger',
	'LBL_REQUIRES_AUTHENTICATION' => 'Memerlukan Autentikasi',
	'LBL_OUTGOING_SERVER' => 'Server Surat Keluar',
	'LBL_OUTGOING_SERVER_DESC' => 'Konfigurasikan detail Server Surat Keluar Anda',
	'LBL_DEFAULT'=>'Secara default, pengaturan akun SMTP untuk server keluar dikonfigurasi ke server email od1.vtiger.com. Untuk mencegah email keluar tersaring oleh filter spam di server email ISP penerima Anda, kami sarankan Anda menerapkan salah satu dari berikut ini.',
	'LBL_OPTIONS1'=>'Kirim email dari server email Anda<br>
					- Masukkan detail akun SMTP (Nama Server, Nama Pengguna, Kata Sandi) untuk akun yang sama seperti yang dimasukkan di alamat email DARI.',
	'LBL_OPTIONS2'=>"Tambahkan server vtiger.com sebagai pengirim email resmi untuk domain Anda <b>(perusahaan_anda.com)</b> saat Anda menggunakan <b>Email Dari (misalnya: support@perusahaan_anda.com)</b>.<br>
						-Untuk memastikan bahwa email Anda tidak ditolak oleh Server penerima sebagai SPAM, 
						catatan TXT yang disebutkan di bawah ini harus ditambahkan ke catatan DNS domain Anda",
	'LBL_MAIL_SERVER_SMTP'=>'Pengaturan Server Email (SMTP)',
	'LBL_OUTGOING_SERVER_FROM_FIELD'=>'CATATAN: Jika kolom "Dari Email" dikosongkan, maka alamat Email Pengguna akan diambil.',
	'LBL_TESTMAILSTATUS'=>'Status Email Uji: ',
	'LBL_MAILSENDERROR'=>'Email tidak dapat dikirim ke pengguna admin. Silakan periksa ID email admin/Pengaturan Server',
	
	//Configuration Editor
	'LBL_CONFIG_EDITOR' => 'Editor Konfigurasi',
	'LBL_CONFIG_DESCRIPTION' => 'Edit detail Konfigurasi vtiger CRM',
	'LBL_CONFIG_FILE' => 'config.inc.php',
	'LBL_MB' => 'MB',

	//Config Editor Fields
	'LBL_MINI_CALENDAR_DISPLAY' => 'Tampilan Kalender Mini',
	'LBL_WORLD_CLOCK_DISPLAY' => 'Tampilan Jam Dunia',
	'LBL_CALCULATOR_DISPLAY' => 'Tampilan Kalkulator',
	'LBL_USE_RTE' => 'Gunakan RTE',
	'LBL_HELPDESK_SUPPORT_EMAILID' => 'ID Email Dukungan Helpdesk',
	'LBL_HELPDESK_SUPPORT_NAME' => 'Nama Dukungan Helpdesk',
	'LBL_MAX_UPLOAD_SIZE' => 'Ukuran Unggahan Maksimum (Maks. %sMB)',
	'LBL_MAX_HISTORY_VIEWED' => 'Riwayat Maksimum yang Dilihat',
	'LBL_DEFAULT_MODULE' => 'Modul Default',
	'LBL_MAX_TEXT_LENGTH_IN_LISTVIEW' => 'Panjang teks maksimum dalam Tampilan Daftar',
	'LBL_MAX_ENTRIES_PER_PAGE_IN_LISTVIEW' => 'Entri maksimum per halaman dalam Tampilan Daftar',
	'LBL_EMAIL_TRACKING' => 'Aktifkan pelacakan email',
	'LBL_INVALID_EMAILID' => 'Id Email Tidak Valid',
	'LBL_INVALID_SUPPORT_NAME' => 'Nama Tidak Valid',
	'LBL_INVALID_MODULE' => 'Modul Tidak Valid',
	'LBL_INVALID_NUMBER' => 'Nomor Tidak Valid',
	'LBL_FIELDS_INFO_IS_EMPTY' => 'Informasi kolom kosong',

	//CustomRecordNumbering
	'LBL_SUCCESSFULLY_UPDATED' => 'Berhasil Diperbarui',
	'LBL_CUSTOMIZE_RECORD_NUMBERING' => 'Penomoran Modul',
	'LBL_MODULE_ENTITY_NUMBER_CUSTOMIZATION' => 'Kustomisasi Nomor Entitas Modul',
	'LBL_UPDATE_MISSING_RECORD_SEQUENCE' => 'Perbarui Urutan Rekaman yang Hilang',
	'LBL_USE_PREFIX' => 'Gunakan Awalan',
    'LBL_PREFIX_IN_USE' => 'Awalan sudah digunakan',
	'LBL_START_SEQUENCE' => 'Mulai Urutan',

	//Company Details
	'organizationname' => 'Nama Perusahaan',
	'logoname' => 'Logo Perusahaan',
	'address' => 'Alamat',
	'city' => 'Kota',
	'state' => 'Negara Bagian',
	'code'  => 'Kode Pos',
	'country' => 'Negara',
	'phone' => 'Telepon',
	'fax' => 'Faks',
	'website' => 'Situs Web',
	'vatid' => 'ID PPN',
	'facebook' => 'Facebook',
    'twitter' => 'Twitter',
    'linkedin' => 'LinkedIn',
	'LBL_IMAGE_CORRUPTED' => 'Virus terdeteksi atau Gambar yang diunggah rusak',
	'LBL_LOGO_RECOMMENDED_MESSAGE' => 'Ukuran yang diizinkan 150X40 piksel (.jpeg, .jpg, .png, .gif, .pjpeg, format .x-png).',
	'LBL_COMPANY_INFORMATION' => 'Informasi Perusahaan',
	'LBL_UPDATE' => 'Perbarui',
	'LBL_UPDATE_LOGO' => 'Perbarui Logo',
	'LBL_COMPANY_LOGO' => 'Logo Perusahaan',
    'LBL_NO_LOGO_EDIT_AND_UPLOAD' => 'Tidak ada gambar, edit dan unggah gambar',
	'LBL_EDIT_COMPANY_DETAILS_MESSAGE' => 'Untuk mengedit detail perusahaan, silakan klik Ikon Pengaturan > Tambah/Hapus Pengguna > Perusahaan ',
    
    'LBL_ACTIVE' => 'Aktif',
    'LBL_INACTIVE' => 'Tidak Active',
    
    //show last scan in workflows and mailconverter
    'LBL_DISABLED' => 'Dinonaktifkan',
    'LBL_RUNNING' => 'Berjalan',
    'LBL_LAST_SCAN_TIMED_OUT' => 'Waktu pemindaian terakhir habis',
    'LBL_LAST_SCAN_AT' => 'Terakhir dipindai pada ',
    'LBL_TIME_TAKEN' => ' waktu yang dibutuhkan ',
    'LBL_SHORT_SECONDS' => 'detik',
	
	//Email Templates
	'EmailTemplate' => 'Templat Email',
	'LBL_TEMPLATE_NAME' => 'Nama Templat',
	'LBL_DESCRIPTION' => 'Deskripsi',
	'LBL_SUBJECT' => 'Subjek',
	
	//User Login History
	'LoginHistory' => 'Riwayat Login Pengguna',
	'LBL_LOGIN_HISTORY_DETAILS' => 'Riwayat Login',
	'LBL_LOGIN_HISTORY_DESCRIPTION' => 'Detail Riwayat Login',
	'LBL_USER_NAME'=> 'Nama Pengguna',
	'LBL_USER_IP_ADDRESS'=> 'Alamat IP Pengguna', 
	'LBL_LOGIN_TIME' => 'Waktu Masuk',
	'LBL_LOGGED_OUT_TIME' => 'Waktu Keluar', 
	'LBL_STATUS' => 'Status',
    
    // Leads and Potentials Mapping 
    'LBL_SAVED_SUCCESSFULLY' => 'Berhasil Disimpan',
	'LBL_DELETED_SUCCESSFULLY' => 'Berhasil Dihapus',
	'LBL_INVALID_MAPPING' => 'Pemetaan Tidak Valid',
    'LBL_FIELD_LABEL' => 'Label Bidang',
	'LBL_FIELD_TYPE' => 'Jenis Bidang',
	'LBL_MAPPING_WITH_OTHER_MODULES' => 'Pemetaan dengan Modul Lain',
    'LBL_ADD_MAPPING' => 'Tambah Pemetaan',
	'LBL_NONE' => 'Tidak ada',
    
    //Field Type Translation
	'phone' => 'Telepon',
	'picklist' => 'Daftar Pilihan',
	'email' => 'Email',
	'text' => 'String',
	'currency' => 'Mata Uang',
	'multiSelectCombo' => 'Kotak Kombo Multi-Pilih',
	'time' => 'Waktu',
	'textArea' => 'Area Teks',
	'url' => 'Url',
	'string' => 'String',
	'checkBox' => 'Kotak Centang',
	'date' => 'Tanggal',
	'decimal' => 'Desimal',
	'percent' => 'Persen',
	'skype' => 'Skype',
	'image' => 'Gambar',
	'LBL_DEFAULT_TAX_MODE' => 'Mode Pajak Default',
	'LBL_RELATIONSHIPS' => 'Hubungan',
    
    'LBL_MODULE_BUILDER_DESCRIPTION' => 'Membuat modul baru',
    
	'LBL_EXTENSION_STORE' => 'Toko Ekstensi',
    'LBL_GATEWAY_CONFIGURATION' => 'Konfigurasi Gerbang Pembayaran',
    'MAIN_PRODUCT_WHITELABEL' => 'Pelabelan putih CRM',
    'LBL_WHITE_LABELING_INFO' => 'Mengaktifkan ini akan menghapus ikon umpan balik, tautan video, video fitur baru, dan footer dari CRM.',
    'LBL_WHITE_LABELING_INFO_MSG' => 'Mengaktifkan ini akan menghapus tombol bantuan dan footer dari CRM.',
	/*Vtiger7 Language Strings*/
    'LBL_USER_MANAGEMENT' => 'Manajemen Pengguna',
    'LBL_MODULE_MANAGEMENT' => 'Manajer Modul',
    'LBL_AUTOMATION' => 'Otomatisasi',
    'LBL_CONFIGURATION' => 'Konfigurasi',
    'LBL_MARKETING_SALES' => 'Pemasaran & Penjualan',
    'LBL_INVOICES' => 'Faktur',
    'LBL_SUPPORT' => 'Dukungan',
    'LBL_TEMPLATES' => 'Templat',
    'LBL_MODULE_CUSTOMIZATION' => 'Tata Letak & Kolom Modul',
    'LBL_TAX_MANAGEMENT' => 'Manajemen Pajak',
    'LBL_TERMS_AND_CONDITIONS' => 'Syarat dan Ketentuan',
    'LBL_GATEWAY_CONFIGURATION' => 'Langganan',
    'LBL_LEAD_MAPPING' => 'Pemetaan Data Konversi Prospek',
    'LBL_OPPORTUNITY_MAPPING' => 'Pemetaan Peluang ke Proyek',
    'LBL_PICKLIST_DEPENDENCY' => 'Ketergantungan Daftar Pilihan',
    'LBL_MY_TAGS' => 'Tag Saya',
	'LBL_ADD_MODULE' => 'Tambah Modul',
    'LBL_SMART_NOTIFICATIONS' => 'Notifikasi Cerdas',
    'LBL_FORECAST_SETTINGS' => 'Pengaturan Prakiraan Cuaca',
    'LBL_SEARCH_FOR_SETTINGS' => 'Pengaturan Pencarian',
    'LBL_GOOGLE' => 'Google',
    'LBL_QUICKBOOKS' => 'QuickBooks',
    'LBL_XERO' => 'Xero',
    'LBL_TALLY' => 'Tally',
    'LBL_SHOPPINGCART' => 'ShoppingCart',
	'LBL_PHONE_CONFIGURATION' => 'Konfigurasi Telepon',
);

$jsLanguageStrings = array(
	'JS_PLEASE_SELECT_ATLEAST_ONE_MEMBER_FOR_A_GROUP' => 'Silakan pilih setidaknya satu anggota untuk satu grup',
	'JS_GROUP_DELETED_SUCCESSFULLY' => 'Group deleted successfully',
	'JS_TAX_SAVED_SUCCESSFULLY' => 'Tax Saved Successfully',
	'JS_TAX_DISABLED' => 'Tax disabled',
	'JS_TAX_ENABLED' => 'Tax Enabled',
	'JS_SELECT_SIMPLE_TAXES' => 'Select Simple Taxes',
	'JS_TAX_REGION_SAVED_SUCCESSFULLY' => 'Tax Region Saved Successfully',
	'JS_TAX_REGION_DELETED_SUCCESSFULLY' => 'Tax Region Deleted Successfully',
	'JS_INVENTORY_CHARGE_SAVED_SUCCESSFULLY' => 'Inventory Charge Saved Successfully',
	'JS_INVENTORY_CHARGE_DELETED_SUCCESSFULLY' => 'Inventory Charge Deleted Successfully',
	'JS_DELETE_CHARGE_DESC' => 'Deleting this charge will affect all the inventory records with this existing charge. Do you wish to continue?',
	'JS_DELETE_REGION_DESC' => 'Deleting this region will affect all the inventory taxes with this existing region. Do you wish to continue?',
	'JS_SELECT_REGIONS' => 'Select Regions',
	'JS_DELETE' => 'Delete',
	'JS_EDIT' => 'Edit',
	'JS_ANNOUNCEMENT_SAVED' => 'Announcement Saved',
	'JS_CONFIRM_DEFAULT_SETTINGS' => 'Are you sure that you want to change the server details to the default server values',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_1TO5' => 'Please enter value in the range 1-%sMB',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_1TO100' => 'Please enter value in the range 1-100',
	'JS_RECORD_NUMBERING_SAVED_SUCCESSFULLY_FOR' => 'Record Numbering Successfully saved for',
	'JS_RECORD_NUMBERING_UPDATED_SUCCESSFULLY_FOR' => 'Record Numbering Updated Successfully for',
	'JS_SEQUENCE_NUMBER_MESSAGE' => 'Sequence Number should be greater than or equal to',
	'LBL_WRONG_IMAGE_TYPE' => 'not supported Image type',
	'LBL_MAXIMUM_SIZE_EXCEEDS' => 'You can upload maximum size of 1MB only',
	'LBL_NO_LOGO_SELECTED' => 'No logo selected',
	'JS_CONFIGURATION_DETAILS_SAVED' => 'Configuration Details Saved',
	'JS_TERMS_AND_CONDITIONS_SAVED' => 'Terms and conditions saved',
	'JS_DEFAULT_TAX_MODE_SET_AS' => 'Default tax mode set as ',
    'JS_INVALID_URL' => 'Invalid URL',
    'JS_LBL_TAX_REGION_EXIST' => 'Region Name already exists',
    'JS_LOGO_IMAGE_DIMENSIONS_WRONG' => 'Logo Image dimensions did not match the allowed dimension. Resize your image and try again.',
);
