<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	//Basic Field Names
	'LBL_NEW' => 'Baru',
	'LBL_WORKFLOW' => 'Alur Kerja',
	'LBL_CREATING_WORKFLOW' => 'Membuat Alur Kerja',
	'LBL_EDITING_WORKFLOW' => 'Mengedit Alur Kerja',
	'LBL_ADD_RECORD' => 'Alur Kerja Baru',

	//Edit view
	'LBL_STEP_1' => 'Langkah 1',
	'LBL_ENTER_BASIC_DETAILS_OF_THE_WORKFLOW' => 'Masukkan detail dasar Alur Kerja',
	'LBL_SPECIFY_WHEN_TO_EXECUTE' => 'Tentukan kapan Alur Kerja ini akan dijalankan',
	'ON_FIRST_SAVE' => 'Hanya pada penyimpanan pertama',
	'ONCE' => 'Sampai kondisi pertama kali benar',
	'ON_EVERY_SAVE' => 'Setiap kali rekaman disimpan',
	'ON_MODIFY' => 'Setiap kali rekaman dimodifikasi',
	'ON_SCHEDULE' => 'Jadwal',
	'MANUAL' => 'Sistem',
	'SCHEDULE_WORKFLOW' => 'Jadwalkan Alur Kerja',
	'ADD_CONDITIONS' => 'Tambahkan Kondisi',
	'ADD_TASKS' => 'Tambahkan Tindakan',

	//Step2 edit view
	'LBL_EXPRESSION' => 'Ekspresi',
	'LBL_FIELD_NAME' => 'Kolom',
	'LBL_SET_VALUE' => 'Tetapkan Nilai',
	'LBL_USE_FIELD' => 'Gunakan Kolom',
	'LBL_USE_FUNCTION' => 'Gunakan Fungsi',
	'LBL_RAW_TEXT' => 'Teks mentah',
	'LBL_ENABLE_TO_CREATE_FILTERS' => 'Aktifkan untuk membuat Filter',
	'LBL_CREATED_IN_OLD_LOOK_CANNOT_BE_EDITED' => 'Alur kerja ini dibuat dalam tampilan lama. Kondisi yang dibuat dalam tampilan lama tidak dapat diedit. Anda dapat memilih untuk membuat ulang kondisi, atau menggunakan kondisi yang ada tanpa mengubahnya.',
	'LBL_USE_EXISTING_CONDITIONS' => 'Gunakan kondisi yang ada',
	'LBL_RECREATE_CONDITIONS' => 'Buat Ulang Kondisi',
	'LBL_SAVE_AND_CONTINUE' => 'Simpan & Lanjutkan',

	//Step3 edit view
	'LBL_ACTIVE' => 'Aktif',
	'LBL_TASK_TYPE' => 'Jenis Tindakan',
	'LBL_TASK_TITLE' => 'Judul Tindakan',
	'LBL_ADD_TASKS_FOR_WORKFLOW' => 'Tambahkan Tindakan untuk Alur Kerja',
	'LBL_EXECUTE_TASK' => 'Jalankan Tindakan',
	'LBL_SELECT_OPTIONS' => 'Pilih Opsi',
	'LBL_ADD_FIELD' => 'Tambahkan kolom',
	'LBL_ADD_TIME' => 'Tambahkan waktu',
	'LBL_TITLE' => 'Judul',
	'LBL_PRIORITY' => 'Prioritas',
	'LBL_ASSIGNED_TO' => 'Ditugaskan kepada',
	'LBL_TIME' => 'Waktu',
	'LBL_DUE_DATE' => 'Tanggal Jatuh Tempo',
	'LBL_THE_SAME_VALUE_IS_USED_FOR_START_DATE' => 'Nilai yang sama digunakan untuk tanggal mulai',
	'LBL_EVENT_NAME' => 'Nama Acara',
	'LBL_TYPE' => 'Jenis',
	'LBL_METHOD_NAME' => 'Nama Metode',
	'LBL_RECEPIENTS' => 'Penerima',
	'LBL_ADD_FIELDS' => 'Tambah Kolom',
	'LBL_SMS_TEXT' => 'Pesan SMS',
	'LBL_SET_FIELD_VALUES' => 'Tetapkan Nilai Kolom',
	'LBL_ADD_FIELD' => 'Tambah Kolom',
	'LBL_IN_ACTIVE' => 'Aktif',
	'LBL_SEND_NOTIFICATION' => 'Kirim Notifikasi',
	'LBL_START_TIME' => 'Waktu Mulai',
	'LBL_START_DATE' => 'Tanggal Mulai',
	'LBL_END_TIME' => 'Waktu Berakhir',
	'LBL_END_DATE' => 'Tanggal Berakhir',
	'LBL_ENABLE_REPEAT' => 'Aktifkan Ulangi',
	'LBL_NO_METHOD_IS_AVAILABLE_FOR_THIS_MODULE' => 'Tidak ada metode yang tersedia untuk modul ini',
	
	'LBL_NO_TASKS_ADDED' => 'Tidak Ada Tindakan',
	'LBL_CANNOT_DELETE_DEFAULT_WORKFLOW' => 'Anda Tidak Dapat Menghapus Alur Kerja Default',
	'LBL_MODULES_TO_CREATE_RECORD' => 'Buat rekaman di',
	'LBL_EXAMPLE_EXPRESSION' => 'Ekspresi',
	'LBL_EXAMPLE_RAWTEXT' => 'Teks Mentah',
	'LBL_VTIGER' => 'Vtiger',
	'LBL_EXAMPLE_FIELD_NAME' => 'Bidang',
	'LBL_NOTIFY_OWNER' => 'beri_tahu_pemilik',
	'LBL_ANNUAL_REVENUE' => 'pendapatan_tahunan',
	'LBL_EXPRESSION_EXAMPLE2' => "jika negara tujuan == 'India' maka gabungkan(nama depan,' ',nama belakang) jika tidak, gabungkan(nama belakang,' ',nama depan) akhir",
	'LBL_FROM' => 'Dari',
	'LBL_RUN_WORKFLOW' => 'Jalankan Alur Kerja',
	'LBL_AT_TIME' => 'Pada Waktunya',
	'LBL_HOURLY' => 'Per Jam',
	'Optional' => 'Opsional',
	'ENTER_FROM_EMAIL_ADDRESS'=> 'Masukkan alamat email Dari',
	'LBL_ADD_TASK' => 'Tambahkan Tindakan',
    'Portal Pdf Url' =>'URL PDF Portal',

	'LBL_DAILY' => 'Harian',
	'LBL_WEEKLY' => 'Mingguan',
	'LBL_ON_THESE_DAYS' => 'Pada hari-hari ini',
	'LBL_MONTHLY_BY_DATE' => 'Bulanan berdasarkan Tanggal',
	'LBL_MONTHLY_BY_WEEKDAY' => 'Bulanan berdasarkan Hari Kerja',
	'LBL_YEARLY' => 'Tahunan',
	'LBL_SPECIFIC_DATE' => 'Pada Tanggal Tertentu',
	'LBL_CHOOSE_DATE' => 'Pilih Tanggal',
	'LBL_SELECT_MONTH_AND_DAY' => 'Pilih Bulan dan Tanggal',
	'LBL_SELECTED_DATES' => 'Tanggal yang Dipilih',
	'LBL_EXCEEDING_MAXIMUM_LIMIT' => 'Batas maksimum terlampaui',
	'LBL_NEXT_TRIGGER_TIME' => 'Waktu pemicu berikutnya aktif',
    'LBL_ADD_TEMPLATE' => 'Tambah Templat',
    'LBL_LINEITEM_BLOCK_GROUP' => 'Blok Item Baris untuk Pajak Grup',
    'LBL_LINEITEM_BLOCK_INDIVIDUAL' => 'Blok Item Baris untuk Pajak Individu',
	'LBL_MESSAGE' => 'Pesan',
    'LBL_ADD_PDF' => 'Tambah PDF',
	
	//Translation for module
	'Calendar' => 'Tugas',
	'Send Mail' => 'Kirim Email',
	'Invoke Custom Function' => 'Panggil Fungsi Kustom',
	'Create Todo' => 'Buat Tugas',
	'Create Event' => 'Buat Acara',
	'Update Fields' => 'Perbarui Bidang',
	'Create Entity' => 'Buat Rekaman',
	'SMS Task' => 'Tugas SMS',
	'Mobile Push Notification' => 'Notifikasi Push Seluler',
    
    // v7 translations
    'LBL_WORKFLOW_NAME' => 'Nama Alur Kerja',
    'LBL_TARGET_MODULE' => 'Modul Target',
    'LBL_WORKFLOW_TRIGGER' => 'Pemicu Alur Kerja',
    'LBL_TRIGGER_WORKFLOW_ON' => 'Alur Kerja Pemicu Aktif',
    'LBL_RECORD_CREATION' => 'Pembuatan Rekaman',
    'LBL_RECORD_UPDATE' => 'Pembaruan Rekaman',
    'LBL_TIME_INTERVAL' => 'Interval Waktu',
    'LBL_RECURRENCE' => 'Pengulangan',
    'LBL_FIRST_TIME_CONDITION_MET' => 'Hanya kondisi pertama kali terpenuhi',
    'LBL_EVERY_TIME_CONDITION_MET' => 'Setiap kali kondisi terpenuhi',
    'LBL_WORKFLOW_CONDITION' => 'Kondisi Alur Kerja',
    'LBL_WORKFLOW_ACTIONS' => 'Tindakan Alur Kerja',
    'LBL_DELAY_ACTION' => 'Tindakan Tunda',
    'LBL_FREQUENCY' => 'Frekuensi',
    'LBL_SELECT_FIELDS' => 'Pilih Kolom',
    'LBL_INCLUDES_CREATION' => 'Termasuk Pembuatan',
    'LBL_ACTION_FOR_WORKFLOW' => 'Tindakan untuk Alur Kerja',
    'LBL_WORKFLOW_SEARCH' => 'Cari Berdasarkan Nama',
	'LBL_ACTION_TYPE' => 'Jenis Tindakan (Jumlah Aktif)',
	'LBL_VTEmailTask' => 'Email',
    'LBL_VTEntityMethodTask' => 'Fungsi Kustom',
    'LBL_VTCreateTodoTask' => 'Tugas',
    'LBL_VTCreateEventTask' => 'Acara',
    'LBL_VTUpdateFieldsTask' => 'Pembaruan Lapangan',
    'LBL_VTSMSTask' => 'SMS', 
    'LBL_VTPushNotificationTask' => 'Notifikasi Seluler',
    'LBL_VTCreateEntityTask' => 'Buat Rekaman',
	'LBL_MAX_SCHEDULED_WORKFLOWS_EXCEEDED' => 'Jumlah maksimum (%s) alur kerja terjadwal telah terlampaui',
    
    'is' => 'adalah %s',
    'contains' => 'berisi %s',
    'does not contain' => 'tidak berisi %s',
    'starts with' => 'dimulai dengan %s',
    'ends with' => 'berakhir dengan %s',
    'has changed' => 'telah berubah',
    'is empty' => 'kosong',
    'is not empty' => 'tidak kosong',
    'equal to' => 'sama dengan %s',
    'less than' => 'kurang dari %s',
    'greater than' => 'lebih besar dari %s',
    'does not equal' => 'tidak sama dengan %s',
    'less than or equal to' => 'kurang dari atau sama dengan %s',
    'greater than or equal to' => 'lebih besar dari atau sama dengan %s',
    'is not' => 'bukan %s',
    'has changed to' => 'telah berubah menjadi %s',
    'has changed from' => 'telah berubah dari %s',
    'before' => 'sebelum %s',
    'after' => 'sesudah %s',
    'is today' => 'hari ini',
    'is tomorrow' => 'besok',
    'is yesterday' => 'kemarin',
	'previous month' => 'bulan sebelumnya',
	'current month' => 'bulan ini',
	'next month' => 'bulan depan',
    'less than days ago' => 'kurang dari %s hari yang lalu',
    'less than days later' => 'kurang dari %s hari kemudian',
    'more than days ago' => 'lebih dari %s hari yang lalu',
    'more than days later' => 'lebih dari %s hari kemudian',
    'days ago' => '%s hari yang lalu',
    'days later' => '%s hari kemudian',
    'between' => 'antara %s',
    'in less than' => 'dalam waktu kurang dari %s',
    'in more than' => 'dalam lebih dari %s',
    'is added' => 'ditambahkan',
	'week days later' => '%s minggu kemudian',
    'more than week days later' => 'lebih dari %s minggu hari kemudian',
    'less than week days later' => 'kurang dari %s hari seminggu kemudian',
    'week days ago' => '%s hari seminggu yang lalu',
    'more than week days ago' => 'lebih dari %s hari seminggu yang lalu',
    'less than week days ago' => 'kurang dari %s hari seminggu yang lalu',
);

$jsLanguageStrings = array(
	'JS_STATUS_CHANGED_SUCCESSFULLY' => 'Status berhasil diubah',
	'JS_TASK_DELETED_SUCCESSFULLY' => 'Tindakan berhasil dihapus',
	'JS_SAME_FIELDS_SELECTED_MORE_THAN_ONCE' => 'Kolom yang sama dipilih lebih dari sekali',
	'JS_WORKFLOW_SAVED_SUCCESSFULLY' => 'Alur kerja berhasil disimpan',
    'JS_CHECK_START_AND_END_DATE'=>'Tanggal & Waktu Akhir harus lebih besar atau sama dengan Tanggal & Waktu Mulai',
    'JS_TASK_STATUS_CHANGED' => 'Status tugas berhasil diubah.',
    'JS_WORKFLOWS_STATUS_CHANGED' => 'Status alur kerja berhasil diubah.',
    'VTEmailTask' => 'Kirim Email',
    'VTEntityMethodTask' => 'Panggil Fungsi Kustom',
    'VTCreateTodoTask' => 'Buat Tugas',
    'VTCreateEventTask' => 'Buat Acara',
    'VTUpdateFieldsTask' => 'Perbarui Kolom',
    'VTSMSTask' => 'Tugas SMS', 
    'VTPushNotificationTask' => 'Notifikasi Push Seluler',
    'VTCreateEntityTask' => 'Buat Rekaman',
    'LBL_EXPRESSION_INVALID' => 'Ekspresi Tidak Valid'
);

